<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AgentXM.Examples.PawMatch.CSharp</RootNamespace>
    <AssemblyName>pawmatch</AssemblyName>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../dotnet-csharp-lib/src/AgentXM.Examples.TinyFlags.CSharp/AgentXM.Examples.TinyFlags.CSharp.csproj" />
  </ItemGroup>
</Project>
