/**
 * Generate the registry Effect HTTP client from the committed OpenAPI spec.
 *
 * Usage:
 *   pnpm exec nx run registry-client:generate:registry-client
 */

// @effect-diagnostics nodeBuiltinImport:off globalConsole:off — generator process adapter owns synchronous descriptors and entry-point diagnostics
import * as NodeServices from "@effect/platform-node/NodeServices";
import * as Data from "effect/Data";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import { format, resolveConfig } from "prettier";
import * as childProcess from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

const CORE_ROOT = path.join(import.meta.dirname, "..");
const SPEC_PATH = path.join(CORE_ROOT, "specs/registry-openapi.json");
const OUTPUT_DIR = path.join(CORE_ROOT, "src/__generated__");
const OUTPUT_PATH = path.join(OUTPUT_DIR, "registry-client.ts");
const CLIENT_NAME = "RegistryClient";

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

class ClientGenerationFailed extends Data.TaggedError("ClientGenerationFailed")<{
  readonly detail: string;
  readonly cause?: unknown;
}> {}

// Regular files avoid captured-pipe dependencies and keep all subprocess output scoped.
const result = {
  stdout: await Effect.runPromise(
    Effect.scoped(
      Effect.gen(function* () {
        const files = yield* FileSystem.FileSystem;
        const paths = yield* Path.Path;
        const temporary = yield* files.makeTempDirectoryScoped({ prefix: "axm-openapi-client-" });
        const stdoutPath = paths.join(temporary, "stdout");
        const stderrPath = paths.join(temporary, "stderr");
        const stdout = yield* Effect.acquireRelease(
          Effect.try({
            try: () => fs.openSync(stdoutPath, "wx", 0o600),
            catch: (cause) =>
              new ClientGenerationFailed({ detail: "Could not open generator output", cause }),
          }),
          (fd) =>
            Effect.try({
              try: () => fs.closeSync(fd),
              catch: (cause) =>
                new ClientGenerationFailed({ detail: "Could not close generator output", cause }),
            }).pipe(Effect.ignore),
        );
        const stderr = yield* Effect.acquireRelease(
          Effect.try({
            try: () => fs.openSync(stderrPath, "wx", 0o600),
            catch: (cause) =>
              new ClientGenerationFailed({ detail: "Could not open generator errors", cause }),
          }),
          (fd) =>
            Effect.try({
              try: () => fs.closeSync(fd),
              catch: (cause) =>
                new ClientGenerationFailed({ detail: "Could not close generator errors", cause }),
            }).pipe(Effect.ignore),
        );
        const child = yield* Effect.try({
          try: () =>
            childProcess.spawnSync(
              "pnpm",
              ["exec", "openapigen", "--spec", SPEC_PATH, "--name", CLIENT_NAME],
              {
                cwd: CORE_ROOT,
                stdio: ["ignore", stdout, stderr],
                timeout: 30_000,
              },
            ),
          catch: (cause) =>
            new ClientGenerationFailed({ detail: "Could not run OpenAPI generator", cause }),
        });
        const errorBytes = Number((yield* files.stat(stderrPath)).size);
        if (errorBytes > 16 * 1024 * 1024)
          return yield* new ClientGenerationFailed({
            detail: "Generator errors exceed sixteen mebibytes",
          });
        if (child.error !== undefined || child.status !== 0)
          return yield* new ClientGenerationFailed({
            detail: "OpenAPI generator failed",
            cause: child.error ?? (yield* files.readFileString(stderrPath)),
          });
        const size = Number((yield* files.stat(stdoutPath)).size);
        if (size === 0 || size > 16 * 1024 * 1024)
          return yield* new ClientGenerationFailed({
            detail: "Generator output is empty or exceeds sixteen mebibytes",
          });
        return yield* files.readFileString(stdoutPath);
      }),
    ).pipe(Effect.provide(NodeServices.layer)),
  ),
};

const header = `/**
 * @generated by registry-client:generate:registry-client (openapigen)
 * Source:     packages/supporting/registry-client/specs/registry-openapi.json
 * Regenerate: pnpm exec nx run registry-client:generate:registry-client
 * DO NOT EDIT - changes are overwritten on regeneration.
 */
// @effect-diagnostics anyUnknownInErrorContext:off — generated OpenAPI transport errors are translated by the registry adapter
/* eslint-disable */

`;

/**
 * openapigen has no format-aware mapping, so the spec's ISO date-time
 * component is emitted as a plain string schema. Swap the generated
 * declaration for the shared kernel timestamp schema so client responses
 * decode timestamps to DateTime.Utc (wire format unchanged).
 */
const swapDateTimeSchema = (source: string): string => {
  const typeAnchorPattern = /^export type IsoDateTimeString = string;?$/m;
  const constAnchorPattern = /^export const IsoDateTimeString = .*$/m;
  const importAnchorPattern = /^import \* as Stream from "effect\/Stream";?$/m;
  if (
    !typeAnchorPattern.test(source) ||
    !constAnchorPattern.test(source) ||
    !importAnchorPattern.test(source)
  ) {
    console.error(
      "generate-registry-client: IsoDateTimeString anchors not found in generated output; " +
        "update swapDateTimeSchema for the new generated shape. This post-processor " +
        "(and patches/@effect__openapi-generator@*.patch) exist while these upstream " +
        "issues are open: https://github.com/Effect-TS/effect/issues/6368 " +
        "https://github.com/Effect-TS/effect/issues/6373 " +
        "https://github.com/Effect-TS/effect/pull/6403 " +
        "https://github.com/Effect-TS/effect/pull/6404",
    );
    process.exit(1);
  }
  return source
    .replace(
      importAnchorPattern,
      (line) =>
        `${line}\nimport { DateTimeUtcSchema } from "@agentxm/extension-model/unstable/date-time"`,
    )
    .replace(typeAnchorPattern, "export type IsoDateTimeString = typeof DateTimeUtcSchema.Type")
    .replace(constAnchorPattern, "export const IsoDateTimeString = DateTimeUtcSchema");
};

/**
 * The component swap above only covers fields routed through the shared
 * IsoDateTimeString component. Spec fields that inline `format: "date-time"`
 * are emitted as plain string schemas, so map those to the kernel schema as
 * well, and fail loudly on any date-time-formatted string shape this mapping
 * does not recognize.
 */
const inlineDateTimeStringPatterns: ReadonlyArray<RegExp> = [
  /Schema\.String\.annotate\(\{\s*format:\s*"date-time"\s*\}\)/g,
  /Schema\.String\.check\(Schema\.isMinLength\(1,\s*\{\s*format:\s*"date-time"\s*\}\)\)/g,
];

const mapInlineDateTimeSchemas = (source: string): string => {
  const mapped = inlineDateTimeStringPatterns.reduce(
    (current, pattern) => current.replace(pattern, "DateTimeUtcSchema"),
    source,
  );
  if (/format:\s*"date-time"/.test(mapped)) {
    console.error(
      "generate-registry-client: unrecognized date-time schema shape in generated output; " +
        "extend inlineDateTimeStringPatterns so the field maps to DateTimeUtcSchema.",
    );
    process.exit(1);
  }
  return mapped;
};

/**
 * The SSE decoder supplies an explicit `id: undefined` when a frame has no
 * id. JSON Schema optional properties currently render as `optionalKey`,
 * which accepts an absent property but rejects that wire value. Narrow this
 * rewrite to SSE event structs so generated clients accept both forms.
 */
const fixSseOptionalIds = (source: string): string => {
  const pattern = /"id": Schema\.optionalKey\(Schema\.String\),(?=\s+"event":)/g;
  const matches = source.match(pattern);
  if (source.includes("const sseEventRequest") && matches === null) {
    console.error(
      "generate-registry-client: SSE optional-id anchor not found; re-evaluate the generated event schema.",
    );
    process.exit(1);
  }
  return source.replace(pattern, '"id": Schema.optional(Schema.String),');
};

const source =
  header + fixSseOptionalIds(mapInlineDateTimeSchemas(swapDateTimeSchema(result.stdout)));

const formatted = await Effect.runPromise(
  Effect.tryPromise({
    try: async () =>
      format(source, { ...(await resolveConfig(OUTPUT_PATH)), filepath: OUTPUT_PATH }),
    catch: (cause) =>
      new ClientGenerationFailed({ detail: "Could not format generated client", cause }),
  }),
);
fs.writeFileSync(OUTPUT_PATH, formatted);

console.log(`Generated: ${path.relative(CORE_ROOT, OUTPUT_PATH)}`);
