/**
 * Generate the registry Effect HTTP client from the committed OpenAPI spec.
 *
 * Usage:
 *   pnpm exec nx run registry-client:generate:registry-client
 */

// @effect-diagnostics nodeBuiltinImport:off globalConsole:off — generator process adapter owns synchronous descriptors and entry-point diagnostics
import * as NodeServices from "@effect/platform-node/NodeServices";
import * as Data from "effect/Data";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import { format, resolveConfig } from "prettier";
import * as childProcess from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

const CORE_ROOT = path.join(import.meta.dirname, "..");
const SPEC_PATH = path.join(CORE_ROOT, "specs/registry-openapi.json");
const OUTPUT_DIR = path.join(CORE_ROOT, "src/__generated__");
const OUTPUT_PATH = path.join(OUTPUT_DIR, "registry-client.ts");
const CLIENT_NAME = "RegistryClient";

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

class ClientGenerationFailed extends Data.TaggedError("ClientGenerationFailed")<{
  readonly detail: string;
  readonly cause?: unknown;
}> {}

// Regular files avoid captured-pipe dependencies and keep all subprocess output scoped.
const result = await Effect.runPromise(
  Effect.scoped(
    Effect.gen(function* () {
      const files = yield* FileSystem.FileSystem;
      const paths = yield* Path.Path;
      const temporary = yield* files.makeTempDirectoryScoped({ prefix: "axm-openapi-client-" });
      const stdoutPath = paths.join(temporary, "stdout");
      const stderrPath = paths.join(temporary, "stderr");
      const stdout = yield* Effect.acquireRelease(
        Effect.try({
          try: () => fs.openSync(stdoutPath, "wx", 0o600),
          catch: (cause) =>
            new ClientGenerationFailed({ detail: "Could not open generator output", cause }),
        }),
        (fd) =>
          Effect.try({
            try: () => fs.closeSync(fd),
            catch: (cause) =>
              new ClientGenerationFailed({ detail: "Could not close generator output", cause }),
          }).pipe(Effect.ignore),
      );
      const stderr = yield* Effect.acquireRelease(
        Effect.try({
          try: () => fs.openSync(stderrPath, "wx", 0o600),
          catch: (cause) =>
            new ClientGenerationFailed({ detail: "Could not open generator errors", cause }),
        }),
        (fd) =>
          Effect.try({
            try: () => fs.closeSync(fd),
            catch: (cause) =>
              new ClientGenerationFailed({ detail: "Could not close generator errors", cause }),
          }).pipe(Effect.ignore),
      );
      const child = yield* Effect.try({
        try: () =>
          childProcess.spawnSync(
            "pnpm",
            ["exec", "openapigen", "--spec", SPEC_PATH, "--name", CLIENT_NAME],
            {
              cwd: CORE_ROOT,
              stdio: ["ignore", stdout, stderr],
              timeout: 30_000,
            },
          ),
        catch: (cause) =>
          new ClientGenerationFailed({ detail: "Could not run OpenAPI generator", cause }),
      });
      const errorBytes = Number((yield* files.stat(stderrPath)).size);
      if (errorBytes > 16 * 1024 * 1024)
        return yield* new ClientGenerationFailed({
          detail: "Generator errors exceed sixteen mebibytes",
        });
      if (child.error !== undefined || child.status !== 0)
        return yield* new ClientGenerationFailed({
          detail: "OpenAPI generator failed",
          cause: child.error ?? (yield* files.readFileString(stderrPath)),
        });
      const size = Number((yield* files.stat(stdoutPath)).size);
      if (size === 0 || size > 16 * 1024 * 1024)
        return yield* new ClientGenerationFailed({
          detail: "Generator output is empty or exceeds sixteen mebibytes",
        });
      return {
        stdout: yield* files.readFileString(stdoutPath),
        warnings: (yield* files.readFileString(stderrPath)).trim(),
      };
    }),
  ).pipe(Effect.provide(NodeServices.layer)),
);

// The generator reports schemas it could not represent faithfully on stderr
// while still succeeding; show them so a contract change cannot hide behind one.
if (result.warnings.length > 0) {
  console.warn(`generate-registry-client: OpenAPI generator warnings:\n${result.warnings}`);
}

const header = `/**
 * @generated by registry-client:generate:registry-client (openapigen)
 * Source:     packages/supporting/registry-client/specs/registry-openapi.json
 * Regenerate: pnpm exec nx run registry-client:generate:registry-client
 * DO NOT EDIT - changes are overwritten on regeneration.
 */
// @effect-diagnostics anyUnknownInErrorContext:off — generated OpenAPI transport errors are translated by the registry adapter
/* eslint-disable */

`;

/**
 * openapigen has no format-aware mapping, so the spec's ISO date-time
 * component is emitted as a plain string schema. Swap the generated
 * declaration for the shared kernel timestamp schema so client responses
 * decode timestamps to DateTime.Utc (wire format unchanged).
 */
const swapDateTimeSchema = (source: string): string => {
  const typeAnchorPattern = /^export type IsoDateTimeString = string;?$/m;
  const constAnchorPattern = /^export const IsoDateTimeString = .*$/m;
  const importAnchorPattern = /^import \* as Stream from "effect\/Stream";?$/m;
  if (
    !typeAnchorPattern.test(source) ||
    !constAnchorPattern.test(source) ||
    !importAnchorPattern.test(source)
  ) {
    console.error(
      "generate-registry-client: IsoDateTimeString anchors not found in generated output; " +
        "update swapDateTimeSchema for the new generated shape.",
    );
    process.exit(1);
  }
  return source
    .replace(
      importAnchorPattern,
      (line) =>
        `${line}\nimport { DateTimeUtcSchema } from "@agentxm/extension-model/unstable/date-time"`,
    )
    .replace(typeAnchorPattern, "export type IsoDateTimeString = typeof DateTimeUtcSchema.Type")
    .replace(constAnchorPattern, "export const IsoDateTimeString = DateTimeUtcSchema");
};

/**
 * The component swap above only covers fields routed through the shared
 * IsoDateTimeString component. Fail loudly when any other schema still
 * carries `format: "date-time"`, so it cannot silently decode as a plain
 * string. The generator emits quoted annotation keys, which the guard accepts
 * along with unquoted ones.
 */
const rejectUnmappedDateTimeSchemas = (source: string): string => {
  if (/"?format"?\s*:\s*"date-time"/.test(source)) {
    console.error(
      "generate-registry-client: a date-time schema outside the IsoDateTimeString component " +
        "remains in generated output; route it through IsoDateTimeString in the contract or " +
        "map it to DateTimeUtcSchema here.",
    );
    process.exit(1);
  }
  return source;
};

const source = header + rejectUnmappedDateTimeSchemas(swapDateTimeSchema(result.stdout));

const formatted = await Effect.runPromise(
  Effect.tryPromise({
    try: async () =>
      format(source, { ...(await resolveConfig(OUTPUT_PATH)), filepath: OUTPUT_PATH }),
    catch: (cause) =>
      new ClientGenerationFailed({ detail: "Could not format generated client", cause }),
  }),
);
fs.writeFileSync(OUTPUT_PATH, formatted);

console.log(`Generated: ${path.relative(CORE_ROOT, OUTPUT_PATH)}`);
