/**
 * @generated by cli:generate:telemetry-client (openapigen)
 * Source:     apps/cli/specs/telemetry-openapi.json
 * Regenerate: pnpm exec nx run cli:generate:telemetry-client
 * DO NOT EDIT - changes are overwritten on regeneration.
 */
// @effect-diagnostics anyUnknownInErrorContext:off — generated OpenAPI transport errors are translated by the telemetry adapter
/* eslint-disable */

import * as Data from "effect/Data";
import * as Effect from "effect/Effect";
import type { SchemaError } from "effect/Schema";
import * as Schema from "effect/Schema";
import type * as HttpClient from "effect/http/HttpClient";
import * as HttpClientError from "effect/http/HttpClientError";
import * as HttpClientRequest from "effect/http/HttpClientRequest";
import * as HttpClientResponse from "effect/http/HttpClientResponse";
// non-recursive definitions
export type TelemetryMetaResponse = {
  readonly ok: true;
  readonly service: "telemetry";
  readonly message: string;
  readonly docs: string | null;
  readonly openapi: string | null;
};
export const TelemetryMetaResponse = Schema.Struct({
  ok: Schema.Literal(true),
  service: Schema.Literal("telemetry"),
  message: Schema.String,
  docs: Schema.Union([Schema.String, Schema.Null]),
  openapi: Schema.Union([Schema.String, Schema.Null]),
}).annotate({
  title: "Telemetry Meta Response",
  description:
    "Service metadata and documentation entrypoints exposed by the telemetry root endpoint. Documentation URLs are null when docs are disabled for the environment.",
  identifier: "TelemetryMetaResponse",
});
export type DecodeErrorResponseEncoded = {
  readonly kind: "DecodeErrorResponse";
  readonly type: string;
  readonly title: string;
  readonly status: number;
  readonly detail: string;
  readonly instance?: string;
  readonly code: string;
};
export const DecodeErrorResponseEncoded = Schema.Struct({
  kind: Schema.Literal("DecodeErrorResponse"),
  type: Schema.String,
  title: Schema.String,
  status: Schema.Number.check(Schema.isInt().annotate({ expected: "an integer" })),
  detail: Schema.String,
  instance: Schema.optionalKey(Schema.String),
  code: Schema.String,
}).annotate({ identifier: "DecodeErrorResponseEncoded" });
export type IsoDateTimeString = string;
export const IsoDateTimeString = Schema.String.annotate({
  title: "ISO Date-Time String",
  description: "A date and time string (e.g. 2024-01-15T12:00:00.000Z).",
  format: "date-time",
  identifier: "IsoDateTimeString",
});
export type AgentId =
  | "adal"
  | "fx"
  | "muse-code"
  | "mimo-code"
  | "coder-agents"
  | "aider-desk"
  | "amp"
  | "antigravity"
  | "antigravity-cli"
  | "augment"
  | "claude-code"
  | "cline"
  | "codearts-agent"
  | "codebuddy"
  | "codemaker"
  | "codestudio"
  | "codex"
  | "command-code"
  | "continue"
  | "cortex"
  | "crush"
  | "cursor"
  | "deepagents"
  | "devin"
  | "dexto"
  | "droid"
  | "firebender"
  | "forgecode"
  | "gemini-cli"
  | "github-copilot-cli"
  | "goose"
  | "grok-cli"
  | "hermes"
  | "ibm-bob"
  | "iflow-cli"
  | "junie"
  | "lingma"
  | "kilo"
  | "kimi-cli"
  | "kiro-cli"
  | "kode"
  | "mcpjam"
  | "minimax-code"
  | "mistral-vibe"
  | "mux"
  | "neovate"
  | "openclaw"
  | "opencode"
  | "openhands"
  | "ona"
  | "pi"
  | "vscode"
  | "pochi"
  | "qoder"
  | "qoder-cn"
  | "qwen-code"
  | "replit"
  | "roo"
  | "rovodev"
  | "tabnine-cli"
  | "trae-cn"
  | "trae"
  | "warp"
  | "windsurf"
  | "zencoder"
  | "zed"
  | "zenflow"
  | "chatgpt"
  | "claude-ai"
  | "cowork"
  | "gemini-app";
export const AgentId = Schema.Literals([
  "adal",
  "fx",
  "muse-code",
  "mimo-code",
  "coder-agents",
  "aider-desk",
  "amp",
  "antigravity",
  "antigravity-cli",
  "augment",
  "claude-code",
  "cline",
  "codearts-agent",
  "codebuddy",
  "codemaker",
  "codestudio",
  "codex",
  "command-code",
  "continue",
  "cortex",
  "crush",
  "cursor",
  "deepagents",
  "devin",
  "dexto",
  "droid",
  "firebender",
  "forgecode",
  "gemini-cli",
  "github-copilot-cli",
  "goose",
  "grok-cli",
  "hermes",
  "ibm-bob",
  "iflow-cli",
  "junie",
  "lingma",
  "kilo",
  "kimi-cli",
  "kiro-cli",
  "kode",
  "mcpjam",
  "minimax-code",
  "mistral-vibe",
  "mux",
  "neovate",
  "openclaw",
  "opencode",
  "openhands",
  "ona",
  "pi",
  "vscode",
  "pochi",
  "qoder",
  "qoder-cn",
  "qwen-code",
  "replit",
  "roo",
  "rovodev",
  "tabnine-cli",
  "trae-cn",
  "trae",
  "warp",
  "windsurf",
  "zencoder",
  "zed",
  "zenflow",
  "chatgpt",
  "claude-ai",
  "cowork",
  "gemini-app",
]).annotate({
  title: "Agent ID",
  description: "Verified coding agent identifier in the capability catalog.",
  examples: ["claude-code", "codex", "cursor"],
  identifier: "AgentId",
});
export type ExtensionName = string;
export const ExtensionName = Schema.String.annotate({
  title: "Extension Name",
  description:
    "The name of an extension — lowercase letters, numbers, and hyphens (e.g. my-skill).",
  examples: ["my-skill", "code-review", "prettier"],
})
  .check(Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }))
  .check(
    Schema.isPattern(new RegExp("^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$", "u")).annotate({
      expected: "a string matching the RegExp ^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$",
      identifier: "ExtensionName",
    }),
  );
export type TelemetryEvent = {
  readonly eventId: string;
  readonly event: string;
  readonly distinctId: string;
  readonly timestamp: string;
  readonly properties?: {
    readonly [x: string]:
      string | number | boolean | null | ReadonlyArray<string | number | boolean | null>;
  };
  readonly userProperties?: {
    readonly set?: {
      readonly [x: string]:
        string | number | boolean | null | ReadonlyArray<string | number | boolean | null>;
    };
    readonly setOnce?: {
      readonly [x: string]:
        string | number | boolean | null | ReadonlyArray<string | number | boolean | null>;
    };
  };
  readonly groups?: { readonly [x: string]: string };
  readonly sessionId?: string;
  readonly anonymous?: boolean;
};
export const TelemetryEvent = Schema.Struct({
  eventId: Schema.String.annotate({
    description:
      "Producer-assigned event identity retained across delivery retries for downstream deduplication.",
  }).check(Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" })),
  event: Schema.String.check(
    Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
  ).check(
    Schema.isPattern(new RegExp("^(?!skill_install_completed$).+$", "u")).annotate({
      expected: "a string matching the RegExp ^(?!skill_install_completed$).+$",
    }),
  ),
  distinctId: Schema.String.check(
    Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
  ),
  timestamp: Schema.String.check(
    Schema.isMinLength(1).annotate({
      expected: "a value with a length of at least 1",
      format: "date-time",
    }),
  ),
  properties: Schema.optionalKey(
    Schema.Record(
      Schema.String,
      Schema.Union([
        Schema.Union([
          Schema.String,
          Schema.Number.check(Schema.isFinite().annotate({ expected: "a finite number" })),
          Schema.Boolean,
          Schema.Null,
        ]),
        Schema.Array(
          Schema.Union([
            Schema.String,
            Schema.Number.check(Schema.isFinite().annotate({ expected: "a finite number" })),
            Schema.Boolean,
            Schema.Null,
          ]),
        ),
      ]).annotate({
        title: "User Property Value",
        description:
          "Telemetry user property value limited to JSON primitives or flat arrays of JSON primitives.",
      }),
    ),
  ),
  userProperties: Schema.optionalKey(
    Schema.Struct({
      set: Schema.optionalKey(
        Schema.Record(
          Schema.String,
          Schema.Union([
            Schema.Union([
              Schema.String,
              Schema.Number.check(Schema.isFinite().annotate({ expected: "a finite number" })),
              Schema.Boolean,
              Schema.Null,
            ]),
            Schema.Array(
              Schema.Union([
                Schema.String,
                Schema.Number.check(Schema.isFinite().annotate({ expected: "a finite number" })),
                Schema.Boolean,
                Schema.Null,
              ]),
            ),
          ]).annotate({
            title: "User Property Value",
            description:
              "Telemetry user property value limited to JSON primitives or flat arrays of JSON primitives.",
          }),
        ),
      ),
      setOnce: Schema.optionalKey(
        Schema.Record(
          Schema.String,
          Schema.Union([
            Schema.Union([
              Schema.String,
              Schema.Number.check(Schema.isFinite().annotate({ expected: "a finite number" })),
              Schema.Boolean,
              Schema.Null,
            ]),
            Schema.Array(
              Schema.Union([
                Schema.String,
                Schema.Number.check(Schema.isFinite().annotate({ expected: "a finite number" })),
                Schema.Boolean,
                Schema.Null,
              ]),
            ),
          ]).annotate({
            title: "User Property Value",
            description:
              "Telemetry user property value limited to JSON primitives or flat arrays of JSON primitives.",
          }),
        ),
      ),
    }),
  ),
  groups: Schema.optionalKey(Schema.Record(Schema.String, Schema.String)),
  sessionId: Schema.optionalKey(Schema.String),
  anonymous: Schema.optionalKey(Schema.Boolean),
}).annotate({
  title: "Telemetry Event",
  description: "One analytics event captured by the AgentXM client or integration.",
  identifier: "TelemetryEvent",
});
export type TelemetryClientContext = { readonly name: string; readonly version: string };
export const TelemetryClientContext = Schema.Struct({
  name: Schema.String.check(
    Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
  ),
  version: Schema.String.check(
    Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
  ),
}).annotate({
  title: "Telemetry Client Context",
  description: "Identifies the client emitting telemetry, including its name and version.",
  identifier: "TelemetryClientContext",
});
export type TelemetryEventsReceipt = { readonly receipt: "received"; readonly eventCount: number };
export const TelemetryEventsReceipt = Schema.Struct({
  receipt: Schema.Literal("received"),
  eventCount: Schema.Number.check(Schema.isInt().annotate({ expected: "an integer" }))
    .check(
      Schema.isGreaterThanOrEqualTo(1).annotate({ expected: "a value greater than or equal to 1" }),
    )
    .check(
      Schema.isLessThanOrEqualTo(100).annotate({ expected: "a value less than or equal to 100" }),
    ),
}).annotate({
  description:
    "Validated and scheduled for bounded best-effort forwarding; not durable storage or provider ingestion.",
  identifier: "TelemetryEventsReceipt",
});
export type TelemetryPayloadTooLargeErrorEncoded = {
  readonly kind: "TelemetryPayloadTooLargeError";
  readonly type: string;
  readonly title: string;
  readonly status: number;
  readonly detail: string;
  readonly instance?: string;
  readonly code: string;
};
export const TelemetryPayloadTooLargeErrorEncoded = Schema.Struct({
  kind: Schema.Literal("TelemetryPayloadTooLargeError"),
  type: Schema.String,
  title: Schema.String,
  status: Schema.Number.check(Schema.isInt().annotate({ expected: "an integer" })),
  detail: Schema.String,
  instance: Schema.optionalKey(Schema.String),
  code: Schema.String,
}).annotate({ identifier: "TelemetryPayloadTooLargeErrorEncoded" });
export type TelemetryReportingClient = {
  readonly name: string;
  readonly version: string;
  readonly runtime: "bun" | "node";
  readonly runtimeVersion: string;
  readonly platform: string;
  readonly architecture: string;
  readonly callerAgent?:
    | "adal"
    | "fx"
    | "muse-code"
    | "mimo-code"
    | "coder-agents"
    | "aider-desk"
    | "amp"
    | "antigravity"
    | "antigravity-cli"
    | "augment"
    | "claude-code"
    | "cline"
    | "codearts-agent"
    | "codebuddy"
    | "codemaker"
    | "codestudio"
    | "codex"
    | "command-code"
    | "continue"
    | "cortex"
    | "crush"
    | "cursor"
    | "deepagents"
    | "devin"
    | "dexto"
    | "droid"
    | "firebender"
    | "forgecode"
    | "gemini-cli"
    | "github-copilot-cli"
    | "goose"
    | "grok-cli"
    | "hermes"
    | "ibm-bob"
    | "iflow-cli"
    | "junie"
    | "lingma"
    | "kilo"
    | "kimi-cli"
    | "kiro-cli"
    | "kode"
    | "mcpjam"
    | "minimax-code"
    | "mistral-vibe"
    | "mux"
    | "neovate"
    | "openclaw"
    | "opencode"
    | "openhands"
    | "ona"
    | "pi"
    | "vscode"
    | "pochi"
    | "qoder"
    | "qoder-cn"
    | "qwen-code"
    | "replit"
    | "roo"
    | "rovodev"
    | "tabnine-cli"
    | "trae-cn"
    | "trae"
    | "warp"
    | "windsurf"
    | "zencoder"
    | "zed"
    | "zenflow"
    | "chatgpt"
    | "claude-ai"
    | "cowork"
    | "gemini-app"
    | "unknown";
  readonly ci: boolean;
};
export const TelemetryReportingClient = Schema.Struct({
  name: Schema.String.annotate({ description: "Stable client identifier, for example `cli`." })
    .check(Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }))
    .check(
      Schema.isMaxCodePoints(32).annotate({ expected: "a string with at most 32 code points" }),
    )
    .check(
      Schema.isPattern(new RegExp("^[a-z][a-z0-9-]*$", "u")).annotate({
        expected: "a string matching the RegExp ^[a-z][a-z0-9-]*$",
      }),
    ),
  version: Schema.String.annotate({
    description: "Released client version; development builds carry their build suffix here.",
  })
    .check(Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }))
    .check(
      Schema.isMaxCodePoints(64).annotate({ expected: "a string with at most 64 code points" }),
    )
    .check(
      Schema.isPattern(new RegExp("^[0-9A-Za-z.+-]+$", "u")).annotate({
        expected: "a string matching the RegExp ^[0-9A-Za-z.+-]+$",
      }),
    ),
  runtime: Schema.Literals(["bun", "node"]).annotate({
    description: "JavaScript runtime executing the client.",
  }),
  runtimeVersion: Schema.String.annotate({
    description: "Version of the executing runtime, or `unknown`.",
  })
    .check(Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }))
    .check(
      Schema.isMaxCodePoints(64).annotate({ expected: "a string with at most 64 code points" }),
    )
    .check(
      Schema.isPattern(new RegExp("^[0-9A-Za-z.+-]+$", "u")).annotate({
        expected: "a string matching the RegExp ^[0-9A-Za-z.+-]+$",
      }),
    ),
  platform: Schema.String.annotate({
    description: "Operating system platform identifier, for example `darwin`.",
  })
    .check(Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }))
    .check(
      Schema.isMaxCodePoints(32).annotate({ expected: "a string with at most 32 code points" }),
    )
    .check(
      Schema.isPattern(new RegExp("^[a-z][a-z0-9-]*$", "u")).annotate({
        expected: "a string matching the RegExp ^[a-z][a-z0-9-]*$",
      }),
    ),
  architecture: Schema.String.annotate({
    description: "CPU architecture identifier, for example `arm64`.",
  })
    .check(Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }))
    .check(
      Schema.isMaxCodePoints(32).annotate({ expected: "a string with at most 32 code points" }),
    )
    .check(
      Schema.isPattern(new RegExp("^[a-z][a-z0-9-]*$", "u")).annotate({
        expected: "a string matching the RegExp ^[a-z][a-z0-9-]*$",
      }),
    ),
  callerAgent: Schema.optionalKey(
    Schema.Literals([
      "adal",
      "fx",
      "muse-code",
      "mimo-code",
      "coder-agents",
      "aider-desk",
      "amp",
      "antigravity",
      "antigravity-cli",
      "augment",
      "claude-code",
      "cline",
      "codearts-agent",
      "codebuddy",
      "codemaker",
      "codestudio",
      "codex",
      "command-code",
      "continue",
      "cortex",
      "crush",
      "cursor",
      "deepagents",
      "devin",
      "dexto",
      "droid",
      "firebender",
      "forgecode",
      "gemini-cli",
      "github-copilot-cli",
      "goose",
      "grok-cli",
      "hermes",
      "ibm-bob",
      "iflow-cli",
      "junie",
      "lingma",
      "kilo",
      "kimi-cli",
      "kiro-cli",
      "kode",
      "mcpjam",
      "minimax-code",
      "mistral-vibe",
      "mux",
      "neovate",
      "openclaw",
      "opencode",
      "openhands",
      "ona",
      "pi",
      "vscode",
      "pochi",
      "qoder",
      "qoder-cn",
      "qwen-code",
      "replit",
      "roo",
      "rovodev",
      "tabnine-cli",
      "trae-cn",
      "trae",
      "warp",
      "windsurf",
      "zencoder",
      "zed",
      "zenflow",
      "chatgpt",
      "claude-ai",
      "cowork",
      "gemini-app",
      "unknown",
    ]),
  ),
  ci: Schema.Boolean.annotate({
    description: "Whether the client detected a continuous-integration host.",
  }),
}).annotate({
  title: "Telemetry Reporting Client",
  description: "Bounded facts about the client build and host that reported a failure.",
  identifier: "TelemetryReportingClient",
});
export type TelemetryErrorReceipt = { readonly eventId: string; readonly receipt: "received" };
export const TelemetryErrorReceipt = Schema.Struct({
  eventId: Schema.String.annotate({
    description: "Identity of the received report.",
    format: "uuid",
  }).check(
    Schema.isPattern(
      new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "u"),
    ).annotate({
      expected:
        "a string matching the RegExp ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    }),
  ),
  receipt: Schema.Literal("received"),
}).annotate({
  title: "Telemetry Error Receipt",
  description:
    "Synchronous receipt for a validated report. It is not durable acceptance, provider ingestion, or issue creation.",
  identifier: "TelemetryErrorReceipt",
});
export type SkillInstallEvent = {
  readonly eventId: string;
  readonly event: "skill_install_completed";
  readonly distinctId: string;
  readonly timestamp: IsoDateTimeString;
  readonly anonymous: true;
  readonly userProperties?: never;
  readonly groups?: never;
  readonly sessionId?: never;
  readonly properties:
    | {
        readonly scope: "project" | "user";
        readonly installKind: "install" | "reinstall";
        readonly targetAgents: ReadonlyArray<AgentId>;
        readonly activityId?: string;
        readonly skill: {
          readonly kind: "git";
          readonly repositoryUrl: string;
          readonly skillPath: string;
        };
        readonly revision: { readonly kind: "git"; readonly commitSha: string };
      }
    | {
        readonly scope: "project" | "user";
        readonly installKind: "install" | "reinstall";
        readonly targetAgents: ReadonlyArray<AgentId>;
        readonly activityId?: string;
        readonly skill: {
          readonly kind: "registry";
          readonly registryUrl: "https://registry.agentxm.ai";
          readonly publisherBindingId: string;
          readonly extensionType: "skill";
          readonly packageName: ExtensionName;
        };
        readonly revision: {
          readonly kind: "registry";
          readonly version: string;
          readonly integrity?: string;
        };
      };
};
export const SkillInstallEvent = Schema.Struct({
  eventId: Schema.String.annotate({ format: "uuid" }).check(
    Schema.isPattern(
      new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "u"),
    ).annotate({
      expected:
        "a string matching the RegExp ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    }),
  ),
  event: Schema.Literal("skill_install_completed"),
  distinctId: Schema.String.annotate({ format: "uuid" }).check(
    Schema.isPattern(
      new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "u"),
    ).annotate({
      expected:
        "a string matching the RegExp ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    }),
  ),
  timestamp: IsoDateTimeString,
  anonymous: Schema.Literal(true),
  userProperties: Schema.optionalKey(Schema.Never),
  groups: Schema.optionalKey(Schema.Never),
  sessionId: Schema.optionalKey(Schema.Never),
  properties: Schema.Union([
    Schema.Struct({
      scope: Schema.Literals(["project", "user"]),
      installKind: Schema.Literals(["install", "reinstall"]),
      targetAgents: Schema.Array(AgentId).check(
        Schema.isMaxLength(71).annotate({ expected: "a value with a length of at most 71" }),
      ),
      activityId: Schema.optionalKey(
        Schema.String.annotate({ format: "uuid" }).check(
          Schema.isPattern(
            new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "u"),
          ).annotate({
            expected:
              "a string matching the RegExp ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
          }),
        ),
      ),
      skill: Schema.Struct({
        kind: Schema.Literal("git"),
        repositoryUrl: Schema.String.check(
          Schema.isMaxCodePoints(2048).annotate({
            expected: "a string with at most 2048 code points",
          }),
        ).check(
          Schema.isPattern(
            new RegExp(
              "^https:\\/\\/github\\.com\\/[A-Za-z0-9][A-Za-z0-9-]*\\/[A-Za-z0-9_.-]+$",
              "u",
            ),
          ).annotate({
            expected:
              "a string matching the RegExp ^https:\\/\\/github\\.com\\/[A-Za-z0-9][A-Za-z0-9-]*\\/[A-Za-z0-9_.-]+$",
          }),
        ),
        skillPath: Schema.String.check(
          Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
        ).check(
          Schema.isMaxCodePoints(1024).annotate({
            expected: "a string with at most 1024 code points",
          }),
        ),
      }),
      revision: Schema.Struct({
        kind: Schema.Literal("git"),
        commitSha: Schema.String.check(
          Schema.isPattern(new RegExp("^[0-9a-f]{40}$", "u")).annotate({
            expected: "a string matching the RegExp ^[0-9a-f]{40}$",
          }),
        ),
      }),
    }),
    Schema.Struct({
      scope: Schema.Literals(["project", "user"]),
      installKind: Schema.Literals(["install", "reinstall"]),
      targetAgents: Schema.Array(AgentId).check(
        Schema.isMaxLength(71).annotate({ expected: "a value with a length of at most 71" }),
      ),
      activityId: Schema.optionalKey(
        Schema.String.annotate({ format: "uuid" }).check(
          Schema.isPattern(
            new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "u"),
          ).annotate({
            expected:
              "a string matching the RegExp ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
          }),
        ),
      ),
      skill: Schema.Struct({
        kind: Schema.Literal("registry"),
        registryUrl: Schema.Literal("https://registry.agentxm.ai"),
        publisherBindingId: Schema.String.check(
          Schema.isPattern(new RegExp("^hbnd_[0-7][0-9a-hjkmnp-tv-z]{25}$", "u")).annotate({
            expected: "a string matching the RegExp ^hbnd_[0-7][0-9a-hjkmnp-tv-z]{25}$",
          }),
        ),
        extensionType: Schema.Literal("skill"),
        packageName: ExtensionName,
      }),
      revision: Schema.Struct({
        kind: Schema.Literal("registry"),
        version: Schema.String.annotate({
          title: "Version",
          description: "A semver version like 1.0.0. Ranges are not allowed here.",
          examples: ["1.0.0", "2.3.1", "0.1.0-beta.1"],
        })
          .check(
            Schema.isMaxCodePoints(256).annotate({
              expected: "a string with at most 256 code points",
            }),
          )
          .check(
            Schema.isPattern(
              new RegExp(
                "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
                "u",
              ),
            ).annotate({
              expected:
                "a string matching the RegExp ^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
            }),
          ),
        integrity: Schema.optionalKey(
          Schema.String.check(
            Schema.isPattern(new RegExp("^sha512-[A-Za-z0-9+/]{86}==$", "u")).annotate({
              expected: "a string matching the RegExp ^sha512-[A-Za-z0-9+/]{86}==$",
            }),
          ),
        ),
      }),
    }),
  ]),
}).annotate({
  description:
    "One committed usable skill installation. Public coordinates are client assertions, not server-verified adoption. Unknown fields are discarded.",
  identifier: "SkillInstallEvent",
});
export type TelemetryContext = {
  readonly client: TelemetryClientContext;
  readonly os?: { readonly name: string; readonly version?: string };
  readonly runtime?: { readonly name: string; readonly version: string };
  readonly device?: { readonly arch: string };
  readonly ide?: { readonly name: string; readonly version: string };
  readonly environment?: string;
  readonly callerAgent?:
    | "adal"
    | "fx"
    | "muse-code"
    | "mimo-code"
    | "coder-agents"
    | "aider-desk"
    | "amp"
    | "antigravity"
    | "antigravity-cli"
    | "augment"
    | "claude-code"
    | "cline"
    | "codearts-agent"
    | "codebuddy"
    | "codemaker"
    | "codestudio"
    | "codex"
    | "command-code"
    | "continue"
    | "cortex"
    | "crush"
    | "cursor"
    | "deepagents"
    | "devin"
    | "dexto"
    | "droid"
    | "firebender"
    | "forgecode"
    | "gemini-cli"
    | "github-copilot-cli"
    | "goose"
    | "grok-cli"
    | "hermes"
    | "ibm-bob"
    | "iflow-cli"
    | "junie"
    | "lingma"
    | "kilo"
    | "kimi-cli"
    | "kiro-cli"
    | "kode"
    | "mcpjam"
    | "minimax-code"
    | "mistral-vibe"
    | "mux"
    | "neovate"
    | "openclaw"
    | "opencode"
    | "openhands"
    | "ona"
    | "pi"
    | "vscode"
    | "pochi"
    | "qoder"
    | "qoder-cn"
    | "qwen-code"
    | "replit"
    | "roo"
    | "rovodev"
    | "tabnine-cli"
    | "trae-cn"
    | "trae"
    | "warp"
    | "windsurf"
    | "zencoder"
    | "zed"
    | "zenflow"
    | "chatgpt"
    | "claude-ai"
    | "cowork"
    | "gemini-app"
    | "unknown";
  readonly ci?: boolean;
  readonly invocationId?: string;
};
export const TelemetryContext = Schema.Struct({
  client: TelemetryClientContext,
  os: Schema.optionalKey(
    Schema.Struct({
      name: Schema.String.check(
        Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
      ),
      version: Schema.optionalKey(Schema.String),
    }).annotate({
      title: "Operating System Context",
      description: "Operating system metadata captured alongside telemetry.",
    }),
  ),
  runtime: Schema.optionalKey(
    Schema.Struct({
      name: Schema.String.check(
        Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
      ),
      version: Schema.String.check(
        Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
      ),
    }).annotate({
      title: "Runtime Context",
      description: "Language or process runtime metadata captured alongside telemetry.",
    }),
  ),
  device: Schema.optionalKey(
    Schema.Struct({
      arch: Schema.String.check(
        Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
      ),
    }).annotate({
      title: "Device Context",
      description: "Device characteristics attached to telemetry submissions.",
    }),
  ),
  ide: Schema.optionalKey(
    Schema.Struct({
      name: Schema.String.check(
        Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
      ),
      version: Schema.String.check(
        Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }),
      ),
    }).annotate({
      title: "IDE Context",
      description:
        "Editor or IDE metadata attached when telemetry originates from a development tool.",
    }),
  ),
  environment: Schema.optionalKey(Schema.String),
  callerAgent: Schema.optionalKey(
    Schema.Literals([
      "adal",
      "fx",
      "muse-code",
      "mimo-code",
      "coder-agents",
      "aider-desk",
      "amp",
      "antigravity",
      "antigravity-cli",
      "augment",
      "claude-code",
      "cline",
      "codearts-agent",
      "codebuddy",
      "codemaker",
      "codestudio",
      "codex",
      "command-code",
      "continue",
      "cortex",
      "crush",
      "cursor",
      "deepagents",
      "devin",
      "dexto",
      "droid",
      "firebender",
      "forgecode",
      "gemini-cli",
      "github-copilot-cli",
      "goose",
      "grok-cli",
      "hermes",
      "ibm-bob",
      "iflow-cli",
      "junie",
      "lingma",
      "kilo",
      "kimi-cli",
      "kiro-cli",
      "kode",
      "mcpjam",
      "minimax-code",
      "mistral-vibe",
      "mux",
      "neovate",
      "openclaw",
      "opencode",
      "openhands",
      "ona",
      "pi",
      "vscode",
      "pochi",
      "qoder",
      "qoder-cn",
      "qwen-code",
      "replit",
      "roo",
      "rovodev",
      "tabnine-cli",
      "trae-cn",
      "trae",
      "warp",
      "windsurf",
      "zencoder",
      "zed",
      "zenflow",
      "chatgpt",
      "claude-ai",
      "cowork",
      "gemini-app",
      "unknown",
    ]),
  ),
  ci: Schema.optionalKey(Schema.Boolean),
  invocationId: Schema.optionalKey(
    Schema.String.annotate({
      description:
        "Identity of the client process invocation that produced the batch; the same identity appears on that invocation's client error reports.",
      format: "uuid",
    }).check(
      Schema.isPattern(
        new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "u"),
      ).annotate({
        expected:
          "a string matching the RegExp ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
      }),
    ),
  ),
}).annotate({
  title: "Telemetry Context",
  description: "Shared environment metadata attached to analytics event batches.",
  identifier: "TelemetryContext",
});
export type TelemetryErrorReport = {
  readonly eventId: string;
  readonly invocationId: string;
  readonly occurredAt: IsoDateTimeString;
  readonly installationId?: string;
  readonly activityId?: string;
  readonly client: TelemetryReportingClient;
  readonly command?: string;
  readonly phase: "bootstrap" | "configuration" | "command" | "output";
  readonly failure: {
    readonly kind: string;
    readonly category: string;
    readonly class: "internal" | "user" | "external";
    readonly handled: boolean;
  };
};
export const TelemetryErrorReport = Schema.Struct({
  eventId: Schema.String.annotate({
    description:
      "Report identity, fresh per report and unchanged when the same report is resubmitted.",
    format: "uuid",
  }).check(
    Schema.isPattern(
      new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "u"),
    ).annotate({
      expected:
        "a string matching the RegExp ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    }),
  ),
  invocationId: Schema.String.annotate({
    description: "Identity of the client process invocation that failed.",
    format: "uuid",
  }).check(
    Schema.isPattern(
      new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "u"),
    ).annotate({
      expected:
        "a string matching the RegExp ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    }),
  ),
  occurredAt: IsoDateTimeString,
  installationId: Schema.optionalKey(
    Schema.String.annotate({
      description:
        "Random persisted installation identity; absent when the client could not load or create it.",
      format: "uuid",
    }).check(
      Schema.isPattern(
        new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "u"),
      ).annotate({
        expected:
          "a string matching the RegExp ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
      }),
    ),
  ),
  activityId: Schema.optionalKey(
    Schema.String.annotate({
      description: "Product activity correlation identity when the invocation started one.",
      format: "uuid",
    }).check(
      Schema.isPattern(
        new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "u"),
      ).annotate({
        expected:
          "a string matching the RegExp ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
      }),
    ),
  ),
  client: TelemetryReportingClient,
  command: Schema.optionalKey(
    Schema.String.annotate({
      description:
        "Canonical command identity when known, for example `extensions install`. Never arguments.",
    })
      .check(Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }))
      .check(
        Schema.isMaxCodePoints(64).annotate({ expected: "a string with at most 64 code points" }),
      )
      .check(
        Schema.isPattern(new RegExp("^[a-z][a-z0-9:_-]*( [a-z][a-z0-9:_-]*)*$", "u")).annotate({
          expected: "a string matching the RegExp ^[a-z][a-z0-9:_-]*( [a-z][a-z0-9:_-]*)*$",
        }),
      ),
  ),
  phase: Schema.Literals(["bootstrap", "configuration", "command", "output"]).annotate({
    title: "Failure Phase",
    description:
      "The invocation phase that settled with the failure: startup, workspace configuration, command execution, or output writing.",
  }),
  failure: Schema.Struct({
    kind: Schema.String.annotate({
      description: "Stable diagnostic identifier from the client's enumerated failure set.",
    })
      .check(Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }))
      .check(
        Schema.isMaxCodePoints(64).annotate({ expected: "a string with at most 64 code points" }),
      )
      .check(
        Schema.isPattern(new RegExp("^[a-z0-9]+([._-][a-z0-9]+)*$", "u")).annotate({
          expected: "a string matching the RegExp ^[a-z0-9]+([._-][a-z0-9]+)*$",
        }),
      ),
    category: Schema.String.annotate({
      description: "AXM error category, for example `validation` or `network`.",
    })
      .check(Schema.isMinLength(1).annotate({ expected: "a value with a length of at least 1" }))
      .check(
        Schema.isMaxCodePoints(32).annotate({ expected: "a string with at most 32 code points" }),
      )
      .check(
        Schema.isPattern(new RegExp("^[a-z0-9]+([._-][a-z0-9]+)*$", "u")).annotate({
          expected: "a string matching the RegExp ^[a-z0-9]+([._-][a-z0-9]+)*$",
        }),
      ),
    class: Schema.Literals(["internal", "user", "external"]).annotate({
      title: "Error Class",
      description:
        "Classifies whether a failure is an AXM defect, a user-correctable failure, or an external dependency failure.",
    }),
    handled: Schema.Boolean.annotate({
      description: "False when the failure is an unexpected defect rather than an expected error.",
    }),
  }).annotate({
    title: "Reported Failure",
    description: "Allowlisted diagnostic identity of one terminal failure.",
  }),
}).annotate({
  title: "Telemetry Error Report",
  description:
    "One bounded, allowlisted report of a consent-controlled client invocation's terminal failure. It carries no messages, stacks, arguments, paths, or other free-form content.",
  identifier: "TelemetryErrorReport",
});
export type TelemetryEventsRequest = {
  readonly events: ReadonlyArray<SkillInstallEvent | TelemetryEvent>;
  readonly sentAt?: string;
  readonly context: TelemetryContext;
};
export const TelemetryEventsRequest = Schema.Struct({
  events: Schema.Array(Schema.Union([SkillInstallEvent, TelemetryEvent])),
  sentAt: Schema.optionalKey(Schema.String.annotate({ format: "date-time" })),
  context: TelemetryContext,
}).annotate({
  title: "Telemetry Events Request",
  description: "Request payload accepted by the telemetry events ingestion endpoint.",
  identifier: "TelemetryEventsRequest",
});
// schemas
export type MetaGet200 = TelemetryMetaResponse;
export const MetaGet200 = TelemetryMetaResponse;
export type MetaGet400 = DecodeErrorResponseEncoded;
export const MetaGet400 = DecodeErrorResponseEncoded;
export type HealthGetShallowHealth200 = { readonly status: "pass" | "warn" | "fail" };
export const HealthGetShallowHealth200 = Schema.Struct({
  status: Schema.Literals(["pass", "warn", "fail"]),
});
export type HealthGetShallowHealth400 = DecodeErrorResponseEncoded;
export const HealthGetShallowHealth400 = DecodeErrorResponseEncoded;
export type HealthGetDeepHealthParams = { readonly "x-health-key"?: string | null };
export const HealthGetDeepHealthParams = Schema.Struct({
  "x-health-key": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
});
export type HealthGetDeepHealth200 = {
  readonly status: "pass" | "warn" | "fail";
  readonly serviceId?: string | null;
  readonly version?: string | null;
  readonly releaseId?: string | null;
  readonly commit?: string | null;
  readonly environment?: string | null;
  readonly region?: string | null;
  readonly checks?: {
    readonly [x: string]: ReadonlyArray<{
      readonly componentName: string;
      readonly componentType: "datastore" | "system" | "component";
      readonly measurementName: string;
      readonly status: "pass" | "warn" | "fail";
      readonly observedValue: number;
      readonly observedUnit: string;
      readonly time: IsoDateTimeString;
      readonly output?: string | null;
    }>;
  } | null;
  readonly output?: string | null;
};
export const HealthGetDeepHealth200 = Schema.Struct({
  status: Schema.Literals(["pass", "warn", "fail"]),
  serviceId: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  version: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  releaseId: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  commit: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  environment: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  region: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  checks: Schema.optionalKey(
    Schema.Union([
      Schema.Record(
        Schema.String,
        Schema.Array(
          Schema.Struct({
            componentName: Schema.String,
            componentType: Schema.Literals(["datastore", "system", "component"]),
            measurementName: Schema.String,
            status: Schema.Literals(["pass", "warn", "fail"]),
            observedValue: Schema.Number.check(
              Schema.isFinite().annotate({ expected: "a finite number" }),
            ),
            observedUnit: Schema.String,
            time: IsoDateTimeString,
            output: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
          }),
        ),
      ),
      Schema.Null,
    ]),
  ),
  output: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
});
export type HealthGetDeepHealth400 = DecodeErrorResponseEncoded;
export const HealthGetDeepHealth400 = DecodeErrorResponseEncoded;
export type HealthGetObservabilityVerificationParams = {
  readonly "x-health-key"?: string | null;
  readonly level?: string | null;
  readonly scenario?: "effect-handled-500" | "surface-unhandled-500" | null;
  readonly scenarioId?: string | null;
};
export const HealthGetObservabilityVerificationParams = Schema.Struct({
  "x-health-key": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  level: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  scenario: Schema.optionalKey(
    Schema.Union([Schema.Literals(["effect-handled-500", "surface-unhandled-500"]), Schema.Null]),
  ),
  scenarioId: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
});
export type HealthGetObservabilityVerification200 = {
  readonly status: "ok" | "warn" | "error";
  readonly timestamp: IsoDateTimeString;
  readonly serviceId: string;
  readonly level: "basic" | "standard" | "full";
  readonly checks: {
    readonly logging?: {
      readonly status: "ok" | "warn" | "error";
      readonly correlationId: string;
    } | null;
    readonly tracing?: {
      readonly status: "ok" | "warn" | "error";
      readonly traceId?: string | null;
      readonly message?: string | null;
    } | null;
    readonly metrics?: {
      readonly status: "ok" | "warn" | "error";
      readonly counter: string;
    } | null;
    readonly errors?: {
      readonly status: "ok" | "warn" | "error";
      readonly sentryEventId?: string | null;
      readonly reason?: "sentry-issue-reporter-disabled" | null;
      readonly message?: string | null;
    } | null;
  };
};
export const HealthGetObservabilityVerification200 = Schema.Struct({
  status: Schema.Literals(["ok", "warn", "error"]),
  timestamp: IsoDateTimeString,
  serviceId: Schema.String,
  level: Schema.Literals(["basic", "standard", "full"]),
  checks: Schema.Struct({
    logging: Schema.optionalKey(
      Schema.Union([
        Schema.Struct({
          status: Schema.Literals(["ok", "warn", "error"]),
          correlationId: Schema.String,
        }),
        Schema.Null,
      ]),
    ),
    tracing: Schema.optionalKey(
      Schema.Union([
        Schema.Struct({
          status: Schema.Literals(["ok", "warn", "error"]),
          traceId: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
          message: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
        }),
        Schema.Null,
      ]),
    ),
    metrics: Schema.optionalKey(
      Schema.Union([
        Schema.Struct({ status: Schema.Literals(["ok", "warn", "error"]), counter: Schema.String }),
        Schema.Null,
      ]),
    ),
    errors: Schema.optionalKey(
      Schema.Union([
        Schema.Struct({
          status: Schema.Literals(["ok", "warn", "error"]),
          sentryEventId: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
          reason: Schema.optionalKey(
            Schema.Union([Schema.Literal("sentry-issue-reporter-disabled"), Schema.Null]),
          ),
          message: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
        }),
        Schema.Null,
      ]),
    ),
  }),
});
export type HealthGetObservabilityVerification400 = DecodeErrorResponseEncoded;
export const HealthGetObservabilityVerification400 = DecodeErrorResponseEncoded;
export type EventsIngestRequestJson = TelemetryEventsRequest;
export const EventsIngestRequestJson = TelemetryEventsRequest;
export type EventsIngest200 = TelemetryEventsReceipt;
export const EventsIngest200 = TelemetryEventsReceipt;
export type EventsIngest400 = DecodeErrorResponseEncoded;
export const EventsIngest400 = DecodeErrorResponseEncoded;
export type EventsIngest413 = TelemetryPayloadTooLargeErrorEncoded;
export const EventsIngest413 = TelemetryPayloadTooLargeErrorEncoded;
export type ErrorsIngestRequestJson = TelemetryErrorReport;
export const ErrorsIngestRequestJson = TelemetryErrorReport;
export type ErrorsIngest200 = TelemetryErrorReceipt;
export const ErrorsIngest200 = TelemetryErrorReceipt;
export type ErrorsIngest400 = DecodeErrorResponseEncoded;
export const ErrorsIngest400 = DecodeErrorResponseEncoded;

export interface OperationConfig {
  /**
   * Whether or not the response should be included in the value returned from
   * an operation.
   *
   * If set to `true`, a tuple of `[A, HttpClientResponse]` will be returned,
   * where `A` is the success type of the operation.
   *
   * If set to `false`, only the success type of the operation will be returned.
   */
  readonly includeResponse?: boolean | undefined;
}

/**
 * A utility type which optionally includes the response in the return result
 * of an operation based upon the value of the `includeResponse` configuration
 * option.
 */
export type WithOptionalResponse<A, Config extends OperationConfig | undefined> = Config extends {
  readonly includeResponse: true;
}
  ? [A, HttpClientResponse.HttpClientResponse]
  : Config extends { readonly includeResponse?: false | undefined } | undefined
    ? A
    : A | [A, HttpClientResponse.HttpClientResponse];

export const make = (
  httpClient: HttpClient.HttpClient,
  options: {
    readonly transformClient?:
      ((client: HttpClient.HttpClient) => Effect.Effect<HttpClient.HttpClient>) | undefined;
  } = {},
): TelemetryClient => {
  const unexpectedStatus = (response: HttpClientResponse.HttpClientResponse) =>
    Effect.flatMap(
      Effect.orElseSucceed(response.json, () => "Unexpected status code"),
      (description) =>
        Effect.fail(
          new HttpClientError.HttpClientError({
            reason: new HttpClientError.StatusCodeError({
              request: response.request,
              response,
              description:
                typeof description === "string" ? description : JSON.stringify(description),
            }),
          }),
        ),
    );
  const withResponse =
    <Config extends OperationConfig>(config: Config | undefined) =>
    (
      f: (response: HttpClientResponse.HttpClientResponse) => Effect.Effect<any, any>,
    ): ((request: HttpClientRequest.HttpClientRequest) => Effect.Effect<any, any>) => {
      const withOptionalResponse = (
        config?.includeResponse
          ? (response: HttpClientResponse.HttpClientResponse) =>
              Effect.map(f(response), (a) => [a, response])
          : (response: HttpClientResponse.HttpClientResponse) => f(response)
      ) as any;
      return options?.transformClient
        ? (request) =>
            Effect.flatMap(
              Effect.flatMap(options.transformClient!(httpClient), (client) =>
                client.execute(request),
              ),
              withOptionalResponse,
            )
        : (request) => Effect.flatMap(httpClient.execute(request), withOptionalResponse);
    };
  const decodeSuccess =
    <Schema extends Schema.Constraint>(schema: Schema) =>
    (response: HttpClientResponse.HttpClientResponse) =>
      HttpClientResponse.schemaBodyJson(schema)(response);
  const decodeError =
    <const Tag extends string, Schema extends Schema.Constraint>(tag: Tag, schema: Schema) =>
    (response: HttpClientResponse.HttpClientResponse) =>
      Effect.flatMap(HttpClientResponse.schemaBodyJson(schema)(response), (cause) =>
        Effect.fail(TelemetryClientError(tag, cause, response)),
      );
  return {
    httpClient,
    MetaGet: (options: Parameters<TelemetryClient["MetaGet"]>[0]) =>
      HttpClientRequest.get("/v1").pipe(
        withResponse(options?.config)(
          HttpClientResponse.matchStatus({
            "2xx": decodeSuccess(MetaGet200),
            "400": decodeError("MetaGet400", MetaGet400),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    HealthGetShallowHealth: (options: Parameters<TelemetryClient["HealthGetShallowHealth"]>[0]) =>
      HttpClientRequest.get("/v1/health").pipe(
        withResponse(options?.config)(
          HttpClientResponse.matchStatus({
            "2xx": decodeSuccess(HealthGetShallowHealth200),
            "400": decodeError("HealthGetShallowHealth400", HealthGetShallowHealth400),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    HealthGetDeepHealth: (options: Parameters<TelemetryClient["HealthGetDeepHealth"]>[0]) =>
      HttpClientRequest.get("/v1/health/dependencies").pipe(
        HttpClientRequest.setHeaders({
          "x-health-key": options?.params?.["x-health-key"] ?? undefined,
        }),
        withResponse(options?.config)(
          HttpClientResponse.matchStatus({
            "2xx": decodeSuccess(HealthGetDeepHealth200),
            "400": decodeError("HealthGetDeepHealth400", HealthGetDeepHealth400),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    HealthGetObservabilityVerification: (
      options: Parameters<TelemetryClient["HealthGetObservabilityVerification"]>[0],
    ) =>
      HttpClientRequest.get("/v1/debug/observability").pipe(
        HttpClientRequest.setUrlParams({
          level: options?.params?.["level"] as any,
          scenario: options?.params?.["scenario"] as any,
          scenarioId: options?.params?.["scenarioId"] as any,
        }),
        HttpClientRequest.setHeaders({
          "x-health-key": options?.params?.["x-health-key"] ?? undefined,
        }),
        withResponse(options?.config)(
          HttpClientResponse.matchStatus({
            "2xx": decodeSuccess(HealthGetObservabilityVerification200),
            "400": decodeError(
              "HealthGetObservabilityVerification400",
              HealthGetObservabilityVerification400,
            ),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    EventsIngest: (options: Parameters<TelemetryClient["EventsIngest"]>[0]) =>
      HttpClientRequest.post("/v1/events").pipe(
        HttpClientRequest.bodyJsonUnsafe(options.payload),
        withResponse(options.config)(
          HttpClientResponse.matchStatus({
            "2xx": decodeSuccess(EventsIngest200),
            "400": decodeError("EventsIngest400", EventsIngest400),
            "413": decodeError("EventsIngest413", EventsIngest413),
            orElse: unexpectedStatus,
          }),
        ),
      ),
    ErrorsIngest: (options: Parameters<TelemetryClient["ErrorsIngest"]>[0]) =>
      HttpClientRequest.post("/v1/errors").pipe(
        HttpClientRequest.bodyJsonUnsafe(options.payload),
        withResponse(options.config)(
          HttpClientResponse.matchStatus({
            "2xx": decodeSuccess(ErrorsIngest200),
            "400": decodeError("ErrorsIngest400", ErrorsIngest400),
            orElse: unexpectedStatus,
          }),
        ),
      ),
  };
};

export interface TelemetryClient {
  readonly httpClient: HttpClient.HttpClient;
  /**
   * Returns service metadata and the documentation entrypoints.
   */
  readonly MetaGet: {
    <Config extends OperationConfig | undefined = undefined>(options: {
      readonly config: Config;
    }): Effect.Effect<
      WithOptionalResponse<typeof MetaGet200.Type, Config>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<"MetaGet400", typeof MetaGet400.Type>
    >;
    <Config extends OperationConfig | undefined = undefined>(
      options: { readonly config?: Config | undefined } | undefined,
    ): Effect.Effect<
      WithOptionalResponse<typeof MetaGet200.Type, Config | undefined>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<"MetaGet400", typeof MetaGet400.Type>
    >;
  };
  /**
   * Returns pass/fail status. Public, no auth required.
   */
  readonly HealthGetShallowHealth: {
    <Config extends OperationConfig | undefined = undefined>(options: {
      readonly config: Config;
    }): Effect.Effect<
      WithOptionalResponse<typeof HealthGetShallowHealth200.Type, Config>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<"HealthGetShallowHealth400", typeof HealthGetShallowHealth400.Type>
    >;
    <Config extends OperationConfig | undefined = undefined>(
      options: { readonly config?: Config | undefined } | undefined,
    ): Effect.Effect<
      WithOptionalResponse<typeof HealthGetShallowHealth200.Type, Config | undefined>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<"HealthGetShallowHealth400", typeof HealthGetShallowHealth400.Type>
    >;
  };
  /**
   * Returns IETF health+json response with per-dependency check results. Requires X-Health-Key header.
   */
  readonly HealthGetDeepHealth: {
    <Config extends OperationConfig | undefined = undefined>(options: {
      readonly params?: typeof HealthGetDeepHealthParams.Encoded | undefined;
      readonly config: Config;
    }): Effect.Effect<
      WithOptionalResponse<typeof HealthGetDeepHealth200.Type, Config>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<"HealthGetDeepHealth400", typeof HealthGetDeepHealth400.Type>
    >;
    <Config extends OperationConfig | undefined = undefined>(
      options:
        | {
            readonly params?: typeof HealthGetDeepHealthParams.Encoded | undefined;
            readonly config?: Config | undefined;
          }
        | undefined,
    ): Effect.Effect<
      WithOptionalResponse<typeof HealthGetDeepHealth200.Type, Config | undefined>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<"HealthGetDeepHealth400", typeof HealthGetDeepHealth400.Type>
    >;
  };
  /**
   * Exercises observability pipelines and can simulate server error scenarios. Requires X-Health-Key header.
   */
  readonly HealthGetObservabilityVerification: {
    <Config extends OperationConfig | undefined = undefined>(options: {
      readonly params?: typeof HealthGetObservabilityVerificationParams.Encoded | undefined;
      readonly config: Config;
    }): Effect.Effect<
      WithOptionalResponse<typeof HealthGetObservabilityVerification200.Type, Config>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<
          "HealthGetObservabilityVerification400",
          typeof HealthGetObservabilityVerification400.Type
        >
    >;
    <Config extends OperationConfig | undefined = undefined>(
      options:
        | {
            readonly params?: typeof HealthGetObservabilityVerificationParams.Encoded | undefined;
            readonly config?: Config | undefined;
          }
        | undefined,
    ): Effect.Effect<
      WithOptionalResponse<typeof HealthGetObservabilityVerification200.Type, Config | undefined>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<
          "HealthGetObservabilityVerification400",
          typeof HealthGetObservabilityVerification400.Type
        >
    >;
  };
  /**
   * Validates a JSON batch and registers bounded best-effort forwarding. The 200 receipt does not imply durable storage or provider ingestion. Content-Type must be application/json. Ingress limits are owned by the edge.
   */
  readonly EventsIngest: {
    <Config extends OperationConfig | undefined = undefined>(options: {
      readonly payload: typeof EventsIngestRequestJson.Encoded;
      readonly config: Config;
    }): Effect.Effect<
      WithOptionalResponse<typeof EventsIngest200.Type, Config>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<"EventsIngest400", typeof EventsIngest400.Type>
      | TelemetryClientError<"EventsIngest413", typeof EventsIngest413.Type>
    >;
    <Config extends OperationConfig | undefined = undefined>(options: {
      readonly payload: typeof EventsIngestRequestJson.Encoded;
      readonly config?: Config | undefined;
    }): Effect.Effect<
      WithOptionalResponse<typeof EventsIngest200.Type, Config | undefined>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<"EventsIngest400", typeof EventsIngest400.Type>
      | TelemetryClientError<"EventsIngest413", typeof EventsIngest413.Type>
    >;
  };
  /**
   * Receives one bounded, allowlisted failure report from a consent-controlled client invocation.
   *
   * **Receipt.** A `200` response is a synchronous receipt: the report passed
   * validation and its forwarding was registered as bounded, best-effort
   * background work of the receiving invocation. The receipt is not durable
   * acceptance, provider ingestion, or issue creation, and the service stores
   * nothing. Forwarding may be dropped when a provider fails or the invocation's
   * background deadline passes; no exactly-once delivery is promised.
   *
   * **Report identity.** Resubmitting the same report keeps its `eventId`. The
   * service carries that identity into the provider insert and event
   * identities, but provider deduplication is not an end-to-end guarantee.
   *
   * **Declared fields only.** Only the declared, bounded fields are accepted.
   * Undeclared fields are ignored: the platform's request decoding drops them
   * before the report is processed. Reports carry no messages, stack traces,
   * arguments, paths, or other free-form content.
   */
  readonly ErrorsIngest: {
    <Config extends OperationConfig | undefined = undefined>(options: {
      readonly payload: typeof ErrorsIngestRequestJson.Encoded;
      readonly config: Config;
    }): Effect.Effect<
      WithOptionalResponse<typeof ErrorsIngest200.Type, Config>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<"ErrorsIngest400", typeof ErrorsIngest400.Type>
    >;
    <Config extends OperationConfig | undefined = undefined>(options: {
      readonly payload: typeof ErrorsIngestRequestJson.Encoded;
      readonly config?: Config | undefined;
    }): Effect.Effect<
      WithOptionalResponse<typeof ErrorsIngest200.Type, Config | undefined>,
      | HttpClientError.HttpClientError
      | SchemaError
      | TelemetryClientError<"ErrorsIngest400", typeof ErrorsIngest400.Type>
    >;
  };
}

export interface TelemetryClientError<Tag extends string, E> {
  readonly _tag: Tag;
  readonly request: HttpClientRequest.HttpClientRequest;
  readonly response: HttpClientResponse.HttpClientResponse;
  readonly cause: E;
}

class TelemetryClientErrorImpl extends Data.Error<{
  _tag: string;
  cause: any;
  request: HttpClientRequest.HttpClientRequest;
  response: HttpClientResponse.HttpClientResponse;
}> {}

export const TelemetryClientError = <Tag extends string, E>(
  tag: Tag,
  cause: E,
  response: HttpClientResponse.HttpClientResponse,
): TelemetryClientError<Tag, E> =>
  new TelemetryClientErrorImpl({
    _tag: tag,
    cause,
    response,
    request: response.request,
  }) as any;
