/**
 * @generated by core:generate:e2e-extension-matrix (packages/core/scripts/generate-e2e-extension-matrix.ts)
 * Source:     EXTENSION_TYPE_TABLE and the parity exemption ledger in packages/core/src/unstable
 * Regenerate: pnpm exec nx run core:generate:e2e-extension-matrix
 * DO NOT EDIT - changes are overwritten on regeneration.
 *
 * Plain literals on purpose: packages/cli-e2e must not depend on
 * @agentxm/client-core, so the type table is copied in rather than imported.
 */

export const EXTENSION_TYPE_MATRIX = [
  {
    type: "skill",
    plural: "skills",
    label: "Skill",
    sentenceLabel: "skill",
    placement: "per-agent",
    installInputs: false,
    e2eExemptions: [],
  },
  {
    type: "command",
    plural: "commands",
    label: "Command",
    sentenceLabel: "command",
    placement: "per-agent",
    installInputs: false,
    e2eExemptions: [],
  },
  {
    type: "mcp-server",
    plural: "mcps",
    label: "MCP Server",
    sentenceLabel: "MCP server",
    placement: "per-agent",
    installInputs: true,
    e2eExemptions: [],
  },
  {
    type: "subagent",
    plural: "subagents",
    label: "Subagent",
    sentenceLabel: "subagent",
    placement: "per-agent",
    installInputs: false,
    e2eExemptions: [],
  },
  {
    type: "files",
    plural: "files",
    label: "Context Files",
    sentenceLabel: "context files",
    placement: "workspace",
    installInputs: true,
    e2eExemptions: [],
  },
  {
    type: "rule",
    plural: "rules",
    label: "Rule",
    sentenceLabel: "rule",
    placement: "workspace",
    installInputs: false,
    e2eExemptions: [],
  },
  {
    type: "hook",
    plural: "hooks",
    label: "Hook",
    sentenceLabel: "hook",
    placement: "per-agent",
    installInputs: false,
    e2eExemptions: [],
  },
  {
    type: "knowledge",
    plural: "knowledge",
    label: "Knowledge",
    sentenceLabel: "knowledge bundle",
    placement: "workspace",
    installInputs: false,
    e2eExemptions: [],
  },
  {
    type: "pack",
    plural: "packs",
    label: "Pack",
    sentenceLabel: "pack",
    placement: "container",
    installInputs: false,
    e2eExemptions: [],
  },
] as const;

export type ExtensionTypeMatrixRow = (typeof EXTENSION_TYPE_MATRIX)[number];

export type MatrixExtensionType = ExtensionTypeMatrixRow["type"];
