packages:
  - packages/*

catalog:
  "@effect/platform-node": 4.0.0-beta.42
  "@effect/vitest": 4.0.0-beta.42
  "@types/bun": ^1.3.11
  effect: 4.0.0-beta.42
  typescript: ^5.9.3
  vitest: ^4.0.0

onlyBuiltDependencies:
  - esbuild
  - nx

patchedDependencies:
  "@effect/openapi-generator": patches/@effect__openapi-generator.patch
