name = "AgentXMExamplePawMatch"
uuid = "8d034267-c7aa-476e-be01-58f88800e3ab"
authors = ["AgentXM <noreply@agentxm.ai>"]
version = "0.1.0"

[deps]
AgentXMExampleTinyFlags = "9019d187-aeb1-4daa-a321-8e2340601955"

[compat]
AgentXMExampleTinyFlags = "0.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
