/**
 * Generate the telemetry Effect HTTP client from the committed OpenAPI spec.
 *
 * Usage:
 *   pnpm exec nx run cli:generate:telemetry-client
 */

// @effect-diagnostics nodeBuiltinImport:off globalConsole:off — generator process adapter owns synchronous descriptors and entry-point diagnostics
import * as NodeServices from "@effect/platform-node/NodeServices";
import * as Data from "effect/Data";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import { format, resolveConfig } from "prettier";
import * as childProcess from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

const CORE_ROOT = path.join(import.meta.dirname, "..");
const SPEC_PATH = path.join(CORE_ROOT, "specs/telemetry-openapi.json");
const OUTPUT_DIR = path.join(CORE_ROOT, "src/telemetry/__generated__");
const OUTPUT_PATH = path.join(OUTPUT_DIR, "telemetry-client.ts");
const CLIENT_NAME = "TelemetryClient";

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

class ClientGenerationFailed extends Data.TaggedError("ClientGenerationFailed")<{
  readonly detail: string;
  readonly cause?: unknown;
}> {}

// Regular files avoid captured-pipe dependencies and keep all subprocess output scoped.
const result = {
  stdout: await Effect.runPromise(
    Effect.scoped(
      Effect.gen(function* () {
        const files = yield* FileSystem.FileSystem;
        const paths = yield* Path.Path;
        const temporary = yield* files.makeTempDirectoryScoped({ prefix: "axm-openapi-client-" });
        const stdoutPath = paths.join(temporary, "stdout");
        const stderrPath = paths.join(temporary, "stderr");
        const stdout = yield* Effect.acquireRelease(
          Effect.try({
            try: () => fs.openSync(stdoutPath, "wx", 0o600),
            catch: (cause) =>
              new ClientGenerationFailed({ detail: "Could not open generator output", cause }),
          }),
          (fd) =>
            Effect.try({
              try: () => fs.closeSync(fd),
              catch: (cause) =>
                new ClientGenerationFailed({ detail: "Could not close generator output", cause }),
            }).pipe(Effect.ignore),
        );
        const stderr = yield* Effect.acquireRelease(
          Effect.try({
            try: () => fs.openSync(stderrPath, "wx", 0o600),
            catch: (cause) =>
              new ClientGenerationFailed({ detail: "Could not open generator errors", cause }),
          }),
          (fd) =>
            Effect.try({
              try: () => fs.closeSync(fd),
              catch: (cause) =>
                new ClientGenerationFailed({ detail: "Could not close generator errors", cause }),
            }).pipe(Effect.ignore),
        );
        const child = yield* Effect.try({
          try: () =>
            childProcess.spawnSync(
              "pnpm",
              ["exec", "openapigen", "--spec", SPEC_PATH, "--name", CLIENT_NAME],
              {
                cwd: CORE_ROOT,
                stdio: ["ignore", stdout, stderr],
                timeout: 30_000,
              },
            ),
          catch: (cause) =>
            new ClientGenerationFailed({ detail: "Could not run OpenAPI generator", cause }),
        });
        const errorBytes = Number((yield* files.stat(stderrPath)).size);
        if (errorBytes > 16 * 1024 * 1024)
          return yield* new ClientGenerationFailed({
            detail: "Generator errors exceed sixteen mebibytes",
          });
        if (child.error !== undefined || child.status !== 0)
          return yield* new ClientGenerationFailed({
            detail: "OpenAPI generator failed",
            cause: child.error ?? (yield* files.readFileString(stderrPath)),
          });
        const size = Number((yield* files.stat(stdoutPath)).size);
        if (size === 0 || size > 16 * 1024 * 1024)
          return yield* new ClientGenerationFailed({
            detail: "Generator output is empty or exceeds sixteen mebibytes",
          });
        return yield* files.readFileString(stdoutPath);
      }),
    ).pipe(Effect.provide(NodeServices.layer)),
  ),
};

const header = `/**
 * @generated by cli:generate:telemetry-client (openapigen)
 * Source:     apps/cli/specs/telemetry-openapi.json
 * Regenerate: pnpm exec nx run cli:generate:telemetry-client
 * DO NOT EDIT - changes are overwritten on regeneration.
 */
// @effect-diagnostics anyUnknownInErrorContext:off — generated OpenAPI transport errors are translated by the telemetry adapter
/* eslint-disable */

`;

const source = header + result.stdout;

const formatted = await Effect.runPromise(
  Effect.tryPromise({
    try: async () =>
      format(source, { ...(await resolveConfig(OUTPUT_PATH)), filepath: OUTPUT_PATH }),
    catch: (cause) =>
      new ClientGenerationFailed({ detail: "Could not format generated client", cause }),
  }),
);
fs.writeFileSync(OUTPUT_PATH, formatted);

console.log(`Generated: ${path.relative(CORE_ROOT, OUTPUT_PATH)}`);
