/**
 * Agent capability catalog.
 *
 * @experimental This API is unstable and may change without notice.
 */

import type { ConfigurableAgentId, HostedAgentId } from "./identity.js";
import type { Agent } from "./schema.js";
import {
  adalAgent,
  aiderDeskAgent,
  ampAgent,
  antigravityCliAgent,
  antigravityAgent,
  augmentAgent,
  chatgptAgent,
  claudeAiAgent,
  claudeCodeAgent,
  clineAgent,
  codeartsAgentAgent,
  codebuddyAgent,
  codemakerAgent,
  codestudioAgent,
  codexAgent,
  commandCodeAgent,
  continueAgent,
  cortexAgent,
  coworkAgent,
  crushAgent,
  cursorAgent,
  deepagentsAgent,
  devinAgent,
  dextoAgent,
  droidAgent,
  firebenderAgent,
  forgecodeAgent,
  geminiCliAgent,
  geminiAppAgent,
  githubCopilotCliAgent,
  gooseAgent,
  grokCliAgent,
  hermesAgent,
  ibmBobAgent,
  iflowCliAgent,
  junieAgent,
  lingmaAgent,
  kiloAgent,
  kimiCliAgent,
  kiroCliAgent,
  kodeAgent,
  mcpjamAgent,
  minimaxCodeAgent,
  mistralVibeAgent,
  muxAgent,
  neovateAgent,
  openclawAgent,
  opencodeAgent,
  openhandsAgent,
  onaAgent,
  piAgent,
  pochiAgent,
  qoderAgent,
  qoderCnAgent,
  qwenCodeAgent,
  replitAgent,
  rooAgent,
  rovodevAgent,
  tabnineCliAgent,
  traeCnAgent,
  traeAgent,
  warpAgent,
  windsurfAgent,
  zencoderAgent,
  zedAgent,
  zenflowAgent,
} from "./data/agents/index.js";

const defineCatalog = <const T extends Record<string, Agent>>(
  entries: T & { readonly [K in keyof T]: { readonly id: K } },
): T => entries;

/** @experimental This API is unstable and may change without notice. */
export const CONFIGURABLE_AGENTS_BY_ID = defineCatalog({
  adal: adalAgent,
  "aider-desk": aiderDeskAgent,
  amp: ampAgent,
  antigravity: antigravityAgent,
  "antigravity-cli": antigravityCliAgent,
  augment: augmentAgent,
  "claude-code": claudeCodeAgent,
  cline: clineAgent,
  "codearts-agent": codeartsAgentAgent,
  codebuddy: codebuddyAgent,
  codemaker: codemakerAgent,
  codestudio: codestudioAgent,
  codex: codexAgent,
  "command-code": commandCodeAgent,
  continue: continueAgent,
  cortex: cortexAgent,
  crush: crushAgent,
  cursor: cursorAgent,
  deepagents: deepagentsAgent,
  devin: devinAgent,
  dexto: dextoAgent,
  droid: droidAgent,
  firebender: firebenderAgent,
  forgecode: forgecodeAgent,
  "gemini-cli": geminiCliAgent,
  "github-copilot-cli": githubCopilotCliAgent,
  goose: gooseAgent,
  "grok-cli": grokCliAgent,
  hermes: hermesAgent,
  "ibm-bob": ibmBobAgent,
  "iflow-cli": iflowCliAgent,
  junie: junieAgent,
  lingma: lingmaAgent,
  kilo: kiloAgent,
  "kimi-cli": kimiCliAgent,
  "kiro-cli": kiroCliAgent,
  kode: kodeAgent,
  mcpjam: mcpjamAgent,
  "minimax-code": minimaxCodeAgent,
  "mistral-vibe": mistralVibeAgent,
  mux: muxAgent,
  neovate: neovateAgent,
  openclaw: openclawAgent,
  opencode: opencodeAgent,
  openhands: openhandsAgent,
  ona: onaAgent,
  pi: piAgent,
  pochi: pochiAgent,
  qoder: qoderAgent,
  "qoder-cn": qoderCnAgent,
  "qwen-code": qwenCodeAgent,
  replit: replitAgent,
  roo: rooAgent,
  rovodev: rovodevAgent,
  "tabnine-cli": tabnineCliAgent,
  "trae-cn": traeCnAgent,
  trae: traeAgent,
  warp: warpAgent,
  windsurf: windsurfAgent,
  zencoder: zencoderAgent,
  zed: zedAgent,
  zenflow: zenflowAgent,
} satisfies Record<ConfigurableAgentId, Agent>);

/** @experimental This API is unstable and may change without notice. */
export const HOSTED_AGENTS_BY_ID = defineCatalog({
  chatgpt: chatgptAgent,
  "claude-ai": claudeAiAgent,
  cowork: coworkAgent,
  "gemini-app": geminiAppAgent,
} satisfies Record<HostedAgentId, Agent>);

/** @experimental This API is unstable and may change without notice. */
export const AGENTS_BY_ID = defineCatalog({
  ...CONFIGURABLE_AGENTS_BY_ID,
  ...HOSTED_AGENTS_BY_ID,
});

/** @experimental This API is unstable and may change without notice. */
export const AGENTS = Object.values(AGENTS_BY_ID);
