/**
 * Generated by packages/cli/scripts/generate-help-topics.ts.
 * Do not edit by hand.
 */

export const HELP_TOPIC_NAMES = [
  "basic-usage",
  "exit-codes",
  "getting-started",
  "workspace",
] as const;

export type HelpTopicName = (typeof HELP_TOPIC_NAMES)[number];

export const HELP_TOPICS: Record<HelpTopicName, string> = {
  "basic-usage":
    "# Basic usage\n\nUse this when you are in an existing axm workspace and need to understand what\nis safe to inspect, what changes workspace state, and where to look next.\n\n## Start read-only\n\nBegin with a read-only workspace check:\n\n```bash\naxm lint\n```\n\nTreat its findings as the workspace map. It tells you what axm manages, what is\nmissing, what is stale, and what may need reconciliation.\n\n## Build context before changing state\n\nBefore installing, updating, pruning, or fixing anything:\n\n- Check the root command list with `axm --help`.\n- Read command-specific behavior with `axm <command> --help`.\n- Prefer preview or dry-run modes when a command offers them.\n- Prefer JSON output when another tool or agent needs to inspect results.\n\n## Common decision path\n\nIf the workspace looks healthy, use command-specific help to choose the next\noperation.\n\nIf configured extensions are missing, sync the workspace rather than adding new\nconfiguration first.\n\nIf managed files are stale or drifted, inspect the lint findings before applying\nfixes or pruning files.\n\nIf you need concepts rather than commands, read:\n\n```bash\naxm help workspace\n```\n\n## Safety notes\n\naxm owns managed files under its workspace configuration. Avoid hand-editing\ngenerated or managed agent files until you understand whether axm will rewrite\nthem.\n\nDo not commit workspace changes just because a command completed. Review the\ndiff and confirm the changed files match the intended operation.\n",
  "exit-codes":
    "# Exit codes\n\naxm uses stable process exit codes so scripts can distinguish success, usage\nerrors, runtime errors, and signal termination.\n\n| Code | Meaning                                                 |\n| ---- | ------------------------------------------------------- |\n| 0    | Success, including help output and cancelled prompts.   |\n| 1    | Runtime or domain error reported as an AppError.        |\n| 2    | CLI usage or validation error, such as an unknown flag. |\n| 130  | Signal termination, such as SIGINT or SIGTERM.          |\n\nIn JSON output mode, AppError failures use a stable error code shaped like\n`AREA_REASON`, plus a human-readable message and the same process exit code.\n",
  "getting-started":
    "# Getting started\n\naxm manages agent extensions for a workspace: skills, commands, MCP servers,\nsubagents, and packs.\n\n## Install\n\nInstall axm from the project release instructions, then confirm it is available:\n\n```bash\naxm --version\n```\n\n## Set up a workspace\n\nRun setup in the project you want axm to manage:\n\n```bash\naxm setup\n```\n\nSetup creates `.axm/`, detects supported coding agents, and writes workspace\nsettings.\n\n## Install an extension\n\nInstall from a registry reference:\n\n```bash\naxm install @acme/skills/code-review\n```\n\nUse `axm discover` to see extension suggestions for the current project.\n\n## Key concepts\n\n- A workspace is the project or user scope axm manages.\n- A registry is a source of published extensions.\n- A pack installs a curated set of extensions together.\n",
  workspace:
    "# Workspace\n\nAn axm workspace is the configuration and installed extension state that axm\nmanages for a project or user.\n\n## Layout\n\nProject workspaces store state in `.axm/`:\n\n- `settings.json` records agents, registry settings, and preferences.\n- `axm-lock.yaml` records resolved extension versions.\n- `extensions/` stores installed extension source files.\n\n## Common flows\n\nRun `axm setup` once to create workspace settings.\n\nRun `axm install` to sync configured extensions, or pass a registry reference to\nadd one extension.\n\nRun `axm lint` to inspect workspace drift. Use `axm lint --fix` to reconcile\nmanaged files non-interactively.\n\nRun `axm prune` to remove stale managed files that no longer match workspace\nconfiguration.\n\nUse `--scope user` on supported commands when you want user-level configuration\ninstead of project-level configuration.\n",
};
