<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateProgramFile>false</GenerateProgramFile>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PawMatchTests.fs" />
    <Compile Include="Program.fs" />
    <ProjectReference Include="../../src/AgentXM.Examples.PawMatch.FSharp/AgentXM.Examples.PawMatch.FSharp.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Expecto" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" />
  </ItemGroup>
</Project>
