// Generated by scripts/generate-error-catalog.ts. Do not edit by hand.

export const ErrorCodeCatalog = {
  AUTH_CREDENTIAL_STORE_FAILED: {
    code: "AUTH_CREDENTIAL_STORE_FAILED",
    category: "auth",
    message: "Credential file could not be read",
    breadcrumbs: [
      {
        task: "Recover",
        description:
          "The credential file may be corrupt. Delete it and re-authenticate with `axm login`.",
      },
    ],
    sources: [
      "packages/core/src/unstable/auth/credential-store.ts:136",
      "packages/core/src/unstable/auth/credential-store.ts:148",
      "packages/core/src/unstable/auth/credential-store.ts:181",
      "packages/core/src/unstable/auth/credential-store.ts:192",
    ],
  },
  AUTH_LOGIN_CANCELLED: {
    code: "AUTH_LOGIN_CANCELLED",
    category: "auth",
    message: "Login was denied or cancelled",
    breadcrumbs: [{ task: "Recover", description: "Run `axm login` to try again." }],
    sources: ["packages/core/src/unstable/auth/auth-client.ts:321"],
  },
  AUTH_LOGIN_FAILED: {
    code: "AUTH_LOGIN_FAILED",
    category: "auth",
    message: "Lost connection to the registry during login",
    breadcrumbs: [
      {
        task: "Recover",
        description: "Verify the registry is running and reachable, then try `axm login` again.",
      },
    ],
    sources: [
      "packages/core/src/unstable/auth/auth-client.ts:134",
      "packages/core/src/unstable/auth/auth-client.ts:213",
      "packages/core/src/unstable/auth/auth-client.ts:229",
      "packages/core/src/unstable/auth/auth-client.ts:278",
      "packages/core/src/unstable/auth/auth-client.ts:328",
      "packages/core/src/unstable/auth/auth-client.ts:479",
      "packages/core/src/unstable/auth/auth-client.ts:487",
    ],
  },
  AUTH_LOGIN_REQUIRED: {
    code: "AUTH_LOGIN_REQUIRED",
    category: "auth",
    message: "Authentication required",
    breadcrumbs: [
      {
        task: "Run `axm login`",
        description: "Run `axm login` to sign in, or set the AXM_TOKEN environment variable.",
      },
    ],
    sources: [
      "packages/core/src/unstable/auth/guard.ts:26",
      "packages/core/src/unstable/auth/token-resolution.ts:75",
    ],
  },
  AUTH_REFRESH_FAILED: {
    code: "AUTH_REFRESH_FAILED",
    category: "auth",
    message: "Token refresh request failed",
    breadcrumbs: [{ task: "Recover", description: "Run `axm login` to re-authenticate." }],
    sources: [
      "packages/core/src/unstable/auth/auth-client.ts:350",
      "packages/core/src/unstable/auth/auth-client.ts:495",
    ],
  },
  AUTH_SERVER_ERROR: {
    code: "AUTH_SERVER_ERROR",
    category: "network",
    message: "Registry returned server error",
    breadcrumbs: [
      {
        task: "Recover",
        description: "The registry may be temporarily unavailable. Try again later.",
      },
    ],
    sources: ["packages/core/src/unstable/auth/auth-client.ts:422"],
  },
  AUTH_TOKEN_REQUIRED: {
    code: "AUTH_TOKEN_REQUIRED",
    category: "auth",
    message: "No authentication token is available.",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/app-error/builders.ts:27"],
  },
  AUTH_UNAUTHENTICATED: {
    code: "AUTH_UNAUTHENTICATED",
    category: "auth",
    message: "Not authenticated or token is invalid",
    breadcrumbs: [{ task: "Recover", description: "Run `axm login` to re-authenticate." }],
    sources: [
      "packages/core/src/unstable/auth/auth-client.ts:397",
      "packages/core/src/unstable/auth/auth-client.ts:408",
      "packages/core/src/unstable/auth/auth-client.ts:435",
      "packages/core/src/unstable/auth/auth-client.ts:504",
      "packages/core/src/unstable/registry/error-mapping.ts:212",
    ],
  },
  AUTH_UNAUTHORIZED: {
    code: "AUTH_UNAUTHORIZED",
    category: "forbidden",
    message: "Insufficient permissions",
    breadcrumbs: [
      {
        task: "Check permissions",
        description:
          "You do not have permission for this operation. Check your account permissions.",
      },
    ],
    sources: ["packages/core/src/unstable/registry/error-mapping.ts:258"],
  },
  COMMAND_CREATE_FAILED: {
    code: "COMMAND_CREATE_FAILED",
    category: "validation",
    message: "Command manifest could not be written",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/commands/operations/new-command.ts:158"],
  },
  COMMAND_FETCH_FAILED: {
    code: "COMMAND_FETCH_FAILED",
    category: "network",
    message: "Command could not be fetched from registry",
    breadcrumbs: [
      { task: "Recover", description: "Verify the command name and registry configuration." },
    ],
    sources: ["packages/cli/src/root/commands/install/command-actions.ts:296"],
  },
  COMMAND_FRONTMATTER_INVALID: {
    code: "COMMAND_FRONTMATTER_INVALID",
    category: "validation",
    message: "Command frontmatter must be a YAML mapping",
    breadcrumbs: [
      {
        task: "Recover",
        description: "Use key-value YAML frontmatter in your command content file.",
      },
    ],
    sources: ["packages/core/src/unstable/commands/command-content.ts:68"],
  },
  COMMAND_SOURCE_INVALID_FORMAT: {
    code: "COMMAND_SOURCE_INVALID_FORMAT",
    category: "validation",
    message: "Command source must include /commands/ segment",
    breadcrumbs: [{ task: "Recover", description: "Use @owner/commands/command-name format." }],
    sources: ["packages/cli/src/root/commands/install/command-actions.ts:199"],
  },
  COMMAND_SOURCE_MISSING_NAME: {
    code: "COMMAND_SOURCE_MISSING_NAME",
    category: "not_found",
    message: "Command source must include a command name",
    breadcrumbs: [{ task: "Recover", description: "Use @owner/commands/command-name format." }],
    sources: ["packages/cli/src/root/commands/install/command-actions.ts:208"],
  },
  COMMAND_SOURCE_NOT_REGISTRY: {
    code: "COMMAND_SOURCE_NOT_REGISTRY",
    category: "usage",
    message: "Commands can only be installed from a registry",
    breadcrumbs: [
      { task: "Recover", description: "Use @owner/commands/command-name or just command-name." },
    ],
    sources: [
      "packages/cli/src/root/commands/install/command-actions.ts:217",
      "packages/cli/src/root/commands/install/command-actions.ts:255",
    ],
  },
  CONFIGURED_ENTRY_RESOLUTION_TIMEOUT: {
    code: "CONFIGURED_ENTRY_RESOLUTION_TIMEOUT",
    category: "network",
    message: "Timed out while resolving a configured extension source",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/workspace/configured-entry-resolution/timeout.ts:14"],
  },
  DISCOVER_FAILED: {
    code: "DISCOVER_FAILED",
    category: "usage",
    message: "No source request to discover from",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/cli/src/root/skills/install/command-actions.ts:355",
      "packages/cli/src/root/skills/install/command-actions.ts:377",
      "packages/cli/src/root/subagents/install/command-actions.ts:294",
      "packages/cli/src/root/subagents/install/command-actions.ts:316",
    ],
  },
  FRONTMATTER_PARSE_ERROR: {
    code: "FRONTMATTER_PARSE_ERROR",
    category: "validation",
    message: "YAML frontmatter could not be parsed",
    breadcrumbs: [
      {
        task: "Recover",
        description: "Ensure the frontmatter block contains valid YAML between --- delimiters.",
      },
    ],
    sources: ["packages/core/src/unstable/extensions/frontmatter.ts:92"],
  },
  INSTALL_COMMAND_COPY_FAILED: {
    code: "INSTALL_COMMAND_COPY_FAILED",
    category: "validation",
    message: "Extracted directory could not be read",
    breadcrumbs: [{ task: "Recover", description: "Check the extension package and try again." }],
    sources: [
      "packages/core/src/unstable/commands/manager.ts:272",
      "packages/core/src/unstable/commands/operations/install.ts:155",
    ],
  },
  INSTALL_COMMAND_TEMP_DIR_FAILED: {
    code: "INSTALL_COMMAND_TEMP_DIR_FAILED",
    category: "validation",
    message: "Temporary directory for registry install could not be created",
    breadcrumbs: [{ task: "Recover", description: "Check the extension package and try again." }],
    sources: [
      "packages/core/src/unstable/commands/manager.ts:248",
      "packages/core/src/unstable/commands/operations/install.ts:131",
    ],
  },
  INSTALL_MCP_SERVER_COPY_FAILED: {
    code: "INSTALL_MCP_SERVER_COPY_FAILED",
    category: "validation",
    message: "Extracted directory could not be read",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/core/src/unstable/mcp-servers/manager.ts:189",
      "packages/core/src/unstable/mcp-servers/operations/install.ts:164",
    ],
  },
  INSTALL_MCP_SERVER_TEMP_DIR_FAILED: {
    code: "INSTALL_MCP_SERVER_TEMP_DIR_FAILED",
    category: "validation",
    message: "Temporary directory for registry install could not be created",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/core/src/unstable/mcp-servers/manager.ts:165",
      "packages/core/src/unstable/mcp-servers/operations/install.ts:138",
    ],
  },
  INSTALL_SKILL_COPY_FAILED: {
    code: "INSTALL_SKILL_COPY_FAILED",
    category: "validation",
    message: "Skill files could not be copied to the canonical location",
    breadcrumbs: [{ task: "Recover", description: "Check the extension package and try again." }],
    sources: ["packages/core/src/unstable/skills/operations/install.ts:102"],
  },
  INSTALL_SKILL_TEMP_DIR_FAILED: {
    code: "INSTALL_SKILL_TEMP_DIR_FAILED",
    category: "validation",
    message: "Temporary directory for registry install could not be created",
    breadcrumbs: [{ task: "Recover", description: "Check the extension package and try again." }],
    sources: [
      "packages/core/src/unstable/skills/materialization.ts:166",
      "packages/core/src/unstable/skills/operations/install.ts:247",
    ],
  },
  INSTALL_SOURCE_INVALID_FQN: {
    code: "INSTALL_SOURCE_INVALID_FQN",
    category: "validation",
    message: "Install source must be a registry FQN",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/install/resolve-root-install-intent.ts:86"],
  },
  INSTALL_SOURCE_NOT_FQN: {
    code: "INSTALL_SOURCE_NOT_FQN",
    category: "usage",
    message: "Root install only accepts registry FQNs",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/install/resolve-root-install-intent.ts:61"],
  },
  INSTALL_SOURCE_UNKNOWN_TYPE: {
    code: "INSTALL_SOURCE_UNKNOWN_TYPE",
    category: "not_found",
    message: "Install source uses an unsupported plural type",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/install/resolve-root-install-intent.ts:72"],
  },
  INSTALL_SOURCE_UNSUPPORTED_TYPE: {
    code: "INSTALL_SOURCE_UNSUPPORTED_TYPE",
    category: "usage",
    message: "Root install does not support that extension type",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/install/resolve-root-install-intent.ts:102"],
  },
  INSTALL_SUBAGENT_TEMP_DIR_FAILED: {
    code: "INSTALL_SUBAGENT_TEMP_DIR_FAILED",
    category: "validation",
    message: "Temporary directory for registry install could not be created",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/subagents/manager.ts:185"],
  },
  INVALID_SOURCE: {
    code: "INVALID_SOURCE",
    category: "validation",
    message: "Invalid source: Unable to parse source",
    breadcrumbs: [
      {
        task: "Recover",
        description:
          "Valid formats: local path, github:owner/repo, gitlab:owner/repo, or https://example.com",
      },
    ],
    sources: [
      "packages/cli/src/root/skills/install/command-actions.ts:277",
      "packages/cli/src/root/subagents/install/command-actions.ts:211",
    ],
  },
  LINT_SETTINGS_PARSE_FAILED: {
    code: "LINT_SETTINGS_PARSE_FAILED",
    category: "validation",
    message: "",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/lint/handler.ts:197"],
  },
  LOCKFILE_BACKUP_FAILED: {
    code: "LOCKFILE_BACKUP_FAILED",
    category: "internal",
    message: "Failed to create temporary directory for invalid lockfile backup",
    sources: ["packages/core/src/unstable/workspace/reconciliation.ts:238"],
  },
  LOCKFILE_RECONCILE_SOURCE_UNREACHABLE: {
    code: "LOCKFILE_RECONCILE_SOURCE_UNREACHABLE",
    category: "network",
    message: "Required declaration sources are unreachable during reconciliation",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/workspace/reconciliation.ts:299"],
  },
  LOCKFILE_RESOLVED_VERSION_INVALID: {
    code: "LOCKFILE_RESOLVED_VERSION_INVALID",
    category: "validation",
    message: "Lockfile resolved versions must be exact semver values",
    breadcrumbs: [
      {
        task: "Recover",
        description:
          "Resolve the constraint first, then persist the exact resolved version (for example, 1.2.3 instead of ^1.2.3).",
      },
    ],
    sources: ["packages/core/src/unstable/lockfile/resolved-version.ts:10"],
  },
  LOCKFILE_WRITE_FAILED: {
    code: "LOCKFILE_WRITE_FAILED",
    category: "internal",
    message: "Failed to encode lockfile",
    sources: [
      "packages/core/src/unstable/lockfile/lockfile.ts:77",
      "packages/core/src/unstable/lockfile/lockfile.ts:89",
    ],
  },
  MCP_SERVER_FETCH_FAILED: {
    code: "MCP_SERVER_FETCH_FAILED",
    category: "network",
    message: "MCP server could not be fetched from registry",
    breadcrumbs: [
      { task: "Recover", description: "Verify the server name and registry configuration." },
    ],
    sources: ["packages/cli/src/root/mcp-servers/install/command-actions.ts:262"],
  },
  MCP_SERVER_SOURCE_INVALID_FORMAT: {
    code: "MCP_SERVER_SOURCE_INVALID_FORMAT",
    category: "validation",
    message: "MCP server source must include /mcp-servers/ segment",
    breadcrumbs: [{ task: "Recover", description: "Use @owner/mcp-servers/server-name format." }],
    sources: ["packages/cli/src/root/mcp-servers/install/command-actions.ts:166"],
  },
  MCP_SERVER_SOURCE_MISSING_NAME: {
    code: "MCP_SERVER_SOURCE_MISSING_NAME",
    category: "not_found",
    message: "MCP server source must include a server name",
    breadcrumbs: [{ task: "Recover", description: "Use @owner/mcp-servers/server-name format." }],
    sources: ["packages/cli/src/root/mcp-servers/install/command-actions.ts:175"],
  },
  MCP_SERVER_SOURCE_NOT_REGISTRY: {
    code: "MCP_SERVER_SOURCE_NOT_REGISTRY",
    category: "usage",
    message: "MCP servers can only be installed from a registry",
    breadcrumbs: [
      { task: "Recover", description: "Use @owner/mcp-servers/server-name or just server-name." },
    ],
    sources: [
      "packages/cli/src/root/mcp-servers/install/command-actions.ts:184",
      "packages/cli/src/root/mcp-servers/install/command-actions.ts:221",
    ],
  },
  NO_REGISTRY_CONFIGURED: {
    code: "NO_REGISTRY_CONFIGURED",
    category: "usage",
    message: "No registry sources configured",
    breadcrumbs: [{ task: "Recover", description: "Run the registry guard first." }],
    sources: [
      "packages/cli/src/root/commands/publish.ts:101",
      "packages/cli/src/root/packs/publish.ts:90",
      "packages/cli/src/root/skills/publish.ts:97",
      "packages/cli/src/root/subagents/publish/handler.ts:90",
      "packages/cli/src/root/view/handler.ts:85",
    ],
  },
  NO_SKILLS_FOUND: {
    code: "NO_SKILLS_FOUND",
    category: "not_found",
    message: "No skills found in source",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/cli/src/root/skills/install/command-actions.ts:391",
      "packages/cli/src/root/skills/install/command-actions.ts:419",
    ],
  },
  NO_SKILLS_MATCHED: {
    code: "NO_SKILLS_MATCHED",
    category: "not_found",
    message: "No skills matched the given pattern",
    breadcrumbs: [
      { task: "Recover", description: "Check installed skill names with `axm skills list`." },
    ],
    sources: ["packages/core/src/unstable/source-resolution/resolve-source-pattern.ts:149"],
  },
  NO_SUBAGENTS_FOUND: {
    code: "NO_SUBAGENTS_FOUND",
    category: "not_found",
    message: "No subagents found in source",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/cli/src/root/subagents/install/command-actions.ts:330",
      "packages/cli/src/root/subagents/install/command-actions.ts:361",
    ],
  },
  PACK_DEPENDENCY_RESOLUTION_FAILED: {
    code: "PACK_DEPENDENCY_RESOLUTION_FAILED",
    category: "usage",
    message: "Cannot resolve extension pack dependencies from non-registry source",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/packs/dependency-resolution.ts:59"],
  },
  PACK_FETCH_FAILED: {
    code: "PACK_FETCH_FAILED",
    category: "network",
    message: "Pack could not be fetched from registry",
    breadcrumbs: [
      {
        task: "Recover",
        description:
          "Remote registry discovery is not yet supported. Configure a file:// registry source or use a local registry source name.",
      },
    ],
    sources: [
      "packages/cli/src/root/packs/install/command-actions.ts:565",
      "packages/cli/src/root/packs/install/command-actions.ts:579",
      "packages/cli/src/root/packs/install/command-actions.ts:642",
    ],
  },
  PACK_MANIFEST_STALE: {
    code: "PACK_MANIFEST_STALE",
    category: "conflict",
    message: "Extension pack manifest is stale — it was modified since the plan was created",
    breadcrumbs: [{ task: "Recover", description: "Re-run the command to create a fresh plan" }],
    sources: [
      "packages/core/src/unstable/packs/operations/add-to-pack.ts:103",
      "packages/core/src/unstable/packs/operations/remove-from-pack.ts:105",
    ],
  },
  PACK_NO_SOURCE_REQUEST: {
    code: "PACK_NO_SOURCE_REQUEST",
    category: "usage",
    message: "No source request provided",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/packs/install/command-actions.ts:477"],
  },
  PACK_NOT_FOUND: {
    code: "PACK_NOT_FOUND",
    category: "not_found",
    message: "No extension pack reference found",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/packs/install/command-actions.ts:634"],
  },
  PACK_SOURCE_INVALID_FORMAT: {
    code: "PACK_SOURCE_INVALID_FORMAT",
    category: "validation",
    message: "Extension pack source must include /packs/ segment",
    breadcrumbs: [
      {
        task: "Recover",
        description:
          "Use @owner/packs/pack-name format. The /packs/ segment distinguishes packs from skills.",
      },
    ],
    sources: ["packages/cli/src/root/packs/install/command-actions.ts:385"],
  },
  PACK_SOURCE_MISSING_NAME: {
    code: "PACK_SOURCE_MISSING_NAME",
    category: "not_found",
    message: "Extension pack source must include a pack name",
    breadcrumbs: [{ task: "Recover", description: "Use @owner/packs/pack-name format." }],
    sources: ["packages/cli/src/root/packs/install/command-actions.ts:398"],
  },
  PACK_SOURCE_NOT_REGISTRY: {
    code: "PACK_SOURCE_NOT_REGISTRY",
    category: "usage",
    message: "Packs can only be installed from a registry",
    breadcrumbs: [
      {
        task: "Recover",
        description: "Use @owner/packs/pack-name or just pack-name (resolved to default owner).",
      },
    ],
    sources: [
      "packages/cli/src/root/packs/install/command-actions.ts:407",
      "packages/cli/src/root/packs/install/command-actions.ts:449",
    ],
  },
  PLAN_BLOCKED_BY_ERRORS: {
    code: "PLAN_BLOCKED_BY_ERRORS",
    category: "conflict",
    message: "Plan has errors that prevent execution",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/plan/resolve-plan.ts:146"],
  },
  PLAN_STEP_BLOCKED: {
    code: "PLAN_STEP_BLOCKED",
    category: "conflict",
    message: "blocked by earlier job failure",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/plan/apply-plan.ts:89"],
  },
  PROMPT_REQUIRED: {
    code: "PROMPT_REQUIRED",
    category: "usage",
    message: "Interactive prompt required: Apply changes?",
    breadcrumbs: [
      { task: "Recover", description: "Provide ResolvePlanInteraction in the runtime." },
    ],
    sources: [
      "packages/core/src/unstable/plan/resolve-plan.ts:42",
      "packages/core/src/unstable/workspace/initialization.ts:36",
    ],
  },
  PROMPT_VALUE_INVALID: {
    code: "PROMPT_VALUE_INVALID",
    category: "validation",
    message: "Pet name must be at least 1 character",
    breadcrumbs: [
      {
        task: "Recover",
        description: "Pass a non-empty `--value` or provide a non-empty prompt response.",
      },
    ],
    sources: ["packages/cli-spike/src/root/prompts/text.ts:57"],
  },
  PUBLISH_REGISTRY_FAILED: {
    code: "PUBLISH_REGISTRY_FAILED",
    category: "network",
    message: "Registry publish did not complete",
    reason: "registry_publish",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/core/src/unstable/commands/operations/publish.ts:195",
      "packages/core/src/unstable/mcp-servers/operations/publish.ts:190",
      "packages/core/src/unstable/packs/operations/publish.ts:198",
    ],
  },
  REGISTRY_PUBLISH_CONFLICT: {
    code: "REGISTRY_PUBLISH_CONFLICT",
    category: "conflict",
    message: "Version already exists with different content.",
    breadcrumbs: [{ task: "Recover", description: "Bump the version in your manifest." }],
    sources: [
      "packages/core/src/unstable/registry/local-client.ts:440",
      "packages/core/src/unstable/registry/remote-client.ts:814",
    ],
  },
  REGISTRY_PUBLISH_NETWORK_ERROR: {
    code: "REGISTRY_PUBLISH_NETWORK_ERROR",
    category: "network",
    message: "Remote registry is unreachable",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/registry/remote-client.ts:782"],
  },
  REGISTRY_PUBLISH_REJECTED: {
    code: "REGISTRY_PUBLISH_REJECTED",
    category: "validation",
    message: "Registry publish request was rejected",
    breadcrumbs: [{ task: "Recover", description: "Check the extension package and try again." }],
    sources: [
      "packages/core/src/unstable/registry/local-client.ts:399",
      "packages/core/src/unstable/registry/local-client.ts:417",
      "packages/core/src/unstable/registry/local-client.ts:426",
      "packages/core/src/unstable/registry/local-client.ts:450",
      "packages/core/src/unstable/registry/local-client.ts:467",
      "packages/core/src/unstable/registry/local-client.ts:479",
      "packages/core/src/unstable/registry/remote-client.ts:801",
      "packages/core/src/unstable/registry/remote-client.ts:824",
      "packages/core/src/unstable/registry/remote-client.ts:833",
      "packages/core/src/unstable/registry/remote-client.ts:842",
      "packages/core/src/unstable/registry/remote-client.ts:854",
      "packages/core/src/unstable/registry/remote-client.ts:866",
      "packages/core/src/unstable/registry/remote-client.ts:874",
      "packages/core/src/unstable/registry/remote-client.ts:881",
      "packages/core/src/unstable/registry/remote-client.ts:895",
      "packages/core/src/unstable/registry/remote-client.ts:906",
      "packages/core/src/unstable/registry/remote-client.ts:919",
      "packages/core/src/unstable/registry/remote-client.ts:928",
      "packages/core/src/unstable/registry/remote-client.ts:935",
    ],
  },
  REGISTRY_REMOTE_DISCOVERY_INVALID_RESPONSE: {
    code: "REGISTRY_REMOTE_DISCOVERY_INVALID_RESPONSE",
    category: "validation",
    message: "Remote discovery response does not match expected schema",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/core/src/unstable/registry/remote-client.ts:198",
      "packages/core/src/unstable/registry/remote-client.ts:474",
    ],
  },
  REGISTRY_REMOTE_EXTENSION_CHECK_FAILED: {
    code: "REGISTRY_REMOTE_EXTENSION_CHECK_FAILED",
    category: "network",
    message: "Remote extension check failed",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/registry/remote-client.ts:726"],
  },
  REGISTRY_REMOTE_NAMESPACE_CHECK_FAILED: {
    code: "REGISTRY_REMOTE_NAMESPACE_CHECK_FAILED",
    category: "network",
    message: "Remote owner check failed",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/registry/remote-client.ts:550"],
  },
  REGISTRY_REMOTE_PACKAGE_FETCH_FAILED: {
    code: "REGISTRY_REMOTE_PACKAGE_FETCH_FAILED",
    category: "network",
    message: "Remote package index request failed",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/core/src/unstable/registry/remote-client.ts:636",
      "packages/core/src/unstable/registry/remote-client.ts:677",
    ],
  },
  REGISTRY_REMOTE_PACKAGE_NOT_FOUND: {
    code: "REGISTRY_REMOTE_PACKAGE_NOT_FOUND",
    category: "not_found",
    message: "Remote package index was not found",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/core/src/unstable/registry/remote-client.ts:608",
      "packages/core/src/unstable/registry/remote-client.ts:649",
    ],
  },
  REGISTRY_REMOTE_VERSION_NOT_FOUND: {
    code: "REGISTRY_REMOTE_VERSION_NOT_FOUND",
    category: "not_found",
    message: "Requested package version is not available in remote index",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/registry/remote-client.ts:582"],
  },
  SETTINGS_IGNORED_PATTERN_INVALID: {
    code: "SETTINGS_IGNORED_PATTERN_INVALID",
    category: "validation",
    message: "Ignored pattern is empty after trimming whitespace",
    breadcrumbs: [{ task: "Recover", description: "Remove empty ignored patterns from settings" }],
    sources: ["packages/core/src/unstable/settings/ignored-patterns.ts:23"],
  },
  SETTINGS_PARSE_FAILED: {
    code: "SETTINGS_PARSE_FAILED",
    category: "validation",
    message: "Workspace settings could not be read",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/core/src/unstable/plan/resolve-plan.ts:109",
      "packages/core/src/unstable/workspace/initialization.ts:78",
    ],
  },
  SKILL_CREATE_FAILED: {
    code: "SKILL_CREATE_FAILED",
    category: "validation",
    message: "Skill manifest could not be written",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/core/src/unstable/skills/operations/new-skill.ts:147",
      "packages/core/src/unstable/skills/operations/new-skill.ts:159",
    ],
  },
  SKILL_DIR_MISCONFIGURED: {
    code: "SKILL_DIR_MISCONFIGURED",
    category: "validation",
    message: "One or more configured agents have invalid skills directory settings",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/core/src/unstable/skills/manager.ts:117"],
  },
  SKILLS_INSTALL_ALL_REQUIRES_SOURCE: {
    code: "SKILLS_INSTALL_ALL_REQUIRES_SOURCE",
    category: "usage",
    message: "The --all flag requires a source for skills install",
    breadcrumbs: [
      {
        task: "Recover",
        description:
          "Run `axm skills install <source> --all` or omit --all to install all configured skills.",
      },
    ],
    sources: ["packages/cli/src/root/skills/install/handler.ts:25"],
  },
  SKILLS_INSTALL_SELECTOR_REQUIRES_SOURCE: {
    code: "SKILLS_INSTALL_SELECTOR_REQUIRES_SOURCE",
    category: "usage",
    message: "The --skill flag requires a source for skills install",
    breadcrumbs: [
      {
        task: "Recover",
        description:
          "Run `axm skills install <source> --skill <name>` or omit --skill to install all configured skills.",
      },
    ],
    sources: ["packages/cli/src/root/skills/install/handler.ts:40"],
  },
  SOURCE_FETCH_FAILED: {
    code: "SOURCE_FETCH_FAILED",
    category: "network",
    message: "Temporary source directory could not be created",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/core/src/unstable/registry/utils.ts:95",
      "packages/core/src/unstable/source-resolution/providers/git-hosting.ts:70",
      "packages/core/src/unstable/source-resolution/providers/git-hosting.ts:91",
      "packages/core/src/unstable/source-resolution/providers/git.ts:33",
      "packages/core/src/unstable/source-resolution/providers/git.ts:42",
      "packages/core/src/unstable/source-resolution/providers/local.ts:45",
      "packages/core/src/unstable/source-resolution/providers/local.ts:75",
      "packages/core/src/unstable/source-resolution/providers/registry/host-provider.ts:314",
      "packages/core/src/unstable/source-resolution/providers/registry/host-provider.ts:347",
    ],
  },
  SOURCE_PARSE_FAILED: {
    code: "SOURCE_PARSE_FAILED",
    category: "validation",
    message: "Invalid GitLab SSH URL format",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: [
      "packages/core/src/unstable/source-resolution/providers/azurerepos/repo-exists.ts:29",
      "packages/core/src/unstable/source-resolution/providers/azurerepos/scp.ts:21",
      "packages/core/src/unstable/source-resolution/providers/azurerepos/scp.ts:37",
      "packages/core/src/unstable/source-resolution/providers/azurerepos/url.ts:20",
      "packages/core/src/unstable/source-resolution/providers/azurerepos/url.ts:30",
      "packages/core/src/unstable/source-resolution/providers/azurerepos/url.ts:46",
      "packages/core/src/unstable/source-resolution/providers/bitbucket/scp.ts:17",
      "packages/core/src/unstable/source-resolution/providers/bitbucket/scp.ts:32",
      "packages/core/src/unstable/source-resolution/providers/bitbucket/url.ts:17",
      "packages/core/src/unstable/source-resolution/providers/bitbucket/url.ts:27",
      "packages/core/src/unstable/source-resolution/providers/bitbucket/url.ts:44",
      "packages/core/src/unstable/source-resolution/providers/github/scp.ts:17",
      "packages/core/src/unstable/source-resolution/providers/github/scp.ts:32",
      "packages/core/src/unstable/source-resolution/providers/github/url.ts:17",
      "packages/core/src/unstable/source-resolution/providers/github/url.ts:27",
      "packages/core/src/unstable/source-resolution/providers/github/url.ts:44",
      "packages/core/src/unstable/source-resolution/providers/gitlab/scp.ts:17",
      "packages/core/src/unstable/source-resolution/providers/gitlab/scp.ts:32",
      "packages/core/src/unstable/source-resolution/providers/gitlab/url.ts:17",
      "packages/core/src/unstable/source-resolution/providers/gitlab/url.ts:27",
      "packages/core/src/unstable/source-resolution/providers/gitlab/url.ts:44",
      "packages/core/src/unstable/source-resolution/providers/parse-provider-shorthand.ts:38",
      "packages/core/src/unstable/source-resolution/providers/parse-provider-shorthand.ts:53",
      "packages/core/src/unstable/source-resolution/resolve-source.ts:221",
      "packages/core/src/unstable/source-resolution/resolve-source.ts:575",
      "packages/core/src/unstable/source-resolution/resolve-source.ts:584",
      "packages/core/src/unstable/source-resolution/resolve-source.ts:612",
    ],
  },
  SPIKE_HANDLED_ERROR: {
    code: "SPIKE_HANDLED_ERROR",
    category: "internal",
    message: "Simulated handled telemetry failure",
    breadcrumbs: [
      {
        task: "Recover",
        description: "Run `axm-spike telemetry defect` to exercise defect telemetry.",
      },
    ],
    sources: ["packages/cli-spike/src/root/telemetry/handled.ts:11"],
  },
  SUBAGENT_CREATE_FAILED: {
    code: "SUBAGENT_CREATE_FAILED",
    category: "validation",
    message: "Subagent manifest could not be written",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/subagents/new/handler.ts:156"],
  },
  SUBAGENT_FRONTMATTER_INVALID: {
    code: "SUBAGENT_FRONTMATTER_INVALID",
    category: "validation",
    message: "Invalid subagent frontmatter",
    breadcrumbs: [
      { task: "Recover", description: "Frontmatter must include a string `name` field." },
    ],
    sources: [
      "packages/core/src/unstable/subagents/subagent-content.ts:108",
      "packages/core/src/unstable/subagents/subagent-content.ts:96",
    ],
  },
  SUBAGENTS_INSTALL_ALL_REQUIRES_SOURCE: {
    code: "SUBAGENTS_INSTALL_ALL_REQUIRES_SOURCE",
    category: "usage",
    message: "The --all flag requires a source for subagents install",
    breadcrumbs: [
      {
        task: "Recover",
        description:
          "Run `axm subagents install <source> --all` or omit --all to install all configured subagents.",
      },
    ],
    sources: ["packages/cli/src/root/subagents/install/handler.ts:25"],
  },
  SUBAGENTS_INSTALL_SELECTOR_REQUIRES_SOURCE: {
    code: "SUBAGENTS_INSTALL_SELECTOR_REQUIRES_SOURCE",
    category: "usage",
    message: "The --subagent flag requires a source for subagents install",
    breadcrumbs: [
      {
        task: "Recover",
        description:
          "Run `axm subagents install <source> --subagent <name>` or omit --subagent to install all configured subagents.",
      },
    ],
    sources: ["packages/cli/src/root/subagents/install/handler.ts:40"],
  },
  SYMLINK_CREATE_FAILED: {
    code: "SYMLINK_CREATE_FAILED",
    category: "internal",
    message: "Failed to resolve target path",
    sources: ["packages/core/src/unstable/utils/create-symlink.ts:34"],
  },
  UNINSTALL_SOURCE_INVALID_FQN: {
    code: "UNINSTALL_SOURCE_INVALID_FQN",
    category: "validation",
    message: "Uninstall source must be a registry FQN",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/uninstall/resolve-root-uninstall-intent.ts:86"],
  },
  UNINSTALL_SOURCE_NOT_FQN: {
    code: "UNINSTALL_SOURCE_NOT_FQN",
    category: "usage",
    message: "Root uninstall only accepts registry FQNs",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/uninstall/resolve-root-uninstall-intent.ts:61"],
  },
  UNINSTALL_SOURCE_UNKNOWN_TYPE: {
    code: "UNINSTALL_SOURCE_UNKNOWN_TYPE",
    category: "not_found",
    message: "Uninstall source uses an unsupported plural type",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/uninstall/resolve-root-uninstall-intent.ts:72"],
  },
  UNINSTALL_SOURCE_UNSUPPORTED_TYPE: {
    code: "UNINSTALL_SOURCE_UNSUPPORTED_TYPE",
    category: "usage",
    message: "Root uninstall does not support that extension type",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/uninstall/resolve-root-uninstall-intent.ts:102"],
  },
  UPDATE_FAILED: {
    code: "UPDATE_FAILED",
    category: "network",
    message: "All source re-resolutions failed. Nothing to update.",
    breadcrumbs: [
      { task: "Recover", description: "Verify the original source paths are still accessible." },
    ],
    sources: [
      "packages/cli/src/root/commands/update.ts:152",
      "packages/cli/src/root/skills/update/handler.ts:394",
      "packages/cli/src/root/subagents/update/handler.ts:221",
    ],
  },
  UPDATE_SOURCE_INVALID_FQN: {
    code: "UPDATE_SOURCE_INVALID_FQN",
    category: "validation",
    message: "Update source must be a registry FQN",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/update/resolve-root-update-intent.ts:86"],
  },
  UPDATE_SOURCE_NOT_FQN: {
    code: "UPDATE_SOURCE_NOT_FQN",
    category: "usage",
    message: "Root update only accepts registry FQNs",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/update/resolve-root-update-intent.ts:61"],
  },
  UPDATE_SOURCE_UNKNOWN_TYPE: {
    code: "UPDATE_SOURCE_UNKNOWN_TYPE",
    category: "not_found",
    message: "Update source uses an unsupported plural type",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/update/resolve-root-update-intent.ts:72"],
  },
  UPDATE_SOURCE_UNSUPPORTED_TYPE: {
    code: "UPDATE_SOURCE_UNSUPPORTED_TYPE",
    category: "usage",
    message: "Root update does not support that extension type",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/update/resolve-root-update-intent.ts:102"],
  },
  UPGRADE_DOWNLOAD_EMPTY: {
    code: "UPGRADE_DOWNLOAD_EMPTY",
    category: "validation",
    message: "Downloaded file is empty",
    breadcrumbs: [
      { task: "Recover", description: "Try again. If the problem persists, download manually." },
    ],
    sources: ["packages/cli/src/root/upgrade/handler.ts:137"],
  },
  UPGRADE_DOWNLOAD_FAILED: {
    code: "UPGRADE_DOWNLOAD_FAILED",
    category: "network",
    message: "Update download did not complete",
    breadcrumbs: [{ task: "Recover", description: "Check your network connection and try again." }],
    sources: [
      "packages/cli/src/root/upgrade/handler.ts:123",
      "packages/cli/src/root/upgrade/handler.ts:78",
    ],
  },
  UPGRADE_DOWNLOAD_TIMEOUT: {
    code: "UPGRADE_DOWNLOAD_TIMEOUT",
    category: "network",
    message: "Download timed out",
    breadcrumbs: [{ task: "Recover", description: "Check your network connection and try again." }],
    sources: ["packages/cli/src/root/upgrade/handler.ts:92"],
  },
  UPGRADE_VERIFY_FAILED: {
    code: "UPGRADE_VERIFY_FAILED",
    category: "validation",
    message: "Downloaded binary could not be verified",
    breadcrumbs: [
      {
        task: "Recover",
        description: "The upgrade may have succeeded. Try running `axm --version` to check.",
      },
    ],
    sources: ["packages/cli/src/root/upgrade/handler.ts:240"],
  },
  VERSION_RESOLUTION_INVALID_RESPONSE: {
    code: "VERSION_RESOLUTION_INVALID_RESPONSE",
    category: "validation",
    message: "GitHub API response was not valid JSON",
    breadcrumbs: [
      {
        task: "Recover",
        description: "This may indicate a GitHub API change. Please try again or report the issue.",
      },
    ],
    sources: [
      "packages/core/src/unstable/version-resolution/version-resolution.ts:113",
      "packages/core/src/unstable/version-resolution/version-resolution.ts:135",
    ],
  },
  VERSION_RESOLUTION_NETWORK_ERROR: {
    code: "VERSION_RESOLUTION_NETWORK_ERROR",
    category: "network",
    message: "GitHub API is unreachable",
    breadcrumbs: [{ task: "Recover", description: "Check your network connection and try again." }],
    sources: ["packages/core/src/unstable/version-resolution/version-resolution.ts:84"],
  },
  VERSION_RESOLUTION_NO_CLI_RELEASE: {
    code: "VERSION_RESOLUTION_NO_CLI_RELEASE",
    category: "not_found",
    message: "No CLI release found on GitHub",
    breadcrumbs: [
      {
        task: "Recover",
        description:
          "Ensure the repository has at least one release tagged with the 'cli-v' prefix.",
      },
    ],
    sources: ["packages/core/src/unstable/version-resolution/version-resolution.ts:192"],
  },
  VERSION_SET_TARGET_MISSING: {
    code: "VERSION_SET_TARGET_MISSING",
    category: "not_found",
    message: "`set` requires an exact semver version",
    breadcrumbs: [
      { task: "Recover", description: "Review the message, adjust the input, and retry." },
    ],
    sources: ["packages/cli/src/root/shared/version-command.ts:79"],
  },
} as const;

export type ErrorCodeCatalog = typeof ErrorCodeCatalog;
