/**
 * Area barrel for the package public surface.
 *
 * @experimental This API is unstable and may change without notice.
 */

export {
  type DiscoverPackageInput,
  DiscoverPackageInputSchema,
  type DiscoverPackagesRequest,
  DiscoverPackagesRequestSchema,
  type DiscoverPackagesResponse,
  DiscoverPackagesResponseSchema,
  type DiscoveryDeclaredExtension,
  DiscoveryDeclaredExtensionSchema,
  type DiscoveryExtensionResult,
  DiscoveryExtensionResultSchema,
  DiscoveryGitResolutionSchema,
  DiscoveryGitResolvedExtensionSchema,
  type DiscoveryPackageResult,
  DiscoveryPackageResultSchema,
  DiscoveryPathResolutionSchema,
  DiscoveryPathResolvedExtensionSchema,
  DiscoveryRegistryResolutionSchema,
  DiscoveryRegistryResolvedExtensionSchema,
  type DiscoveryResolvedExtension,
  DiscoveryResolvedExtensionSchema,
} from "./discover-schema.js";
export {
  MAX_RESOLUTION_METADATA_ITEMS,
  MAX_RESOLUTION_METADATA_REQUEST_BYTES,
  MAX_RESOLUTION_METADATA_RESPONSE_BYTES,
  MAX_RESOLUTION_METADATA_VERSIONS_PER_PAGE,
  RESOLUTION_METADATA_SCHEMA_VERSION,
  RESOLUTION_SELECTION_POLICY_VERSION,
  decodeResolutionMetadataRequestBody,
  type ResolutionMetadataError,
  ResolutionMetadataErrorSchema,
  ResolutionMetadataIdentitySchema,
  ResolutionMetadataItemSchema,
  type ResolutionMetadataOutcome,
  ResolutionMetadataOutcomeSchema,
  type ResolutionMetadataRequest,
  ResolutionMetadataRequestSchema,
  type ResolutionMetadataResponse,
  ResolutionMetadataResponseSchema,
  resolutionMetadataResponseMatchesRequest,
} from "./resolution-metadata.js";
export {
  MAX_PUBLICATION_SET_CANDIDATES,
  PUBLICATION_SET_CONTRACT,
  type PackDependencyDescriptor,
  type PackDependencyFinding,
  PackDependencyFindingSchema,
  type PreviewPublicationSetRequest,
  PreviewPublicationSetRequestSchema,
  type PreviewPublicationSetResponse,
  PreviewPublicationSetResponseSchema,
  type PublicationCandidateResult,
  type PublicationDescriptor,
  type PublicationPackResult,
  type PublicationTarget,
  type PublicationVisibilityInput,
  PublicationVisibilityInputSchema,
  type Sha256Hex,
  Sha256HexSchema,
  archiveSha256Hex,
  formatPackDependencyFinding,
  comparePublicationTargets,
  normalizePublicationDescriptor,
  normalizePublicationSet,
  publicationDescriptorDigest,
  publicationSetDigest,
  publicationTargetKey,
  validatePublicationDescriptors,
  validatePublicationSetResponse,
} from "./publication-set.js";
export {
  type ArchivalManagementView,
  ArchivalManagementViewSchema,
  ArchivalRevisionSchema,
  type ArchivalTransition,
  ArchivalTransitionSchema,
  type DeprecationManagementView,
  DeprecationManagementViewSchema,
  type DeprecationReplacementIntent,
  DeprecationReplacementIntentSchema,
  DeprecationRevisionSchema,
  type DeprecationTransition,
  DeprecationTransitionSchema,
  type ExtensionIndex,
  ExtensionIndexSchema,
  type VersionEntry,
  VersionEntrySchema,
  packagesToPackageUrlParts,
} from "./schema.js";
