/**
 * Generate the registry Effect HTTP client from the committed OpenAPI spec.
 *
 * Usage:
 *   pnpm exec nx run core:generate:registry-client
 */

// @effect-diagnostics nodeBuiltinImport:off globalConsole:off — Bun codegen script, not Effect code
import * as childProcess from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

const WORKSPACE_ROOT = path.join(import.meta.dirname, "..");
const CORE_ROOT = path.join(WORKSPACE_ROOT, "packages/core");
const SPEC_PATH = path.join(CORE_ROOT, "specs/registry-openapi.json");
const OUTPUT_DIR = path.join(CORE_ROOT, "src/unstable/registry/__generated__");
const OUTPUT_PATH = path.join(OUTPUT_DIR, "registry-client.ts");
const CLIENT_NAME = "RegistryClient";

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

const result = childProcess.spawnSync(
  "pnpm",
  ["exec", "openapigen", "--spec", SPEC_PATH, "--name", CLIENT_NAME],
  { cwd: CORE_ROOT, encoding: "utf-8", timeout: 30_000 },
);

if (result.status !== 0) {
  console.error("openapigen failed:");
  console.error(result.stderr || result.stdout);
  process.exit(1);
}

const header = `/**
 * @generated by core:generate:registry-client (openapigen)
 * Source:     packages/core/specs/registry-openapi.json
 * Regenerate: pnpm exec nx run core:generate:registry-client
 * DO NOT EDIT - changes are overwritten on regeneration.
 */
/* eslint-disable */

`;

fs.writeFileSync(OUTPUT_PATH, header + result.stdout);

const formatResult = childProcess.spawnSync("pnpm", ["exec", "prettier", "--write", OUTPUT_PATH], {
  cwd: CORE_ROOT,
  encoding: "utf-8",
  timeout: 30_000,
});

if (formatResult.status !== 0) {
  console.error("Format failed:");
  console.error(formatResult.stderr || formatResult.stdout);
  process.exit(1);
}

console.log(`Generated: ${path.relative(CORE_ROOT, OUTPUT_PATH)}`);
