// Existing production literals. Remove an entry with its site; additions require workload review.
export const existingUnboundedConcurrencySites: ReadonlyArray<string> = [
  '["apps/cli/src/test-support/command-tree-test-helpers.ts","{","concurrency: \\"unbounded\\",","},"]',
  '["packages/core/workspace/src/authoring/create/create-extension.ts",".pipe(Effect.map((outcome) => ({ agentId: agent.id, outcome }))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/configuration/setup/initialization.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/desired-state/workspace/read-model-record-readers.ts","const inventories = yield* Effect.forEach(types, (type) => getExtensionInventory(type, {}), {","concurrency: \\"unbounded\\",","});"]',
  '["packages/core/workspace/src/desired-state/workspace/read-model/discovery/plugin-manifests.ts","[parseMarketplaceJson(basePath), parsePluginJson(basePath)],","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/desired-state/workspace/read-model/scanners/agent-settings.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/discovery/packaging/detect.ts","const results = yield* Effect.forEach(detectors, (d) => d.detect(projectDir), {","concurrency: \\"unbounded\\",","});"]',
  '["packages/core/workspace/src/discovery/packaging/read.ts","},","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/hooks/manager.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/hooks/manager.ts","}),","{ concurrency: \\"unbounded\\" },","),"]',
  '["packages/core/workspace/src/inspection/extension-list/assessment.ts","const rowsByType = yield* Effect.forEach(types, (itemType) => records.rows(itemType), {","concurrency: \\"unbounded\\",","});"]',
  '["packages/core/workspace/src/inspection/knowledge/list-knowledge.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/inspection/show/show-extension.ts","],","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/inspection/test-helpers.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/inspection/test-helpers.ts","}).pipe(Effect.catch(() => Effect.succeed<ReadonlyArray<DiscoveredSkill>>([]))),","{ concurrency: \\"unbounded\\" },",").pipe(Effect.map(Array.flatten));"]',
  '["packages/core/workspace/src/inspection/type-list/type-lists.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/inspection/view/view-extension.ts",").pipe(Effect.result),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/instructions/manager.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/instructions/manager.ts","}),","{ concurrency: \\"unbounded\\" },","),"]',
  '["packages/core/workspace/src/knowledge/manager.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/activation/set-activation.ts","),","{ concurrency: \\"unbounded\\", discard: true },",");"]',
  '["packages/core/workspace/src/lifecycle/activation/set-activation.ts","),","{ concurrency: \\"unbounded\\", discard: true },",");"]',
  '["packages/core/workspace/src/lifecycle/install/configured.ts","([name, entry]) => planFor(name, entry.source),","{ concurrency: \\"unbounded\\" },","),"]',
  '["packages/core/workspace/src/lifecycle/install/configured.ts","([name, entry]) => planFor(name, entry.source),","{ concurrency: \\"unbounded\\" },","),"]',
  '["packages/core/workspace/src/lifecycle/install/configured.ts","([name, entry]) => planFor(name, entry.source),","{ concurrency: \\"unbounded\\" },","),"]',
  '["packages/core/workspace/src/lifecycle/install/configured.ts","([name, entry]) => planFor(name, entry.source),","{ concurrency: \\"unbounded\\" },","),"]',
  '["packages/core/workspace/src/lifecycle/install/configured.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/install/configured.ts",").pipe(Effect.map((collection) => ({ type, collection }))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/install/configured.ts","// The operation\'s request budget bounds transport while selections run together.","const resolvedPacks = yield* Effect.all(preparedPacks, { concurrency: \\"unbounded\\" });","const prospectivePacks = resolvedPacks.map(({ intent }) => intent.packToInstall);"]',
  '["packages/core/workspace/src/lifecycle/install/configured.ts",": planFor(name, entry.source),","{ concurrency: \\"unbounded\\" },","),"]',
  '["packages/core/workspace/src/lifecycle/install/configured.ts","plans: yield* Effect.forEach(entries, ([name, entry]) => planFor(name, entry.source), {","concurrency: \\"unbounded\\",","}),"]',
  '["packages/core/workspace/src/lifecycle/test-helpers.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/test-helpers.ts","}).pipe(Effect.catch(() => Effect.succeed<ReadonlyArray<DiscoveredSkill>>([]))),","{ concurrency: \\"unbounded\\" },",").pipe(Effect.map(Array.flatten));"]',
  '["packages/core/workspace/src/lifecycle/update/configured.ts","({ intent }) => planPackInstall(intent),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/update/configured.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/update/configured.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/update/configured.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/update/configured.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/update/configured.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/update/configured.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/update/configured.ts",");","const resolved = yield* Effect.all(prepared, { concurrency: \\"unbounded\\" });","const selected: ReadonlyArray<SelectedPackAdvance> = resolved.flatMap((item) =>"]',
  '["packages/core/workspace/src/lifecycle/update/selective/plan.ts","{","concurrency: \\"unbounded\\",","steps: units.map((unit): PlannedJobStep<R> => {"]',
  '["packages/core/workspace/src/lifecycle/update/selective/selection.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/update/selective/skills.ts","},","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/update/selective/subagents.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/lifecycle/update/selector.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/catalog/workspace-read-model/lint-workspace.ts","],","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/catalog/workspace-read-model/lint-workspace.ts","],","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/catalog/workspace-read-model/lint-workspace.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/catalog/workspace-read-model/lint-workspace.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/catalog/workspace-read-model/lint-workspace.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/catalog/workspace-read-model/lint-workspace.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/catalog/workspace-read-model/lint-workspace.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/catalog/workspace-read-model/lint-workspace.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/catalog/workspace-read-model/lint-workspace.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/catalog/workspace/configured-but-not-installed.ts","(type) => readRows(INSTALLED_ROWS_BY_TYPE[type](context.workspace)),","{ concurrency: \\"unbounded\\" },","),"]',
  '["packages/core/workspace/src/linting/catalog/workspace/packs-shared-members-distributable.ts","],","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/run/staged-workspace.ts","},","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/run/staged-workspace.ts","},","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/linting/runner.ts","],","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/materialization/test-helpers.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/materialization/test-helpers.ts","}).pipe(Effect.catch(() => Effect.succeed<ReadonlyArray<DiscoveredSkill>>([]))),","{ concurrency: \\"unbounded\\" },",").pipe(Effect.map(Array.flatten));"]',
  '["packages/core/workspace/src/mcp-connections/lifecycle/operations/disable.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/mcp-connections/lifecycle/operations/uninstall.ts",".pipe(Effect.map((outcome) => ({ agentId: agent.id, outcome }))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/mcp-connections/manager.ts","([name, entry]) => configuredAgentOutcomesForEntry({ name, entry, state }),","{ concurrency: \\"unbounded\\" },",")).flat();"]',
  '["packages/core/workspace/src/packs/lifecycle/promote-authored-pack.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/packs/lifecycle/resolved-dependency.ts",": Effect.void,","{ concurrency: \\"unbounded\\", discard: true },",");"]',
  '["packages/core/workspace/src/projection/agent-adapters/detection.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/agent-adapters/detection.ts","Effect.filter(Object.values(AGENTS), (agent) => detectAgentInRootRaw(agent, rootDir), {","concurrency: \\"unbounded\\",","}).pipe(Effect.mapError(wrapDetectionError(`Failed to detect installed agents in ${rootDir}`)));"]',
  '["packages/core/workspace/src/projection/agent-adapters/detection.ts","Effect.forEach(Object.values(AGENTS), (agent) => detectAgentScopes(agent, projectDir), {","concurrency: \\"unbounded\\",","}).pipe(Effect.map((detections) => detections.filter(({ project, user }) => project || user)));"]',
  '["packages/core/workspace/src/projection/agent-adapters/detection.ts","[detectAgentInRootRaw(agent, projectDir), detectScopeRaw(agent.detection.user, home, \\"user\\")],","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/agent-adapters/mcps/sync.ts","(candidate) => fs.exists(candidate).pipe(Effect.catch(() => Effect.succeed(false))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/agent-adapters/mcps/sync.ts",").pipe(Effect.map((results) => results.some(Boolean))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/agent-adapters/mcps/sync.ts","fs.exists(path.join(dir, candidate)).pipe(Effect.catch(() => Effect.succeed(false))),","{ concurrency: \\"unbounded\\" },",").pipe(Effect.map((results) => results.some(Boolean))),"]',
  '["packages/core/workspace/src/projection/agent-adapters/mcps/sync.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/agent-adapters/mcps/sync.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/agent-adapters/mcps/sync.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/agent-adapters/mcps/sync.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/agent-adapters/mcps/sync.ts","},","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/instructions/instructions.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/instructions/instructions.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/instructions/instructions.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/invariant-facts.ts","const observed = yield* Effect.forEach(participants.aggregates, observeParticipant, {","concurrency: \\"unbounded\\",","});"]',
  '["packages/core/workspace/src/projection/materialization-currency.ts","),","{ concurrency: \\"unbounded\\" },",").pipe(Effect.map((results) => results.every(Boolean)));"]',
  '["packages/core/workspace/src/projection/mcps/inspection.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/mcps/inspection.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/mcps/inspection.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/mcps/inspection.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/mcps/inspection.ts","},","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/projection/workspace-catalog-live.ts","),","{ concurrency: \\"unbounded\\" },",").pipe(Effect.provideService(FileSystem.FileSystem, observedFs), Effect.map(Array.flatten));"]',
  '["packages/core/workspace/src/projection/workspace-catalog-live.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/reconciliation/materialize.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/reconciliation/materialize.ts","skillMaterializeStep,","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/reconciliation/materialize.ts","}),","{ concurrency: \\"unbounded\\" },",").pipe("]',
  '["packages/core/workspace/src/reconciliation/mcps/install-operation.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/reconciliation/mcps/install-operation.ts",".pipe(Effect.map((value) => ({ name, value }))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/reconciliation/mcps/install-operation.ts","},","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/reconciliation/plan.ts","if (ruleSteps.length > 0) {","jobs.push({ concurrency: \\"unbounded\\", steps: ruleSteps });","}"]',
  '["packages/core/workspace/src/reconciliation/plan.ts","}).pipe(Effect.map((outcome) => ({ agentId, outcome }))),","{ concurrency: \\"unbounded\\" },",").pipe("]',
  '["packages/core/workspace/src/resolution/pack-dependency-resolution.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/resolution/pack-dependency-resolution.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/resolution/sources/resolve-identifier.ts","}).pipe(Effect.result),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/lifecycle/adapters/installation.ts",".pipe(Effect.map((outcome) => ({ agentId: agent.id, outcome }))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/lifecycle/adapters/installation.ts","},","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/lifecycle/install/bundled.ts","),","{ concurrency: \\"unbounded\\" },",").pipe("]',
  '["packages/core/workspace/src/skills/lifecycle/install/bundled.ts",".pipe(Effect.map((outcome) => ({ agentId: agent.id, outcome }))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/lifecycle/install/bundled.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/lifecycle/install/bundled.ts","},","{ concurrency: \\"unbounded\\", discard: true },",");"]',
  '["packages/core/workspace/src/skills/lifecycle/operations/disable.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/lifecycle/operations/enable.ts",".pipe(Effect.map((outcome) => ({ agent, outcome }))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/lifecycle/operations/enable.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/lifecycle/uninstall/plan.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/lifecycle/uninstall/plan.ts",".pipe(Effect.map((outcome) => ({ agentId: agent.id, outcome }))),","{ concurrency: \\"unbounded\\" },",").pipe("]',
  '["packages/core/workspace/src/skills/manager.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/manager.ts",".pipe(Effect.map((outcome) => ({ agent, outcome }))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/manager.ts",".pipe(Effect.map((outcome) => ({ agent, outcome }))),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/skills/skill-artifact.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/subagents/lifecycle/adapters/installation.ts","),","{ concurrency: \\"unbounded\\" },",").pipe("]',
  '["packages/core/workspace/src/subagents/lifecycle/operations/disable.ts","}),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/core/workspace/src/subagents/lifecycle/operations/enable.ts","),","{ concurrency: \\"unbounded\\" },",");"]',
  '["packages/supporting/cli-maintenance/src/self-update/adapters/native/subprocess/subprocess.ts","},","{ concurrency: \\"unbounded\\" },",").pipe("]',
];
