/**
 * Generated by packages/cli/scripts/generate-agent-catalog.ts.
 * Do not edit directly.
 */

import * as Schema from "effect/Schema";
import type { Agent } from "./schema.js";

/** @experimental This API is unstable and may change without notice. */
export const AGENT_IDS = [
  "claude-code",
  "codex",
  "cursor",
  "gemini-cli",
  "github-copilot",
  "windsurf",
] as const;

/** @experimental This API is unstable and may change without notice. */
export type AgentId = (typeof AGENT_IDS)[number];

/** @experimental This API is unstable and may change without notice. */
export const AgentIdSchema = Schema.Literals([...AGENT_IDS]).annotate({
  identifier: "AgentId",
  title: "Agent ID",
  description: "Verified coding agent identifier in the capability catalog.",
  examples: ["claude-code", "codex", "cursor"],
});

/** @experimental This API is unstable and may change without notice. */
export const AGENTS = [
  {
    id: "claude-code",
    name: "Claude Code",
    vendor: "Anthropic",
    homepage: "https://claude.com/claude-code",
    interfaces: ["cli", "ide-extension"],
    family: "anthropic",
    docs: [
      {
        label: "Claude Code documentation",
        url: "https://docs.claude.com/en/docs/claude-code",
      },
    ],
    skills: {
      support: "standard",
      sources: ["https://docs.claude.com/en/docs/claude-code/skills"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      directory: ".claude/skills",
    },
    commands: {
      support: "standard",
      sources: ["https://docs.claude.com/en/docs/claude-code/slash-commands"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      directory: ".claude/commands",
    },
    mcp: {
      support: "standard",
      sources: ["https://docs.claude.com/en/docs/claude-code/mcp"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio", "http", "sse"],
    },
    subagents: {
      support: "bridged",
      sources: ["https://docs.claude.com/en/docs/claude-code/sub-agents"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
    },
    instructions: {
      support: "bridged",
      sources: ["https://docs.claude.com/en/docs/claude-code/memory"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      files: ["CLAUDE.md"],
      nestedDiscovery: true,
    },
    permissions: {
      support: "standard",
      sources: [
        "https://docs.claude.com/en/docs/claude-code/iam",
        "https://docs.claude.com/en/docs/claude-code/settings",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user", "project"],
      mechanism: ["config-file"],
      configFiles: [
        {
          scope: "user",
          path: "~/.claude/settings.json",
          format: "json",
        },
        {
          scope: "project",
          path: ".claude/settings.json",
          format: "json",
        },
        {
          scope: "project",
          path: ".claude/settings.local.json",
          format: "json",
          gitignored: true,
        },
      ],
      grammar: {
        style: "tool-call",
        example: "Bash(axm:*)",
        notes:
          "Tool(specifier) with * wildcards. Evaluated deny > ask > allow (first match wins). Settings merge across scopes rather than override.\n",
      },
      grants: {
        shell: {
          target: "~/.claude/settings.json",
          patch: {
            permissions: {
              allow: ["Bash(${tool}:*)"],
            },
          },
        },
        filesystem: {
          target: "~/.claude/settings.json",
          patch: {
            permissions: {
              allow: [
                "Read(${workspaceRoot}/**)",
                "Write(${workspaceRoot}/**)",
                "Edit(${workspaceRoot}/**)",
              ],
            },
          },
        },
      },
    },
  },
  {
    id: "codex",
    name: "Codex",
    vendor: "OpenAI",
    homepage: "https://developers.openai.com/codex",
    interfaces: ["cli", "ide-extension"],
    family: "openai",
    docs: [
      {
        label: "Codex documentation",
        url: "https://developers.openai.com/codex",
      },
    ],
    mcp: {
      support: "standard",
      sources: ["https://github.com/openai/codex/blob/main/docs/config.md#mcp-servers"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio", "http"],
    },
    instructions: {
      support: "standard",
      sources: ["https://github.com/openai/codex/blob/main/docs/agents_md.md"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      files: ["AGENTS.md"],
      nestedDiscovery: true,
    },
    permissions: {
      support: "standard",
      sources: [
        "https://developers.openai.com/codex/config-reference",
        "https://developers.openai.com/codex/config-advanced",
        "https://developers.openai.com/codex/security",
        "https://developers.openai.com/codex/rules",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user", "project"],
      mechanism: ["config-file", "cli-flag"],
      configFiles: [
        {
          scope: "user",
          path: "~/.codex/config.toml",
          format: "toml",
        },
        {
          scope: "user",
          path: "~/.codex/rules/${tool}.rules",
          format: "starlark",
        },
      ],
      grammar: {
        style: "starlark-rule",
        example: 'prefix_rule(pattern=["axm"], decision="allow")',
        notes:
          "Per-command allowlisting is Starlark prefix_rule() in ~/.codex/rules/*.rules. Sandbox and approval mode live separately in config.toml. Most restrictive match wins (forbidden > prompt > allow).\n",
      },
      prerequisites: [
        {
          key: "sandbox_mode",
          value: "workspace-write",
          scope: "user",
          note: "Required to grant project write access.",
        },
        {
          key: "approval_policy",
          value: "never",
          scope: "user",
          note: "Suppresses approval prompts.",
        },
      ],
      cliFlags: [
        {
          flag: "--full-auto",
          note: "Equivalent one-shot bypass of prompts and sandbox restrictions.",
        },
        {
          flag: "--sandbox workspace-write",
        },
        {
          flag: "--ask-for-approval never",
        },
      ],
      grants: {
        shell: {
          target: "~/.codex/rules/${tool}.rules",
          template:
            'prefix_rule(\n    pattern = ["${tool}"],\n    decision = "allow",\n    justification = "${tool} CLI trusted in this workspace.",\n)\n',
        },
        filesystem: {
          target: "~/.codex/config.toml",
          patch: {
            sandbox_mode: "workspace-write",
            sandbox_workspace_write: {
              writable_roots: ["${workspaceRoot}"],
              network_access: true,
            },
          },
        },
      },
    },
  },
  {
    id: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    homepage: "https://cursor.com",
    interfaces: ["ide-extension", "cli"],
    family: "cursor",
    docs: [
      {
        label: "Cursor documentation",
        url: "https://docs.cursor.com",
      },
    ],
    mcp: {
      support: "standard",
      sources: ["https://docs.cursor.com/advanced/model-context-protocol"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio", "http", "sse"],
    },
    instructions: {
      support: "standard",
      sources: ["https://docs.cursor.com/en/cli/using"],
      lastVerified: "2026-05-16",
      scopes: ["project"],
      files: ["AGENTS.md", "CLAUDE.md"],
      nestedDiscovery: false,
    },
    rules: {
      support: "bridged",
      sources: ["https://docs.cursor.com/en/context/rules"],
      lastVerified: "2026-05-16",
      scopes: ["project"],
      directory: ".cursor/rules",
    },
    permissions: {
      support: "standard",
      sources: [
        "https://cursor.com/docs/reference/permissions",
        "https://cursor.com/docs/reference/sandbox",
        "https://cursor.com/docs/agent/tools/terminal",
        "https://cursor.com/docs/cli/reference/permissions",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user", "project"],
      mechanism: ["config-file", "ui-only", "cli-flag"],
      configFiles: [
        {
          scope: "user",
          path: "~/.cursor/permissions.json",
          format: "json",
        },
        {
          scope: "user",
          path: "~/.cursor/sandbox.json",
          format: "json",
        },
        {
          scope: "project",
          path: ".cursor/sandbox.json",
          format: "json",
        },
        {
          scope: "user",
          path: "~/.cursor/cli-config.json",
          format: "json",
        },
        {
          scope: "project",
          path: ".cursor/cli.json",
          format: "json",
        },
      ],
      grammar: {
        style: "prefix",
        example: "axm",
        notes:
          "IDE: case-sensitive command prefix in terminalAllowlist. CLI: Tool-call syntax Shell()/Read()/Write() with glob patterns. Deny always beats allow.\n",
      },
      prerequisites: [
        {
          key: "Settings > Cursor Settings > Agents > Auto-Run",
          value: "Run in Sandbox | Run Everything",
          scope: "user",
          note: "IDE Auto-Run must be enabled before terminalAllowlist takes effect.",
        },
      ],
      cliFlags: [
        {
          flag: "--force",
          note: "Bypasses cursor-agent prompts (community-documented; verify against --help).",
        },
        {
          flag: "--yolo",
          note: "Bypasses cursor-agent prompts (community-documented; verify against --help).",
        },
      ],
      grants: {
        shell: {
          target: "~/.cursor/permissions.json",
          patch: {
            terminalAllowlist: ["${tool}"],
          },
        },
        cliShell: {
          target: ".cursor/cli.json",
          patch: {
            permissions: {
              allow: ["Shell(${tool})", "Shell(${tool}:*)"],
            },
          },
        },
        filesystem: {
          target: ".cursor/sandbox.json",
          patch: {
            type: "workspace_readwrite",
            additionalReadwritePaths: [],
          },
        },
      },
    },
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    vendor: "Google",
    homepage: "https://github.com/google-gemini/gemini-cli",
    interfaces: ["cli"],
    family: "google",
    docs: [
      {
        label: "Gemini CLI documentation",
        url: "https://github.com/google-gemini/gemini-cli/tree/main/docs",
      },
    ],
    skills: {
      support: "standard",
      sources: ["https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/cli-reference.md"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      directory: ".gemini/skills",
    },
    mcp: {
      support: "standard",
      sources: ["https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/cli-reference.md"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio"],
    },
    instructions: {
      support: "bridged",
      sources: ["https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/configuration.md"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      files: ["GEMINI.md"],
      nestedDiscovery: true,
    },
    permissions: {
      support: "standard",
      sources: [
        "https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/settings.md",
        "https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/cli-reference.md",
        "https://github.com/google-gemini/gemini-cli/blob/main/docs/tools/shell.md",
        "https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/trusted-folders.md",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user", "project"],
      mechanism: ["config-file", "cli-flag"],
      configFiles: [
        {
          scope: "user",
          path: "~/.gemini/settings.json",
          format: "json",
        },
        {
          scope: "project",
          path: ".gemini/settings.json",
          format: "json",
        },
      ],
      grammar: {
        style: "prefix",
        example: "run_shell_command(axm)",
        notes:
          "tools.core is prefix-matched and currently documented in docs/tools/shell.md. The newer Policy Engine is replacing --allowed-tools; tools.core is still functional but transitional.\n",
      },
      prerequisites: [
        {
          key: "security.folderTrust.enabled",
          value: "true",
          scope: "user",
          note: "Untrusted folders disable all auto-acceptance regardless of other settings.",
        },
      ],
      cliFlags: [
        {
          flag: "--approval-mode=yolo",
          note: "Broad bypass; not tool-scoped. Blocked when security.disableYoloMode=true.",
        },
        {
          flag: "--yolo",
          note: "Alias for --approval-mode=yolo.",
        },
      ],
      grants: {
        shell: {
          target: "~/.gemini/settings.json",
          patch: {
            security: {
              folderTrust: {
                enabled: true,
              },
              enablePermanentToolApproval: true,
            },
            tools: {
              core: ["run_shell_command(${tool})"],
            },
          },
        },
      },
    },
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    vendor: "GitHub",
    homepage: "https://github.com/features/copilot",
    interfaces: ["ide-extension", "cli"],
    family: "github",
    docs: [
      {
        label: "GitHub Copilot documentation",
        url: "https://docs.github.com/en/copilot",
      },
    ],
    mcp: {
      support: "standard",
      sources: [
        "https://docs.github.com/en/copilot/concepts/agents/coding-agent/mcp-and-coding-agent",
      ],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio", "http", "sse"],
    },
    subagents: {
      support: "bridged",
      sources: ["https://docs.github.com/en/copilot/reference/custom-agents-configuration"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
    },
    instructions: {
      support: "standard",
      sources: ["https://code.visualstudio.com/docs/copilot/customization/custom-instructions"],
      lastVerified: "2026-05-16",
      scopes: ["project"],
      files: ["AGENTS.md", ".github/copilot-instructions.md"],
      nestedDiscovery: false,
    },
    permissions: {
      support: "standard",
      sources: [
        "https://code.visualstudio.com/docs/copilot/reference/copilot-settings",
        "https://code.visualstudio.com/docs/copilot/chat/chat-agent-mode",
        "https://code.visualstudio.com/docs/copilot/agents/agent-tools",
        "https://docs.github.com/en/copilot/concepts/agents/coding-agent",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user", "project"],
      mechanism: ["config-file"],
      configFiles: [
        {
          scope: "user",
          path: "~/Library/Application Support/Code/User/settings.json",
          format: "vscode-settings",
        },
        {
          scope: "project",
          path: ".vscode/settings.json",
          format: "vscode-settings",
        },
      ],
      grammar: {
        style: "regex",
        example: '"/^axm(\\\\s|$)/": true',
        notes:
          "chat.tools.terminal.autoApprove keys are literal command names or /regex/ patterns mapping to bool. Default deny rules for rm, chmod, etc. remain active unless chat.tools.terminal.ignoreDefaultAutoApproveRules is set.\n",
      },
      cliFlags: [],
      grants: {
        shell: {
          target: ".vscode/settings.json",
          patch: {
            "chat.tools.terminal.autoApprove": {
              "${tool}": true,
              "/^${tool}(\\s|$)/": true,
            },
          },
        },
        filesystem: {
          target: ".vscode/settings.json",
          patch: {
            "chat.tools.edits.autoApprove": {
              "**/*": true,
            },
          },
        },
      },
    },
  },
  {
    id: "windsurf",
    name: "Windsurf",
    vendor: "Cognition",
    homepage: "https://windsurf.com",
    interfaces: ["ide-extension"],
    family: "cognition",
    docs: [
      {
        label: "Windsurf documentation",
        url: "https://docs.windsurf.com",
      },
    ],
    mcp: {
      support: "standard",
      sources: ["https://docs.windsurf.com/windsurf/cascade/mcp"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio"],
    },
    instructions: {
      support: "standard",
      sources: ["https://docs.windsurf.com/windsurf/cascade/agents-md"],
      lastVerified: "2026-05-16",
      scopes: ["project"],
      files: ["AGENTS.md"],
      nestedDiscovery: true,
    },
    rules: {
      support: "bridged",
      sources: ["https://docs.windsurf.com/windsurf/cascade/rules"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      directory: ".windsurf/rules",
    },
    permissions: {
      support: "standard",
      sources: [
        "https://docs.windsurf.com/windsurf/terminal",
        "https://docs.windsurf.com/windsurf/cascade",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user"],
      mechanism: ["config-file", "ui-only"],
      configFiles: [
        {
          scope: "user",
          path: "VS Code settings (Settings UI)",
          format: "vscode-settings",
        },
      ],
      grammar: {
        style: "prefix",
        example: "axm",
        notes:
          "windsurf.cascadeCommandsAllowList is prefix-matched. Workspace-scoped override for these keys is not documented; configure at user scope. Teams/Enterprise can merge in lists via the Admin Portal.\n",
      },
      prerequisites: [
        {
          key: "Cascade auto-execution level",
          value: "allowlist_only | turbo",
          scope: "user",
          note: "Disabled and Auto modes ignore allowlist entries; set via the Windsurf Settings panel.",
        },
      ],
      grants: {
        shell: {
          target: "VS Code settings",
          patch: {
            "windsurf.cascadeCommandsAllowList": ["${tool}"],
          },
        },
      },
    },
  },
] as const satisfies ReadonlyArray<Agent>;

/** @experimental This API is unstable and may change without notice. */
export const AGENTS_BY_ID = {
  "claude-code": {
    id: "claude-code",
    name: "Claude Code",
    vendor: "Anthropic",
    homepage: "https://claude.com/claude-code",
    interfaces: ["cli", "ide-extension"],
    family: "anthropic",
    docs: [
      {
        label: "Claude Code documentation",
        url: "https://docs.claude.com/en/docs/claude-code",
      },
    ],
    skills: {
      support: "standard",
      sources: ["https://docs.claude.com/en/docs/claude-code/skills"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      directory: ".claude/skills",
    },
    commands: {
      support: "standard",
      sources: ["https://docs.claude.com/en/docs/claude-code/slash-commands"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      directory: ".claude/commands",
    },
    mcp: {
      support: "standard",
      sources: ["https://docs.claude.com/en/docs/claude-code/mcp"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio", "http", "sse"],
    },
    subagents: {
      support: "bridged",
      sources: ["https://docs.claude.com/en/docs/claude-code/sub-agents"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
    },
    instructions: {
      support: "bridged",
      sources: ["https://docs.claude.com/en/docs/claude-code/memory"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      files: ["CLAUDE.md"],
      nestedDiscovery: true,
    },
    permissions: {
      support: "standard",
      sources: [
        "https://docs.claude.com/en/docs/claude-code/iam",
        "https://docs.claude.com/en/docs/claude-code/settings",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user", "project"],
      mechanism: ["config-file"],
      configFiles: [
        {
          scope: "user",
          path: "~/.claude/settings.json",
          format: "json",
        },
        {
          scope: "project",
          path: ".claude/settings.json",
          format: "json",
        },
        {
          scope: "project",
          path: ".claude/settings.local.json",
          format: "json",
          gitignored: true,
        },
      ],
      grammar: {
        style: "tool-call",
        example: "Bash(axm:*)",
        notes:
          "Tool(specifier) with * wildcards. Evaluated deny > ask > allow (first match wins). Settings merge across scopes rather than override.\n",
      },
      grants: {
        shell: {
          target: "~/.claude/settings.json",
          patch: {
            permissions: {
              allow: ["Bash(${tool}:*)"],
            },
          },
        },
        filesystem: {
          target: "~/.claude/settings.json",
          patch: {
            permissions: {
              allow: [
                "Read(${workspaceRoot}/**)",
                "Write(${workspaceRoot}/**)",
                "Edit(${workspaceRoot}/**)",
              ],
            },
          },
        },
      },
    },
  },
  codex: {
    id: "codex",
    name: "Codex",
    vendor: "OpenAI",
    homepage: "https://developers.openai.com/codex",
    interfaces: ["cli", "ide-extension"],
    family: "openai",
    docs: [
      {
        label: "Codex documentation",
        url: "https://developers.openai.com/codex",
      },
    ],
    mcp: {
      support: "standard",
      sources: ["https://github.com/openai/codex/blob/main/docs/config.md#mcp-servers"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio", "http"],
    },
    instructions: {
      support: "standard",
      sources: ["https://github.com/openai/codex/blob/main/docs/agents_md.md"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      files: ["AGENTS.md"],
      nestedDiscovery: true,
    },
    permissions: {
      support: "standard",
      sources: [
        "https://developers.openai.com/codex/config-reference",
        "https://developers.openai.com/codex/config-advanced",
        "https://developers.openai.com/codex/security",
        "https://developers.openai.com/codex/rules",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user", "project"],
      mechanism: ["config-file", "cli-flag"],
      configFiles: [
        {
          scope: "user",
          path: "~/.codex/config.toml",
          format: "toml",
        },
        {
          scope: "user",
          path: "~/.codex/rules/${tool}.rules",
          format: "starlark",
        },
      ],
      grammar: {
        style: "starlark-rule",
        example: 'prefix_rule(pattern=["axm"], decision="allow")',
        notes:
          "Per-command allowlisting is Starlark prefix_rule() in ~/.codex/rules/*.rules. Sandbox and approval mode live separately in config.toml. Most restrictive match wins (forbidden > prompt > allow).\n",
      },
      prerequisites: [
        {
          key: "sandbox_mode",
          value: "workspace-write",
          scope: "user",
          note: "Required to grant project write access.",
        },
        {
          key: "approval_policy",
          value: "never",
          scope: "user",
          note: "Suppresses approval prompts.",
        },
      ],
      cliFlags: [
        {
          flag: "--full-auto",
          note: "Equivalent one-shot bypass of prompts and sandbox restrictions.",
        },
        {
          flag: "--sandbox workspace-write",
        },
        {
          flag: "--ask-for-approval never",
        },
      ],
      grants: {
        shell: {
          target: "~/.codex/rules/${tool}.rules",
          template:
            'prefix_rule(\n    pattern = ["${tool}"],\n    decision = "allow",\n    justification = "${tool} CLI trusted in this workspace.",\n)\n',
        },
        filesystem: {
          target: "~/.codex/config.toml",
          patch: {
            sandbox_mode: "workspace-write",
            sandbox_workspace_write: {
              writable_roots: ["${workspaceRoot}"],
              network_access: true,
            },
          },
        },
      },
    },
  },
  cursor: {
    id: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    homepage: "https://cursor.com",
    interfaces: ["ide-extension", "cli"],
    family: "cursor",
    docs: [
      {
        label: "Cursor documentation",
        url: "https://docs.cursor.com",
      },
    ],
    mcp: {
      support: "standard",
      sources: ["https://docs.cursor.com/advanced/model-context-protocol"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio", "http", "sse"],
    },
    instructions: {
      support: "standard",
      sources: ["https://docs.cursor.com/en/cli/using"],
      lastVerified: "2026-05-16",
      scopes: ["project"],
      files: ["AGENTS.md", "CLAUDE.md"],
      nestedDiscovery: false,
    },
    rules: {
      support: "bridged",
      sources: ["https://docs.cursor.com/en/context/rules"],
      lastVerified: "2026-05-16",
      scopes: ["project"],
      directory: ".cursor/rules",
    },
    permissions: {
      support: "standard",
      sources: [
        "https://cursor.com/docs/reference/permissions",
        "https://cursor.com/docs/reference/sandbox",
        "https://cursor.com/docs/agent/tools/terminal",
        "https://cursor.com/docs/cli/reference/permissions",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user", "project"],
      mechanism: ["config-file", "ui-only", "cli-flag"],
      configFiles: [
        {
          scope: "user",
          path: "~/.cursor/permissions.json",
          format: "json",
        },
        {
          scope: "user",
          path: "~/.cursor/sandbox.json",
          format: "json",
        },
        {
          scope: "project",
          path: ".cursor/sandbox.json",
          format: "json",
        },
        {
          scope: "user",
          path: "~/.cursor/cli-config.json",
          format: "json",
        },
        {
          scope: "project",
          path: ".cursor/cli.json",
          format: "json",
        },
      ],
      grammar: {
        style: "prefix",
        example: "axm",
        notes:
          "IDE: case-sensitive command prefix in terminalAllowlist. CLI: Tool-call syntax Shell()/Read()/Write() with glob patterns. Deny always beats allow.\n",
      },
      prerequisites: [
        {
          key: "Settings > Cursor Settings > Agents > Auto-Run",
          value: "Run in Sandbox | Run Everything",
          scope: "user",
          note: "IDE Auto-Run must be enabled before terminalAllowlist takes effect.",
        },
      ],
      cliFlags: [
        {
          flag: "--force",
          note: "Bypasses cursor-agent prompts (community-documented; verify against --help).",
        },
        {
          flag: "--yolo",
          note: "Bypasses cursor-agent prompts (community-documented; verify against --help).",
        },
      ],
      grants: {
        shell: {
          target: "~/.cursor/permissions.json",
          patch: {
            terminalAllowlist: ["${tool}"],
          },
        },
        cliShell: {
          target: ".cursor/cli.json",
          patch: {
            permissions: {
              allow: ["Shell(${tool})", "Shell(${tool}:*)"],
            },
          },
        },
        filesystem: {
          target: ".cursor/sandbox.json",
          patch: {
            type: "workspace_readwrite",
            additionalReadwritePaths: [],
          },
        },
      },
    },
  },
  "gemini-cli": {
    id: "gemini-cli",
    name: "Gemini CLI",
    vendor: "Google",
    homepage: "https://github.com/google-gemini/gemini-cli",
    interfaces: ["cli"],
    family: "google",
    docs: [
      {
        label: "Gemini CLI documentation",
        url: "https://github.com/google-gemini/gemini-cli/tree/main/docs",
      },
    ],
    skills: {
      support: "standard",
      sources: ["https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/cli-reference.md"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      directory: ".gemini/skills",
    },
    mcp: {
      support: "standard",
      sources: ["https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/cli-reference.md"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio"],
    },
    instructions: {
      support: "bridged",
      sources: ["https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/configuration.md"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      files: ["GEMINI.md"],
      nestedDiscovery: true,
    },
    permissions: {
      support: "standard",
      sources: [
        "https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/settings.md",
        "https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/cli-reference.md",
        "https://github.com/google-gemini/gemini-cli/blob/main/docs/tools/shell.md",
        "https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/trusted-folders.md",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user", "project"],
      mechanism: ["config-file", "cli-flag"],
      configFiles: [
        {
          scope: "user",
          path: "~/.gemini/settings.json",
          format: "json",
        },
        {
          scope: "project",
          path: ".gemini/settings.json",
          format: "json",
        },
      ],
      grammar: {
        style: "prefix",
        example: "run_shell_command(axm)",
        notes:
          "tools.core is prefix-matched and currently documented in docs/tools/shell.md. The newer Policy Engine is replacing --allowed-tools; tools.core is still functional but transitional.\n",
      },
      prerequisites: [
        {
          key: "security.folderTrust.enabled",
          value: "true",
          scope: "user",
          note: "Untrusted folders disable all auto-acceptance regardless of other settings.",
        },
      ],
      cliFlags: [
        {
          flag: "--approval-mode=yolo",
          note: "Broad bypass; not tool-scoped. Blocked when security.disableYoloMode=true.",
        },
        {
          flag: "--yolo",
          note: "Alias for --approval-mode=yolo.",
        },
      ],
      grants: {
        shell: {
          target: "~/.gemini/settings.json",
          patch: {
            security: {
              folderTrust: {
                enabled: true,
              },
              enablePermanentToolApproval: true,
            },
            tools: {
              core: ["run_shell_command(${tool})"],
            },
          },
        },
      },
    },
  },
  "github-copilot": {
    id: "github-copilot",
    name: "GitHub Copilot",
    vendor: "GitHub",
    homepage: "https://github.com/features/copilot",
    interfaces: ["ide-extension", "cli"],
    family: "github",
    docs: [
      {
        label: "GitHub Copilot documentation",
        url: "https://docs.github.com/en/copilot",
      },
    ],
    mcp: {
      support: "standard",
      sources: [
        "https://docs.github.com/en/copilot/concepts/agents/coding-agent/mcp-and-coding-agent",
      ],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio", "http", "sse"],
    },
    subagents: {
      support: "bridged",
      sources: ["https://docs.github.com/en/copilot/reference/custom-agents-configuration"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
    },
    instructions: {
      support: "standard",
      sources: ["https://code.visualstudio.com/docs/copilot/customization/custom-instructions"],
      lastVerified: "2026-05-16",
      scopes: ["project"],
      files: ["AGENTS.md", ".github/copilot-instructions.md"],
      nestedDiscovery: false,
    },
    permissions: {
      support: "standard",
      sources: [
        "https://code.visualstudio.com/docs/copilot/reference/copilot-settings",
        "https://code.visualstudio.com/docs/copilot/chat/chat-agent-mode",
        "https://code.visualstudio.com/docs/copilot/agents/agent-tools",
        "https://docs.github.com/en/copilot/concepts/agents/coding-agent",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user", "project"],
      mechanism: ["config-file"],
      configFiles: [
        {
          scope: "user",
          path: "~/Library/Application Support/Code/User/settings.json",
          format: "vscode-settings",
        },
        {
          scope: "project",
          path: ".vscode/settings.json",
          format: "vscode-settings",
        },
      ],
      grammar: {
        style: "regex",
        example: '"/^axm(\\\\s|$)/": true',
        notes:
          "chat.tools.terminal.autoApprove keys are literal command names or /regex/ patterns mapping to bool. Default deny rules for rm, chmod, etc. remain active unless chat.tools.terminal.ignoreDefaultAutoApproveRules is set.\n",
      },
      cliFlags: [],
      grants: {
        shell: {
          target: ".vscode/settings.json",
          patch: {
            "chat.tools.terminal.autoApprove": {
              "${tool}": true,
              "/^${tool}(\\s|$)/": true,
            },
          },
        },
        filesystem: {
          target: ".vscode/settings.json",
          patch: {
            "chat.tools.edits.autoApprove": {
              "**/*": true,
            },
          },
        },
      },
    },
  },
  windsurf: {
    id: "windsurf",
    name: "Windsurf",
    vendor: "Cognition",
    homepage: "https://windsurf.com",
    interfaces: ["ide-extension"],
    family: "cognition",
    docs: [
      {
        label: "Windsurf documentation",
        url: "https://docs.windsurf.com",
      },
    ],
    mcp: {
      support: "standard",
      sources: ["https://docs.windsurf.com/windsurf/cascade/mcp"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      transports: ["stdio"],
    },
    instructions: {
      support: "standard",
      sources: ["https://docs.windsurf.com/windsurf/cascade/agents-md"],
      lastVerified: "2026-05-16",
      scopes: ["project"],
      files: ["AGENTS.md"],
      nestedDiscovery: true,
    },
    rules: {
      support: "bridged",
      sources: ["https://docs.windsurf.com/windsurf/cascade/rules"],
      lastVerified: "2026-05-16",
      scopes: ["user", "project"],
      directory: ".windsurf/rules",
    },
    permissions: {
      support: "standard",
      sources: [
        "https://docs.windsurf.com/windsurf/terminal",
        "https://docs.windsurf.com/windsurf/cascade",
      ],
      lastVerified: "2026-05-18",
      scopes: ["user"],
      mechanism: ["config-file", "ui-only"],
      configFiles: [
        {
          scope: "user",
          path: "VS Code settings (Settings UI)",
          format: "vscode-settings",
        },
      ],
      grammar: {
        style: "prefix",
        example: "axm",
        notes:
          "windsurf.cascadeCommandsAllowList is prefix-matched. Workspace-scoped override for these keys is not documented; configure at user scope. Teams/Enterprise can merge in lists via the Admin Portal.\n",
      },
      prerequisites: [
        {
          key: "Cascade auto-execution level",
          value: "allowlist_only | turbo",
          scope: "user",
          note: "Disabled and Auto modes ignore allowlist entries; set via the Windsurf Settings panel.",
        },
      ],
      grants: {
        shell: {
          target: "VS Code settings",
          patch: {
            "windsurf.cascadeCommandsAllowList": ["${tool}"],
          },
        },
      },
    },
  },
} as const satisfies Record<AgentId, Agent>;
