/**
 * Agent capability catalog.
 *
 * @experimental This API is unstable and may change without notice.
 */

import * as Schema from "effect/Schema";
import type { Agent } from "./schema.js";
import {
  adalAgent,
  aiderDeskAgent,
  ampAgent,
  antigravityAgent,
  augmentAgent,
  claudeCodeAgent,
  clineAgent,
  codeartsAgentAgent,
  codebuddyAgent,
  codemakerAgent,
  codestudioAgent,
  codexAgent,
  commandCodeAgent,
  continueAgent,
  cortexAgent,
  crushAgent,
  cursorAgent,
  deepagentsAgent,
  devinAgent,
  dextoAgent,
  droidAgent,
  firebenderAgent,
  forgecodeAgent,
  geminiCliAgent,
  githubCopilotAgent,
  gooseAgent,
  grokCliAgent,
  hermesAgent,
  ibmBobAgent,
  junieAgent,
  kiloAgent,
  kimiCliAgent,
  kiroCliAgent,
  kodeAgent,
  mcpjamAgent,
  mistralVibeAgent,
  muxAgent,
  neovateAgent,
  openclawAgent,
  opencodeAgent,
  openhandsAgent,
  piAgent,
  pochiAgent,
  qoderAgent,
  qwenCodeAgent,
  replitAgent,
  rooAgent,
  rovodevAgent,
  tabnineCliAgent,
  traeCnAgent,
  traeAgent,
  warpAgent,
  windsurfAgent,
  zencoderAgent,
} from "./data/agents/index.js";

const defineCatalog = <const T extends Record<string, Agent>>(
  entries: T & { readonly [K in keyof T]: { readonly id: K } },
): T => entries;

/** @experimental This API is unstable and may change without notice. */
export const AGENTS_BY_ID = defineCatalog({
  adal: adalAgent,
  "aider-desk": aiderDeskAgent,
  amp: ampAgent,
  antigravity: antigravityAgent,
  augment: augmentAgent,
  "claude-code": claudeCodeAgent,
  cline: clineAgent,
  "codearts-agent": codeartsAgentAgent,
  codebuddy: codebuddyAgent,
  codemaker: codemakerAgent,
  codestudio: codestudioAgent,
  codex: codexAgent,
  "command-code": commandCodeAgent,
  continue: continueAgent,
  cortex: cortexAgent,
  crush: crushAgent,
  cursor: cursorAgent,
  deepagents: deepagentsAgent,
  devin: devinAgent,
  dexto: dextoAgent,
  droid: droidAgent,
  firebender: firebenderAgent,
  forgecode: forgecodeAgent,
  "gemini-cli": geminiCliAgent,
  "github-copilot": githubCopilotAgent,
  goose: gooseAgent,
  "grok-cli": grokCliAgent,
  hermes: hermesAgent,
  "ibm-bob": ibmBobAgent,
  junie: junieAgent,
  kilo: kiloAgent,
  "kimi-cli": kimiCliAgent,
  "kiro-cli": kiroCliAgent,
  kode: kodeAgent,
  mcpjam: mcpjamAgent,
  "mistral-vibe": mistralVibeAgent,
  mux: muxAgent,
  neovate: neovateAgent,
  openclaw: openclawAgent,
  opencode: opencodeAgent,
  openhands: openhandsAgent,
  pi: piAgent,
  pochi: pochiAgent,
  qoder: qoderAgent,
  "qwen-code": qwenCodeAgent,
  replit: replitAgent,
  roo: rooAgent,
  rovodev: rovodevAgent,
  "tabnine-cli": tabnineCliAgent,
  "trae-cn": traeCnAgent,
  trae: traeAgent,
  warp: warpAgent,
  windsurf: windsurfAgent,
  zencoder: zencoderAgent,
});

/** @experimental This API is unstable and may change without notice. */
export const AGENT_IDS = [
  "adal",
  "aider-desk",
  "amp",
  "antigravity",
  "augment",
  "claude-code",
  "cline",
  "codearts-agent",
  "codebuddy",
  "codemaker",
  "codestudio",
  "codex",
  "command-code",
  "continue",
  "cortex",
  "crush",
  "cursor",
  "deepagents",
  "devin",
  "dexto",
  "droid",
  "firebender",
  "forgecode",
  "gemini-cli",
  "github-copilot",
  "goose",
  "grok-cli",
  "hermes",
  "ibm-bob",
  "junie",
  "kilo",
  "kimi-cli",
  "kiro-cli",
  "kode",
  "mcpjam",
  "mistral-vibe",
  "mux",
  "neovate",
  "openclaw",
  "opencode",
  "openhands",
  "pi",
  "pochi",
  "qoder",
  "qwen-code",
  "replit",
  "roo",
  "rovodev",
  "tabnine-cli",
  "trae-cn",
  "trae",
  "warp",
  "windsurf",
  "zencoder",
] as const satisfies ReadonlyArray<keyof typeof AGENTS_BY_ID & string>;

/** @experimental This API is unstable and may change without notice. */
export type AgentId = (typeof AGENT_IDS)[number];

/** @experimental This API is unstable and may change without notice. */
export const AgentIdSchema = Schema.Literals(AGENT_IDS).annotate({
  identifier: "AgentId",
  title: "Agent ID",
  description: "Verified coding agent identifier in the capability catalog.",
  examples: ["claude-code", "codex", "cursor"],
});

/** @experimental This API is unstable and may change without notice. */
export const AGENTS = Object.values(AGENTS_BY_ID);
