/**
 * Agent capability catalog for @agentxm/client-core.
 *
 * @experimental All exports from this module are unstable and may change without notice.
 * @packageDocumentation
 */

export {
  AgentIdFromYamlSchema,
  AgentInterfaceSchema,
  AgentSchema,
  CapabilityBaseSchema,
  CapabilityLifecycleSchema,
  CatalogExtensionTypeSchema,
  CommandsCapabilitySchema,
  ConfigFileFormatSchema,
  ConfigFileLocationSchema,
  ConventionSchema,
  DetectionSchema,
  DocLinkSchema,
  InstructionsCapabilitySchema,
  InstructionsImportSyntaxSchema,
  InstructionsKindSchema,
  LastVerifiedDateSchema,
  McpCapabilitySchema,
  McpTransportSchema,
  PermissionCliFlagSchema,
  PermissionGrammarSchema,
  PermissionGrammarStyleSchema,
  PermissionGrantSchema,
  PermissionMechanismSchema,
  PermissionPrerequisiteSchema,
  PermissionsCapabilitySchema,
  RulesCapabilitySchema,
  ScopeSchema,
  ScopedCapabilityBaseSchema,
  SkillsCapabilitySchema,
  StandardSchema,
  StandardsComplianceSchema,
  SubagentsCapabilitySchema,
  SubagentsLayoutSchema,
  type Agent,
  type AgentCapability,
  type AgentIdFromYaml,
  type AgentInterface,
  type CapabilityBase,
  type CapabilityLifecycle,
  type CommandsCapability,
  type ConfigFileFormat,
  type ConfigFileLocation,
  type Convention,
  type Detection,
  type DocLink,
  type InstructionsCapability,
  type InstructionsImportSyntax,
  type InstructionsKind,
  type LastVerifiedDate,
  type McpCapability,
  type McpConfig,
  type McpConfigTarget,
  type McpRemoteDialect,
  type McpServersKey,
  type McpStdioDialect,
  type McpTransport,
  type PermissionCliFlag,
  type PermissionGrammar,
  type PermissionGrammarStyle,
  type PermissionGrant,
  type PermissionMechanism,
  type PermissionPrerequisite,
  type PermissionsCapability,
  type RulesCapability,
  type Scope,
  type ScopedCapabilityBase,
  type SkillsCapability,
  type Standard,
  type StandardsCompliance,
  type SubagentsCapability,
  type SubagentsLayout,
} from "./schema.js";
export { STANDARDS } from "./standards.js";
export {
  EXTENSION_TYPE_CAPABILITY,
  LEAF_EXTENSION_TYPES,
  agentSupportsType,
  capabilityWorks,
  capabilityKinds,
  deriveAgentDescriptor,
  isLeafExtensionType,
  listCapabilities,
  supportedTypes,
  worksOn,
  worksOnAll,
  worksOnExtension,
  type CapabilityKind,
  type CapabilityListing,
  type ExtensionCompatibilityInput,
  type LeafExtensionType,
} from "./derive.js";
export {
  validateCatalogSources,
  type CatalogSource,
  type CatalogValidationIssue,
} from "./validate.js";
export {
  AGENTS,
  AGENTS_BY_ID,
  AGENT_IDS,
  AgentIdSchema,
  type AgentId,
} from "./__generated__/catalog.js";
export { agentById } from "./lookup.js";
