/**
 * Agent capability catalog for @agentxm/client-core.
 *
 * @experimental All exports from this module are unstable and may change without notice.
 * @packageDocumentation
 */

export {
  AgentIdFromYamlSchema,
  AgentCapabilitiesSchema,
  AgentInterfaceSchema,
  AgentSchema,
  ActiveAxmSupportSchema,
  AvailabilitySchema,
  AxmSupportSchema,
  CANONICAL_HOOK_EVENTS,
  CANONICAL_HOOK_EVENT_IDS,
  CatalogExtensionTypeSchema,
  CanonicalHookEventIdSchema,
  CanonicalHookEventSchema,
  CommandsExtensionCapabilitySchema,
  ConfigFileFormatSchema,
  ConfigFileLocationSchema,
  ConventionSchema,
  DetectionMarkerSchema,
  DetectionSchema,
  DetectionSignalSchema,
  DocLinkSchema,
  InactiveAxmSupportSchema,
  LastVerifiedDateSchema,
  LEAF_EXTENSION_TYPES,
  FilesExtensionCapabilitySchema,
  HookBlockOutcomeSchema,
  HookCommandNameSerializationSchema,
  HookDecisionCapabilitySchema,
  HookEventMappingSchema,
  HookEventTierSchema,
  HookMatcherKindSchema,
  HookMatcherSerializationSchema,
  HookMatcherSchema,
  HookMechanismFamilySchema,
  HookModifyOperationSchema,
  HookTimeoutSerializationSchema,
  HooksCanonicalModelSchema,
  McpEnvExpansionSchema,
  McpExtensionCapabilitySchema,
  McpTransportSchema,
  NativeCapabilityBaseSchema,
  PermissionCliFlagSchema,
  PermissionGrammarSchema,
  PermissionGrammarStyleSchema,
  PermissionGrantSchema,
  PermissionMechanismSchema,
  PermissionPrerequisiteSchema,
  PermissionsExtensionCapabilitySchema,
  PluginDescriptorSchema,
  PluginDetectionConfigKeySchema,
  PluginDetectionPathSchema,
  PluginDetectionSchema,
  PluginDistributionMechanismSchema,
  PluginDistributionSchema,
  RuleInstructionsImportSyntaxSchema,
  RuleInstructionsKindSchema,
  RulesExtensionCapabilitySchema,
  ScopeSchema,
  ScopeDetectionSchema,
  SkillsExtensionCapabilitySchema,
  StandardSchema,
  StandardsComplianceSchema,
  SubagentsExtensionCapabilitySchema,
  SubagentsLayoutSchema,
  SUPPORTED_AXM_SUPPORT,
  UrlSchema,
  VendorStatusSchema,
  type Agent,
  type AgentCapabilities,
  type AgentExtensionCapability,
  type ActiveAxmSupport,
  type AgentIdFromYaml,
  type AgentInterface,
  type Availability,
  type AxmCapabilityState,
  type AxmSupport,
  type CanonicalHookEvent,
  type CanonicalHookEventId,
  type CommandsExtensionCapability,
  type ConfigFileFormat,
  type ConfigFileLocation,
  type Convention,
  type Detection,
  type DetectionMarker,
  type DetectionSignal,
  type DocLink,
  type FilesExtensionCapability,
  type HookBlockOutcome,
  type HookCommandNameSerialization,
  type HookDecisionCapability,
  type HookEventMapping,
  type HookEventTier,
  type HookMatcher,
  type HookMatcherKind,
  type HookMatcherSerialization,
  type HookMechanismFamily,
  type HookModifyOperation,
  type HookTimeoutSerialization,
  type HooksCanonicalModel,
  type HooksSerializer,
  type HooksWriter,
  type InactiveAxmSupport,
  type LastVerifiedDate,
  type LeafExtensionType,
  type McpEnvExpansion,
  type McpExtensionCapability,
  type McpConfig,
  type McpConfigTarget,
  type McpRemoteDialect,
  type McpServersKey,
  type McpStdioDialect,
  type McpTransport,
  type PermissionCliFlag,
  type PermissionGrammar,
  type PermissionGrammarStyle,
  type PermissionGrant,
  type PermissionMechanism,
  type PermissionPrerequisite,
  type PermissionsExtensionCapability,
  type NativeCapability,
  type NativeCapabilityBase,
  type PluginDescriptor,
  type PluginDetection,
  type PluginDetectionConfigKey,
  type PluginDetectionPath,
  type PluginDistribution,
  type PluginDistributionMechanism,
  type RuleInstructionsImportSyntax,
  type RuleInstructionsKind,
  type RulesExtensionCapability,
  type Scope,
  type ScopeDetection,
  type SkillsExtensionCapability,
  type Standard,
  type StandardsCompliance,
  type SubagentsExtensionCapability,
  type SubagentsLayout,
  type Url,
  type VendorStatus,
} from "./schema.js";
export { STANDARDS } from "../extension-types/standards.js";
export {
  agentCapabilityStatus,
  agentSupportsType,
  axmIntegrationStatus,
  deriveAgentDescriptor,
  deriveHookPortability,
  getSupportedAgentsForExtension,
  getSupportedAgentsForExtensionType,
  getSupportedAgentsForExtensionTypes,
  getSupportedExtensionTypesForAgent,
  isCapabilitySupported,
  isLeafExtensionType,
  listCapabilities,
  toNativeAgent,
  type AgentCapabilityStatus,
  type AxmIntegrationStatus,
  type CapabilityListing,
  type ExtensionCompatibilityInput,
  type HookDecisionKind,
  type HookPortabilityRequirement,
  type HookPortabilityVerdict,
  type NativeAgent,
  type NativeAgentCapabilities,
} from "./derive.js";
export { AGENTS, AGENTS_BY_ID, AGENT_IDS, AgentIdSchema, type AgentId } from "./catalog.js";
export { agentById } from "./lookup.js";
