/**
 * Agent capability catalog for @agentxm/client-core.
 *
 * @experimental All exports from this module are unstable and may change without notice.
 * @packageDocumentation
 */

export {
  AgentIdFromYamlSchema,
  AgentCapabilitiesSchema,
  AgentInterfaceSchema,
  AgentSchema,
  ActiveAxmSupportSchema,
  AvailabilitySchema,
  AxmSupportSchema,
  CatalogExtensionTypeSchema,
  CanonicalCapabilityBaseSchema,
  CommandsExtensionCapabilitySchema,
  ConfigFileFormatSchema,
  ConfigFileLocationSchema,
  ConventionSchema,
  DetectionMarkerSchema,
  DetectionSchema,
  DetectionSignalSchema,
  DocLinkSchema,
  InactiveAxmSupportSchema,
  LastVerifiedDateSchema,
  LEAF_EXTENSION_TYPES,
  FilesExtensionCapabilitySchema,
  McpEnvExpansionSchema,
  McpExtensionCapabilitySchema,
  McpTransportSchema,
  PermissionCliFlagSchema,
  PermissionGrammarSchema,
  PermissionGrammarStyleSchema,
  PermissionGrantSchema,
  PermissionMechanismSchema,
  PermissionPrerequisiteSchema,
  PermissionsExtensionCapabilitySchema,
  PluginDescriptorSchema,
  PluginDetectionConfigKeySchema,
  PluginDetectionPathSchema,
  PluginDetectionSchema,
  PluginDistributionMechanismSchema,
  PluginDistributionSchema,
  RuleInstructionsImportSyntaxSchema,
  RuleInstructionsKindSchema,
  RulesExtensionCapabilitySchema,
  ScopeSchema,
  ScopeDetectionSchema,
  SkillsExtensionCapabilitySchema,
  StandardSchema,
  StandardsComplianceSchema,
  SubagentsExtensionCapabilitySchema,
  SubagentsLayoutSchema,
  SUPPORTED_AXM_SUPPORT,
  UrlSchema,
  VendorStatusSchema,
  type Agent,
  type AgentCapabilities,
  type AgentExtensionCapability,
  type ActiveAxmSupport,
  type AgentIdFromYaml,
  type AgentInterface,
  type Availability,
  type AxmCapabilityState,
  type AxmSupport,
  type CanonicalCapability,
  type CanonicalCapabilityBase,
  type CommandsExtensionCapability,
  type ConfigFileFormat,
  type ConfigFileLocation,
  type Convention,
  type Detection,
  type DetectionMarker,
  type DetectionSignal,
  type DocLink,
  type FilesExtensionCapability,
  type InactiveAxmSupport,
  type LastVerifiedDate,
  type LeafExtensionType,
  type McpEnvExpansion,
  type McpExtensionCapability,
  type McpConfig,
  type McpConfigTarget,
  type McpRemoteDialect,
  type McpServersKey,
  type McpStdioDialect,
  type McpTransport,
  type PermissionCliFlag,
  type PermissionGrammar,
  type PermissionGrammarStyle,
  type PermissionGrant,
  type PermissionMechanism,
  type PermissionPrerequisite,
  type PermissionsExtensionCapability,
  type PluginDescriptor,
  type PluginDetection,
  type PluginDetectionConfigKey,
  type PluginDetectionPath,
  type PluginDistribution,
  type PluginDistributionMechanism,
  type RuleInstructionsImportSyntax,
  type RuleInstructionsKind,
  type RulesExtensionCapability,
  type Scope,
  type ScopeDetection,
  type SkillsExtensionCapability,
  type Standard,
  type StandardsCompliance,
  type SubagentsExtensionCapability,
  type SubagentsLayout,
  type Url,
  type VendorStatus,
} from "./schema.js";
export { STANDARDS } from "../extension-types/standards.js";
export {
  agentCapabilityStatus,
  agentSupportsType,
  axmIntegrationStatus,
  deriveAgentDescriptor,
  getSupportedAgentsForExtension,
  getSupportedAgentsForExtensionType,
  getSupportedAgentsForExtensionTypes,
  getSupportedExtensionTypesForAgent,
  isCapabilitySupported,
  isLeafExtensionType,
  listCapabilities,
  toCanonicalAgent,
  type AgentCapabilityStatus,
  type AxmIntegrationStatus,
  type CanonicalAgent,
  type CanonicalAgentCapabilities,
  type CapabilityListing,
  type ExtensionCompatibilityInput,
} from "./derive.js";
export { AGENTS, AGENTS_BY_ID, AGENT_IDS, AgentIdSchema, type AgentId } from "./catalog.js";
export { agentById } from "./lookup.js";
