/**
 * Generate the bundled @agentxm/skills/axm source that `axm setup` materializes
 * into a new workspace. Reads the canonical workspace copy under
 * .axm/extensions/@agentxm/skills/axm so the bundled constants never drift
 * from the published skill.
 */

// @effect-diagnostics nodeBuiltinImport:off globalConsole:off — build-time generation script, not Effect code
import * as fs from "node:fs";
import * as path from "node:path";
import { format as formatWithPrettier, resolveConfig as resolvePrettierConfig } from "prettier";

import { validateBundledAxmSkillContract } from "./bundled-axm-skill-contract.js";

const CLI_ROOT = path.join(import.meta.dirname, "..");
const REPO_ROOT = path.join(CLI_ROOT, "..", "..");
const SKILL_DIR = path.join(REPO_ROOT, ".axm", "extensions", "@agentxm", "skills", "axm");
const SKILL_JSON_PATH = path.join(SKILL_DIR, "skill.json");
const SKILL_SRC_DIR = path.join(SKILL_DIR, "src");
const OUTPUT_PATH = path.join(CLI_ROOT, "src", "__generated__", "bundled-axm-skill.ts");

const skillJsonRaw = fs.readFileSync(SKILL_JSON_PATH, "utf-8");

interface BundledSourceFile {
  readonly path: string;
  readonly base64: string;
}

const collectSourceFiles = (
  directory: string,
  relativeRoot = "",
): ReadonlyArray<BundledSourceFile> =>
  fs
    .readdirSync(directory, { withFileTypes: true })
    .sort((left, right) => left.name.localeCompare(right.name))
    .flatMap((entry) => {
      const absolutePath = path.join(directory, entry.name);
      const relativePath = path.posix.join(relativeRoot, entry.name);
      if (entry.isDirectory()) return collectSourceFiles(absolutePath, relativePath);
      if (!entry.isFile()) {
        throw new Error(
          `unsupported bundled skill entry: ${path.relative(REPO_ROOT, absolutePath)}`,
        );
      }
      return [{ path: relativePath, base64: fs.readFileSync(absolutePath).toString("base64") }];
    });

const sourceFiles = collectSourceFiles(SKILL_SRC_DIR);
if (!sourceFiles.some((file) => file.path === "SKILL.md")) {
  throw new Error(`missing ${path.relative(REPO_ROOT, path.join(SKILL_SRC_DIR, "SKILL.md"))}`);
}
const skillMd = fs.readFileSync(path.join(SKILL_SRC_DIR, "SKILL.md"), "utf-8");

const skillJson: unknown = JSON.parse(skillJsonRaw);
if (
  typeof skillJson !== "object" ||
  skillJson === null ||
  !("version" in skillJson) ||
  typeof skillJson.version !== "string" ||
  skillJson.version.length === 0
) {
  throw new Error(`missing string "version" in ${path.relative(REPO_ROOT, SKILL_JSON_PATH)}`);
}
const version = skillJson.version;
const compatibility = validateBundledAxmSkillContract(version, skillMd);

const source = `/**
 * @generated by cli:generate:bundled-axm-skill (packages/cli/scripts/generate-bundled-axm-skill.ts)
 * Source:     .axm/extensions/@agentxm/skills/axm/skill.json and the complete .axm/extensions/@agentxm/skills/axm/src tree
 * Regenerate: pnpm exec nx run cli:generate:bundled-axm-skill
 * DO NOT EDIT - changes are overwritten on regeneration.
 */

export const AXM_SKILL_VERSION = ${JSON.stringify(version)};

export const AXM_SKILL_CLI_VERSION = ${JSON.stringify(compatibility.cliVersion)};

export const AXM_SKILL_CLI_VERSION_RANGE = ${JSON.stringify(compatibility.cliVersionRange)};

export const AXM_SKILL_JSON = ${JSON.stringify(skillJsonRaw)};

export const AXM_SKILL_SOURCE_FILES = ${JSON.stringify(sourceFiles)};

export const AXM_SKILL_MD = ${JSON.stringify(skillMd)};
`;

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });

const prettierConfig = (await resolvePrettierConfig(OUTPUT_PATH)) ?? {};
const formatted = await formatWithPrettier(source, {
  ...prettierConfig,
  filepath: OUTPUT_PATH,
  parser: "typescript",
});

fs.writeFileSync(OUTPUT_PATH, formatted);
console.log(`Generated: ${path.relative(CLI_ROOT, OUTPUT_PATH)}`);
