/**
 * Generate the agent capability catalog module and YAML JSON Schema.
 */

/* eslint-disable @nx/enforce-module-boundaries -- Generator reads core source schemas directly so generated catalog output cannot drift behind source YAML. */

// @effect-diagnostics nodeBuiltinImport:off globalConsole:off — build-time generator script, not Effect code
import * as fs from "node:fs";
import * as path from "node:path";
import * as JsonSchema from "effect/JsonSchema";
import * as Schema from "effect/Schema";
import { format as formatWithPrettier, resolveConfig as resolvePrettierConfig } from "prettier";
import YAML from "yaml";
import { AgentSchema, type Agent } from "../../core/src/unstable/agent-capabilities/schema.js";
import {
  validateCatalogSources,
  type CatalogSource,
} from "../../core/src/unstable/agent-capabilities/validate.js";

const CLI_ROOT = path.join(import.meta.dirname, "..");
const CORE_ROOT = path.join(import.meta.dirname, "../../core");
const CATALOG_ROOT = path.join(CORE_ROOT, "src/unstable/agent-capabilities");
const AGENTS_DIR = path.join(CATALOG_ROOT, "data/agents");
const GENERATED_DIR = path.join(CATALOG_ROOT, "__generated__");
const GENERATED_CATALOG_PATH = path.join(GENERATED_DIR, "catalog.ts");
const AGENT_SCHEMA_PATH = path.join(GENERATED_DIR, "agent.schema.json");

const decodeAgent = (input: unknown): Agent =>
  Schema.decodeUnknownSync(AgentSchema)(input, { onExcessProperty: "error" });

const toErrorMessage = (error: unknown): string =>
  error instanceof Error ? error.message : String(error);

const readAgentYaml = (filename: string): CatalogSource => {
  const fullPath = path.join(AGENTS_DIR, filename);
  const raw = fs.readFileSync(fullPath, "utf8");
  const document = YAML.parseDocument(raw);
  if (document.errors.length > 0) {
    const message = document.errors.map((error) => error.message).join("; ");
    throw new Error(`${filename}: ${message}`);
  }
  const parsed: unknown = document.toJSON();
  try {
    return { filename, agent: decodeAgent(parsed) };
  } catch (error: unknown) {
    throw new Error(`${filename}: ${toErrorMessage(error)}`, { cause: error });
  }
};

const readCatalogSources = (): ReadonlyArray<CatalogSource> => {
  const filenames = fs
    .readdirSync(AGENTS_DIR)
    .filter((filename) => filename.endsWith(".yaml"))
    .sort();

  return filenames.map(readAgentYaml);
};

const toDraft07SchemaFile = (schema: Schema.Top) => {
  const document = JsonSchema.toDocumentDraft07(Schema.toJsonSchemaDocument(schema));

  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    ...document.schema,
    ...(Object.keys(document.definitions).length > 0 ? { definitions: document.definitions } : {}),
  };
};

const formatFile = async (filepath: string, content: string, parser: "json" | "typescript") => {
  const prettierConfig = (await resolvePrettierConfig(filepath)) ?? {};
  return formatWithPrettier(content, {
    ...prettierConfig,
    filepath,
    parser,
  });
};

const literalList = (values: ReadonlyArray<string>): string =>
  `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;

const generateCatalogModule = (agents: ReadonlyArray<Agent>): string => {
  const agentIds = agents.map((agent) => agent.id);
  const agentsById = Object.fromEntries(agents.map((agent) => [agent.id, agent]));

  return `/**
 * @generated by core:generate:agent-catalog (packages/cli/scripts/generate-agent-catalog.ts)
 * Source:     packages/core/src/unstable/agent-capabilities/data/agents/*.yaml
 * Regenerate: pnpm exec nx run core:generate:agent-catalog
 * DO NOT EDIT - changes are overwritten on regeneration.
 */

import * as Schema from "effect/Schema";
import type { Agent } from "../schema.js";

/** @experimental This API is unstable and may change without notice. */
export const AGENT_IDS = ${literalList(agentIds)} as const;

/** @experimental This API is unstable and may change without notice. */
export type AgentId = (typeof AGENT_IDS)[number];

/** @experimental This API is unstable and may change without notice. */
export const AgentIdSchema = Schema.Literals([...AGENT_IDS]).annotate({
  identifier: "AgentId",
  title: "Agent ID",
  description: "Verified coding agent identifier in the capability catalog.",
  examples: ["claude-code", "codex", "cursor"],
});

/** @experimental This API is unstable and may change without notice. */
export const AGENTS = ${JSON.stringify(agents, null, 2)} as const satisfies ReadonlyArray<Agent>;

/** @experimental This API is unstable and may change without notice. */
export const AGENTS_BY_ID = ${JSON.stringify(
    agentsById,
    null,
    2,
  )} as const satisfies Record<AgentId, Agent>;
`;
};

const sources = readCatalogSources();
const validationIssues = validateCatalogSources(sources);
if (validationIssues.length > 0) {
  const details = validationIssues.map((issue) => `- ${issue.path}: ${issue.message}`).join("\n");
  throw new Error(`Agent catalog validation failed:\n${details}`);
}

const agents = sources.map((source) => source.agent);

const catalogModule = await formatFile(
  GENERATED_CATALOG_PATH,
  generateCatalogModule(agents),
  "typescript",
);
fs.writeFileSync(GENERATED_CATALOG_PATH, catalogModule);
console.log(`Generated: ${path.relative(CLI_ROOT, GENERATED_CATALOG_PATH)}`);

const agentJsonSchema = await formatFile(
  AGENT_SCHEMA_PATH,
  JSON.stringify({
    $comment:
      "@generated by core:generate:agent-catalog (packages/cli/scripts/generate-agent-catalog.ts). Source: packages/core/src/unstable/agent-capabilities/schema.ts. Regenerate: pnpm exec nx run core:generate:agent-catalog. DO NOT EDIT.",
    ...toDraft07SchemaFile(AgentSchema),
  }),
  "json",
);
fs.writeFileSync(AGENT_SCHEMA_PATH, agentJsonSchema);
console.log(`Generated: ${path.relative(CLI_ROOT, AGENT_SCHEMA_PATH)}`);
