/**
 * Generate the bundled @agentxm/skills/axm source that `axm setup` materializes
 * into a new workspace. Reads the canonical workspace copy under
 * .axm/extensions/@agentxm/skills/axm so the bundled constants never drift
 * from the published skill.
 */

// @effect-diagnostics nodeBuiltinImport:off globalConsole:off — build-time generation script, not Effect code
import * as fs from "node:fs";
import * as path from "node:path";
import { format as formatWithPrettier, resolveConfig as resolvePrettierConfig } from "prettier";

const CLI_ROOT = path.join(import.meta.dirname, "..");
const REPO_ROOT = path.join(CLI_ROOT, "..", "..");
const SKILL_DIR = path.join(REPO_ROOT, ".axm", "extensions", "@agentxm", "skills", "axm");
const SKILL_JSON_PATH = path.join(SKILL_DIR, "skill.json");
const SKILL_MD_PATH = path.join(SKILL_DIR, "src", "SKILL.md");
const OUTPUT_PATH = path.join(CLI_ROOT, "src", "__generated__", "bundled-axm-skill.ts");

const skillJsonRaw = fs.readFileSync(SKILL_JSON_PATH, "utf-8");
const skillMd = fs.readFileSync(SKILL_MD_PATH, "utf-8");

const skillJson: unknown = JSON.parse(skillJsonRaw);
if (
  typeof skillJson !== "object" ||
  skillJson === null ||
  !("version" in skillJson) ||
  typeof skillJson.version !== "string" ||
  skillJson.version.length === 0
) {
  throw new Error(`missing string "version" in ${path.relative(REPO_ROOT, SKILL_JSON_PATH)}`);
}
const version = skillJson.version;

const source = `/**
 * Generated by packages/cli/scripts/generate-bundled-axm-skill.ts.
 * Do not edit by hand. Run \`pnpm nx run cli:generate-bundled-axm-skill\` to regenerate.
 */

export const AXM_SKILL_VERSION = ${JSON.stringify(version)};

export const AXM_SKILL_JSON = ${JSON.stringify(skillJsonRaw)};

export const AXM_SKILL_MD = ${JSON.stringify(skillMd)};
`;

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });

const prettierConfig = (await resolvePrettierConfig(OUTPUT_PATH)) ?? {};
const formatted = await formatWithPrettier(source, {
  ...prettierConfig,
  filepath: OUTPUT_PATH,
  parser: "typescript",
});

fs.writeFileSync(OUTPUT_PATH, formatted);
console.log(`Generated: ${path.relative(CLI_ROOT, OUTPUT_PATH)}`);
