/**
 * Generate bundled CLI help topic source from markdown files and JSON schemas.
 */

// @effect-diagnostics nodeBuiltinImport:off globalConsole:off — build-time help topic generation script, not Effect code
import * as fs from "node:fs";
import * as path from "node:path";
import { format as formatWithPrettier, resolveConfig as resolvePrettierConfig } from "prettier";

import { stripRegionMarkers } from "./type-enumerations.js";

const CLI_ROOT = path.join(import.meta.dirname, "..");
const TOPICS_DIR = path.join(CLI_ROOT, "help/topics");
const OUTPUT_PATH = path.join(CLI_ROOT, "src/__generated__/help-topics.ts");
const SCHEMAS_DIR = path.join(CLI_ROOT, "../core/site-content/__generated__/schemas");

type HelpTopicKind = "markdown" | "json-schema";

interface HelpTopic {
  readonly name: string;
  readonly content: string;
  readonly kind: HelpTopicKind;
}

// Index-table descriptions are curated by hand in
// src/root/help/help-topic-descriptions.ts (a `satisfies` clause there fails
// the typecheck when a topic gains or loses a description).

const topicFiles = fs
  .readdirSync(TOPICS_DIR)
  .filter((file) => file.endsWith(".md"))
  .sort((a, b) => a.localeCompare(b));

// Topic sources carry `axm:generated` region markers so the enumeration
// generator knows what it owns. They are plumbing, not documentation, so they
// are stripped before the topic reaches a reader.
const markdownTopics = topicFiles.map((file): HelpTopic => {
  const name = path.basename(file, ".md");
  const content = stripRegionMarkers(fs.readFileSync(path.join(TOPICS_DIR, file), "utf-8"));
  return { name, content, kind: "markdown" };
});

const schemaFiles = fs
  .readdirSync(SCHEMAS_DIR)
  .filter((file) => file.endsWith(".schema.json"))
  .sort((a, b) => a.localeCompare(b));

const schemaTopics = schemaFiles.map((file): HelpTopic => {
  const name = `${path.basename(file, ".schema.json")}-schema`;
  const content = fs.readFileSync(path.join(SCHEMAS_DIR, file), "utf-8").trimEnd();
  return { name, content, kind: "json-schema" };
});

const topics = [...markdownTopics, ...schemaTopics].sort((a, b) => a.name.localeCompare(b.name));
const seenTopicNames = new Set<string>();
for (const { name } of topics) {
  if (seenTopicNames.has(name)) {
    throw new Error(`duplicate help topic name: ${name}`);
  }
  seenTopicNames.add(name);
}

const topicNames = topics.map(({ name }) => name);
const topicEntries = topics
  .map(({ name, content }) => `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`)
  .join("\n");
const topicKindEntries = topics
  .map(({ name, kind }) => `  ${JSON.stringify(name)}: ${JSON.stringify(kind)},`)
  .join("\n");

const source = `/**
 * @generated by cli:generate:help-topics (packages/cli/scripts/generate-help-topics.ts)
 * Source:     packages/cli/help/topics/*.md and packages/cli/site-content/__generated__/schemas/*.schema.json
 * Regenerate: pnpm exec nx run cli:generate:help-topics
 * DO NOT EDIT - changes are overwritten on regeneration.
 */

export const HELP_TOPIC_NAMES = ${JSON.stringify(topicNames)} as const;

export type HelpTopicName = (typeof HELP_TOPIC_NAMES)[number];

export const HELP_TOPICS: Record<HelpTopicName, string> = {
${topicEntries}
};

export type HelpTopicKind = "markdown" | "json-schema";

export const HELP_TOPIC_KINDS = {
${topicKindEntries}
} as const satisfies Record<HelpTopicName, HelpTopicKind>;
`;

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });

const prettierConfig = (await resolvePrettierConfig(OUTPUT_PATH)) ?? {};
const formatted = await formatWithPrettier(source, {
  ...prettierConfig,
  filepath: OUTPUT_PATH,
  parser: "typescript",
});

fs.writeFileSync(OUTPUT_PATH, formatted);
console.log(`Generated: ${path.relative(CLI_ROOT, OUTPUT_PATH)}`);
