/**
 * Generate bundled CLI help topic source from markdown files.
 */

// @effect-diagnostics nodeBuiltinImport:off globalConsole:off — build-time help topic generation script, not Effect code
import * as fs from "node:fs";
import * as path from "node:path";
import { format as formatWithPrettier, resolveConfig as resolvePrettierConfig } from "prettier";

const CLI_ROOT = path.join(import.meta.dirname, "..");
const TOPICS_DIR = path.join(CLI_ROOT, "help/topics");
const OUTPUT_PATH = path.join(CLI_ROOT, "src/__generated__/help-topics.ts");

const topicFiles = fs
  .readdirSync(TOPICS_DIR)
  .filter((file) => file.endsWith(".md"))
  .sort((a, b) => a.localeCompare(b));

const topics = topicFiles.map((file) => {
  const name = path.basename(file, ".md");
  const content = fs.readFileSync(path.join(TOPICS_DIR, file), "utf-8");
  return { name, content };
});

const topicNames = topics.map(({ name }) => name);
const topicEntries = topics
  .map(({ name, content }) => `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`)
  .join("\n");

const source = `/**
 * Generated by packages/cli/scripts/generate-help-topics.ts.
 * Do not edit by hand.
 */

export const HELP_TOPIC_NAMES = ${JSON.stringify(topicNames)} as const;

export type HelpTopicName = (typeof HELP_TOPIC_NAMES)[number];

export const HELP_TOPICS: Record<HelpTopicName, string> = {
${topicEntries}
};
`;

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });

const prettierConfig = (await resolvePrettierConfig(OUTPUT_PATH)) ?? {};
const formatted = await formatWithPrettier(source, {
  ...prettierConfig,
  filepath: OUTPUT_PATH,
  parser: "typescript",
});

fs.writeFileSync(OUTPUT_PATH, formatted);
console.log(`Generated: ${path.relative(CLI_ROOT, OUTPUT_PATH)}`);
