/**
 * Generate the cli-e2e extension-type matrix from the canonical type table.
 *
 * The e2e package must not depend on the product library packages (enforced by
 * `verify-e2e-boundaries`), so it cannot import the table it needs to drive a
 * per-type suite. Emitting plain literals into the package keeps the suite
 * catalog-driven — a new extension type shows up as a new row, and a row with
 * no coverage has to be answered for — without adding an edge to the graph.
 */

/* eslint-disable @nx/enforce-module-boundaries -- Generator must read kernel source directly so the emitted matrix cannot drift behind stale dist output. */
// @effect-diagnostics nodeBuiltinImport:off globalConsole:off — build-time generation script, not Effect code
import * as fs from "node:fs";
import * as path from "node:path";
import { format as formatWithPrettier, resolveConfig as resolvePrettierConfig } from "prettier";

import { exemptedObligations } from "../src/unstable/extension-types/parity/exemptions.js";
import { EXTENSION_LIFECYCLE_CONTRACT } from "../src/unstable/extension-types/parity/lifecycle.js";
import { obligationsVerifiedBy } from "../src/unstable/extension-types/parity/obligations.js";
import {
  EXTENSION_TYPE_TABLE,
  extensionTypes,
} from "@agentxm/extension-model/unstable/extensions/common";
import { EXTENSION_CONFIGURED_AGENT_POLICY } from "../../workspace-state/src/workspace/configured-agent-outcomes.js";

const CORE_ROOT = path.join(import.meta.dirname, "..");
const OUTPUT_PATH = path.join(CORE_ROOT, "../cli-e2e/src/__generated__/extension-type-matrix.ts");

const e2eExemptions: Readonly<Record<string, ReadonlyArray<string>>> = exemptedObligations("e2e");
const e2eObligations = obligationsVerifiedBy("e2e");

// Publishability is a CLI-owned decision (`PUBLISHABLE_TYPES`), so it is not
// emitted here — importing it would invert the core → cli dependency. The e2e
// suite carries its own total record of per-type publishers instead.
const rows = extensionTypes.map((type) => {
  const row = EXTENSION_TYPE_TABLE[type];
  const lifecycle = EXTENSION_LIFECYCLE_CONTRACT[type];
  return {
    type,
    plural: row.plural,
    label: row.label,
    sentenceLabel: row.sentenceLabel,
    placement: row.placement,
    installInputs: row.installInputs,
    workspaceCapability: row.workspaceCapability,
    mutations: lifecycle.mutations,
    scopeSupport: lifecycle.scopeSupport,
    updateSelection: lifecycle.updateSelection,
    activationConfirmation: lifecycle.activationConfirmation,
    configuredAgentPolicy: EXTENSION_CONFIGURED_AGENT_POLICY[type].kind,
    e2eObligations,
    e2eExemptions: e2eExemptions[type] ?? [],
  };
});

const rowEntries = rows
  .map(
    (row) => `  {
    type: ${JSON.stringify(row.type)},
    plural: ${JSON.stringify(row.plural)},
    label: ${JSON.stringify(row.label)},
    sentenceLabel: ${JSON.stringify(row.sentenceLabel)},
    placement: ${JSON.stringify(row.placement)},
    installInputs: ${JSON.stringify(row.installInputs)},
    workspaceCapability: ${JSON.stringify(row.workspaceCapability)},
    mutations: ${JSON.stringify(row.mutations)},
    scopeSupport: ${JSON.stringify(row.scopeSupport)},
    updateSelection: ${JSON.stringify(row.updateSelection)},
    activationConfirmation: ${JSON.stringify(row.activationConfirmation)},
    configuredAgentPolicy: ${JSON.stringify(row.configuredAgentPolicy)},
    e2eObligations: ${JSON.stringify(row.e2eObligations)},
    e2eExemptions: ${JSON.stringify(row.e2eExemptions)},
  },`,
  )
  .join("\n");

const source = `/**
 * @generated by extension-management:generate:e2e-extension-matrix (packages/extension-management/scripts/generate-e2e-extension-matrix.ts)
 * Source:     EXTENSION_TYPE_TABLE and the parity exemption ledger in packages/extension-management and packages/extension-model src/unstable
 * Regenerate: pnpm exec nx run extension-management:generate:e2e-extension-matrix
 * DO NOT EDIT - changes are overwritten on regeneration.
 *
 * Plain literals on purpose: packages/cli-e2e must not depend on
 * the product library packages, so the type table is copied in rather than imported.
 */

export const EXTENSION_TYPE_MATRIX = [
${rowEntries}
] as const;

export type ExtensionTypeMatrixRow = (typeof EXTENSION_TYPE_MATRIX)[number];

export type MatrixExtensionType = ExtensionTypeMatrixRow["type"];
`;

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });

const prettierConfig = (await resolvePrettierConfig(OUTPUT_PATH)) ?? {};
const formatted = await formatWithPrettier(source, {
  ...prettierConfig,
  filepath: OUTPUT_PATH,
  parser: "typescript",
});

fs.writeFileSync(OUTPUT_PATH, formatted);
console.log(`Generated: ${path.relative(CORE_ROOT, OUTPUT_PATH)}`);
