/**
 * Area barrel for the package public surface.
 *
 * @experimental This API is unstable and may change without notice.
 */

export {
  AgentIdSchema,
  type Author,
  AuthorSchema,
  CONTAINER_EXTENSION_TYPES,
  CommonManifestBaseFields,
  type ConfigurableAgentId,
  ConfigurableAgentIdSchema,
  type ContainerType,
  EXTENSION_NAME_PATTERN,
  EXTENSION_ONLY_TYPES,
  type ExtensionDependencyConstraintMap,
  ExtensionDependencyConstraintMapSchema,
  type ExtensionFqn,
  type ExtensionFqnParts,
  ExtensionFqnPartsSchema,
  ExtensionFqnSchema,
  type ExtensionName,
  ExtensionNameSchema,
  type ExtensionSpec,
  ExtensionSpecSchema,
  type ExtensionType,
  type ExtensionTypePlural,
  ExtensionTypePluralSchema,
  ExtensionTypeSchema,
  type ExtensionVisibility,
  ExtensionVisibilitySchema,
  FQN_PATTERN,
  LicenseSchema,
  NON_PACK_FQN_PATTERN,
  type NonPackExtensionDependencyConstraintMap,
  NonPackExtensionDependencyConstraintMapSchema,
  type NonPackExtensionFqn,
  NonPackExtensionFqnSchema,
  type NonPackExtensionTypePlural,
  NonPackManifestFields,
  PACK_FQN_PATTERN,
  PER_AGENT_EXTENSION_TYPES,
  type PackFqn,
  PackFqnSchema,
  type PackSpec,
  PackSpecSchema,
  type PerAgentType,
  type PublishOptions,
  PublishOptionsSchema,
  WORKSPACE_CAPABILITY_EXTENSION_TYPES,
  type WorkspaceCapabilityType,
  decodeExtensionNameSync,
  extensionTypeFromPlural,
  extensionTypeLabels,
  extensionTypePluralLabels,
  extensionTypePluralSegments,
  extensionTypePluralSentenceLabels,
  extensionTypeSentenceLabels,
  extensionTypeToPlural,
  extensionTypes,
  isExtensionType,
  isExtensionTypePlural,
  nonPackExtensionTypePluralSegments,
  parseExtensionFqnParts,
  parseExtensionSpecParts,
  toAuthor,
  toExtensionType,
  toExtensionTypePlural,
} from "./common.js";
export {
  type ReleaseAgeExcludePattern,
  ReleaseAgeExcludePatternSchema,
  matchesReleaseAgeExcludePattern,
} from "./fqn-pattern.js";
export { FqnInvalidError, formatFqn, parseFqn, parseFqnOrThrow } from "./fqn.js";
export {
  HANDLE_PATTERN,
  HANDLE_PATTERN_SOURCE,
  type Handle,
  HandleSchema,
  SLUG_PATTERN,
  SLUG_PATTERN_SOURCE,
  type Slug,
  SlugSchema,
  decodeHandleSync,
  decodeSlugSync,
  handleFromSlug,
  normalizeHandle,
  normalizeSlug,
  slugFromHandle,
} from "./handle.js";
export { parseLicenseExpression } from "./license.js";
export {
  EXTENSION_METADATA_MAX_BYTES,
  EXTENSION_METADATA_MAX_DEPTH,
  type ExtensionMetadata,
  ExtensionMetadataSchema,
  extensionMetadataCompactByteLength,
  extensionMetadataContainerDepth,
} from "./manifest-metadata.js";
export {
  type RegistrySourcePatternParts,
  RegistrySourcePatternPartsSchema,
  RegistrySourcePatternSchema,
  type RegistrySourceRefParts,
  RegistrySourceRefPartsSchema,
  RegistrySourceRefSchema,
  type SourceQualifiedRegistrySourcePatternParts,
  formatRegistrySourcePatternParts,
  formatRegistrySourceRef,
  parseRegistrySourcePatternParts,
  parseRegistrySourceRef,
  parseSourceQualifiedRegistrySourcePatternParts,
} from "./registry-source.js";
