name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: corepack enable

      - run: pnpm install --frozen-lockfile

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Run all checks
        if: github.ref == 'refs/heads/main'
        run: pnpm nx run-many -t build typecheck test e2e lint format-check

      - name: Run affected checks
        if: github.event_name == 'pull_request'
        run: pnpm nx affected -t build typecheck test e2e lint format-check
